### ISSUE TITLE
Savage dice in attack rolls

### ISSUE THREAD

**Issue by parvusdomus** [lipefl/swade-tools#1]
When you do an attack roll from the weapon dialog, the savage dice does not explode, while the skill dice does. Heard that his might be a Foundry issue actually but just in case (works properly in the better rolls and better rolls 2 modules).

**Comment by parvusdomus** [comment]
When you get a raise, and click the message in the chat card for it to roll the damage it doesn't add the extra d6 for damage.

**Comment by lipefl** [comment]
solved. It was a typo
