### ISSUE TITLE
Custom status icons in 1.0.1 world

### ISSUE THREAD

**Issue by deanopalooza** [lipefl/swade-tools#102]
Just a note.   See Issue #86 .  Core and CUB no longer get along for setting customized status effect icons, making the requested "deactivate" option in #86 superfluous.   Don't know if you want to comment it out in case the functionality returns, or hide altogether to avoid confusion.

Thanks again.

**Comment by lipefl** [comment]
I'll have to check about this, I'll need to make some changes since swade system now handles status icons.
