### ISSUE TITLE
Benny rerolls when Hard Choices is enabled

### ISSUE THREAD

**Issue by architech99** [lipefl/swade-tools#103]
In Sunday's game, I think we were running into a problem with Hard Choices being enabled and the SWADE Tools chat card action to reroll using a Benny.

Every time we clicked the Benny icon on the chat card to reroll, unshake, or soak, all we got was the character did not have any bennies. But we could go to the character sheet, spend the Benny, and it would spend it for the player and give one to the GM pool.

Does SWADE Tools not interact with the Hard Choices setting rules?

**Comment by lipefl** [comment]
Yes, they dont interact yet. There's an option for Hard Choices in SWADE Tools also. It might work if you check both. This is a new setting for swade system 1.0 and SWADE Tools is not fully compatible with this system version yet. I'll leave this open as a reminder to fix this.

**Comment by lipefl** [comment]
Fixed in v1.8. Removed from SWADE Tools. Now it'll follow the setting from the system.

**Comment by architech99** [comment]
That was fast! Thank you!
