### ISSUE TITLE
Problem with unlinked token

### ISSUE THREAD

**Issue by Lifthraser** [lipefl/swade-tools#104]
in a fight with unlinked tokens, swade tools is unable to apply statuses (shaken from damage rolls or vulnerable from wild attack)
For info there was just swade system 1.03 update simultaneous to swade tools update 1.8 and it did correct bugs with statuses and unlinked token...

**Comment by Arnok13** [comment]
i have seen the same behavior last night.

**Comment by lipefl** [comment]
Fixed in v1.8.1
Thanks!
