### ISSUE TITLE
Handling of Called Shots

### ISSUE THREAD

**Issue by Lifthraser** [lipefl/swade-tools#106]
This is an enhancement request, not a bug report.

Trying to use called shots with swade tools is proving complex, You have to remove some armor, check if the weapon has an AP and if so is there enought armor in the target to apply or do we need to remove some dmg to take account of the AP that swade tool will apply anyway while it should not...

Maybe a "called shot" button that makes a popup and ask for the aimed point armor value?

Thank you for SWADE TOOLS.

**Comment by lipefl** [comment]
Added an option to show a select box for Called Shots (must be enabled in swade tools config)

**Comment by Lifthraser** [comment]
Incredible option! works even better than what i imaged, thank you so much.
