### ISSUE TITLE
Is there any way to modify a roll after it is made?

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#109]
I love the way Swade Tools handles rolls. The only thing missing for me is the ability to edit a roll after it is made. Sometimes, you realize after the roll that a modifier wasn't added (i.e. player forgot that they ran, flanking bonus didn't apply, etc) and you want to edit it to get the new total so you can auto apply the damage from the card.

Better Rolls 2 for SWADE has this and it's a life saver, but I very much prefer the way Swade Tools handles a lot of the other automation. I'm just wondering if this is something that can be done, or if I'm just missing something that is already there.

Thanks.

**Comment by lipefl** [comment]
Yes, that's something i've been planning to add.

**Comment by gravagehulk** [comment]
> Yes, that's something i've been planning to add.

Awesome! I'm looking forward to it. Thank you.

**Comment by lipefl** [comment]
There's some new buttons for GM in v1.8.5, including adding a modifier after the roll is made :)

**Comment by gravagehulk** [comment]
That's great news! Thank you.
