### ISSUE TITLE
Roll dialog: Add indication what type of action a button represents

### ISSUE THREAD

**Issue by eXaminator** [lipefl/swade-tools#11]
The two default buttons say "Shooting" (or Fighting etc.) while the damage button say "Damage". In addition, there is another button for each extra Action. These extra actions can be of type "damage" or "skill".

Some weapons (like the official SWADE "Streetsweeper Shotgun") have two actions with the same name but different type (in this example we have "Slug" twice, once as damage and once as skill action). Right now both buttons look the same / have the same label.

![image](https://user-images.githubusercontent.com/2758908/103541357-9b758600-4e9b-11eb-8b4a-9eb44c72f401.png)

I have 2 possible ideas for this:
1. Add the type to the button label (for example: "Shooting: Slug" or "Slug (Shooting)") or add an appropriate icon instead
2. Like the default buttons, display the additional actions in two columns, one for skills and one for damage.

**Comment by lipefl** [comment]
Maybe an icon would solve this... ? 
But it's probably a thing to solve in the official swade module, this actions should have different names (the same would occur in the chat functionality)

**Comment by eXaminator** [comment]
I agree that it is not optimal that both actions have the same name in the official package.

**BUT**: I still think it would be good to know what kind of roll to expect from each button, independent of how what it was named. Even the range based rolls in my example could be easily mistaken for skill rolls, but they are in fact damage rolls.

**Comment by lipefl** [comment]
Yes, in the chat, they show an icon to differentiate. I think it'll solve the problem.
