### ISSUE TITLE
Range calculation seems to be off

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#116]
I don't know if this is SWADE Tools or the SWADE core system. As you can see in the screenshot below, the range calculation seems to calculate to the BACK of large tokens, not the front. I have tested this on several large tokens and a few huge. On the huge tokens, it adds a couple extra squares because it calculates to the rear of those tokens as well. For what it's worth, Better Rolls 2 seems to have this issue as well, though it calculates a different (lesser) range. The range of the pistol is 5 (first range increment).

<img width="757" alt="SWADE tools range" src="https://user-images.githubusercontent.com/69117052/157885672-3758bbb9-0b91-4a67-a75f-3d45d67fa4b9.png">

**Comment by lipefl** [comment]
I made some tests, the range is between the center of both tokens. The thing is, for a big token, it measures from the top left as if the token was 1x1 (you can re-size the token to see it, the range will be the same). I'll fix it to take the size of the token into account.
But, i'm questioning myself about something you said. Range should be calculated between two tokens (not taking themselves into account, from the center). Like in the screenshot, it's it distance 1 or 2? I think it's 1 (Reach 1 would be in range), but the calculation shows 2 (from the center of one token to another). I'll research about it and probably fix it too. But if you have any considerations, it'll be appreciated.

![image](https://user-images.githubusercontent.com/10639148/157891967-c8891374-6072-4d7c-aecd-c4d395d16bb5.png)

**Comment by gravagehulk** [comment]
Since we're counting squares, I believe ranged weapons are supposed to count to the front of the square the token is occupying. I've been running my SWADE games in Fantasy Grounds lately and the same tokens at the same range calculate correctly (within 5). That's not to say that the Fantasy Grounds implementation is the authority, but if I were playing in person and the tokens were within 5 squares of each other, I wouldn't count the giant as "out of range" and apply a penalty and I see nothing in the core book (or Pathfinder SWADE) that suggests otherwise. Though range and grid combat seem to be secondary in SWADE.

As for you question: it's two squares. I had the same crisis, believe me. But when you cast a cone spell or a line or anything else, it always starts from the FRONT of your token, not from within your token. The first square is the first 5 feet. If those two tokens in your screenshot were 1 square apart, they would be within melee range. Only a reach of 2" would allow red to hit purpose and vice versa.

**Comment by lipefl** [comment]
I removed the squares to be more clear (i dont use it in my games, i just left it the screenshot for clarity). As you said, if I take the range from the front of one token to the front of another... It'll be 1. I'm confused by your answer. For a melee it should be range 0 (or less than 1), right?

About the giant tokens, it's definitely an error.

![image](https://user-images.githubusercontent.com/10639148/157895320-ef13d204-2760-4a61-9d00-8ea4dc0c13ff.png)

**Comment by gravagehulk** [comment]
> I removed the squares to be more clear (i dont use it in my games, i just left it the screenshot for clarity). As you said, if I take the range from the front of one token to the front of another... It'll be 1. I'm confused by your answer. For a melee it should be range 0 (or less than 1), right?
> 
> About the giant tokens, it's definitely an error.
> 
> ![image](https://user-images.githubusercontent.com/10639148/157895320-ef13d204-2760-4a61-9d00-8ea4dc0c13ff.png)

Now I'm confused. I'm thinking in terms of 5e where someone is 5 feet away from you when they are right next to you (meaning the distance is relative). I would assume it's the same for SWADE.

**Comment by gravagehulk** [comment]
Here's another screenshot demonstrating the issue. The token is huge. The leading edge is in the 4th square (within the 5 square range of the pistol) and even the second square the giant occupies is within 5. So, it seems to be calculating against the furthest square the token occupies:

<img width="826" alt="Screen Shot 2022-03-11 at 9 50 43 AM" src="https://user-images.githubusercontent.com/69117052/157901622-18d4faab-f666-4407-9401-76a5e17ee2b5.png">

**Comment by lipefl** [comment]
Fixed in v1.8.10. 
I decided to keep the same scheme about distance (from the center of the square in the edge of the token) because that's how grid uses it, FG does it and how most people play. I also added a non-grid measure, based on the actual scene config, more in line with Savage non-grid rules, wich sometimes gives a completely different distance (grid ignores diagonal).

**Comment by gravagehulk** [comment]
Just tested and it seems to be working great. Thank you for the fast fix and all of your hard work on this module.
