### ISSUE TITLE
Bennies, Raise calculator and GM Bonuses buttons sometimes doesn't appear in the chat

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#118]
Hi,

sometimes (when all the players make simultaneous rolls perhaps ?) the buttons in the chat does not appear. 
![image](https://user-images.githubusercontent.com/4520046/158015647-d95ca75e-8c8a-4d3d-98a4-d4d9159f0278.png)

 nothing in the console on errors related.

strange. When i am alone i never reproduce it, just when the players are rolling (not always on the same player or rolls).

**Comment by lipefl** [comment]
Unfortunately i need to be able to reproduce the problem to fix it. 
I made some tests and everything seems fine. I'll need more information.

**Comment by Arnok13** [comment]
when i am alone with electron it works perfecly. Only happens with several players with web browser.

i will try to reproduce with fake players.

**Comment by Arnok13** [comment]
just reproduce it one time this night : 
![image](https://user-images.githubusercontent.com/4520046/160019741-9a9d40f7-d9f0-49f3-8d20-3154e957fca9.png)

**Comment by lipefl** [comment]
Have you tried use "Simple Trait Roll" option? This way, all rolls come from SWADE Tools. Maybe this roll is coming from swade system and not being "avaliated" as as skill roll by SWADE Tools. It could be other modules too, interfering with the roll. The real strange thing is that it only happens sometimes and without any errors, wich makes it impossible to me to decipher.
