### ISSUE TITLE
Permission Error with GM rolls and actor import

### ISSUE THREAD

**Issue by humsi** [lipefl/swade-tools#121]
Hallo there,

thank you for your amazing work. One of the best „core“ modules for SWADE, at least in my opinion.
Really don’t want to play without it anymore.

But I’ve some issues. They can be reproduced on Forge-VTT and on a local self-hosted instances of Foundry VTT.

- Foundry:
  - Version 9 Build 255 (Stable)
- Core:
  - Savage Worlds Adventure Edition 1.0.5
- Modules:
  - Compendium Folders 2.4.3
  - libWrapper 1.12.4.0
  - Savage Worlds Adventure Edition Core Rules 1.0.7
  - SWADE Tools 1.8.12

**First error: Importing actor from compendium
Steps to reproduce:**

1. Create a new empty world
2. Install core and above-mentioned modules
3. Create one additional test user and join the game
4. As GM Import an actor from compendium (i.e. SWADE Bestiary - Dragon)
5. Player gets error message „Player 2 lacks permission to update Actor“

![grafik](https://user-images.githubusercontent.com/83549920/159699848-7f0e2479-c22f-4119-a7bf-59b10dfef310.png)
![grafik](https://user-images.githubusercontent.com/83549920/159699864-73ee7e73-1128-451a-91ad-79607c457b86.png)

Player console log:
`` Uncaught (in promise) Error: User Player2 lacks permission to update Actor [qxsx7oSIT2cDISMK] [No packages detected]
[foundry.js:2253:46](http://localhost:3000/scripts/foundry.js)
    update document.mjs:458
    AsyncFunctionThrow self-hosted:704
    (Async: async)
    <anonym> start.js:147
    _call foundry.js:294
    callAll foundry.js:253
    callback foundry.js:10095
    callback self-hosted:1287
    documents foundry.js:10033
    map self-hosted:224
    _handleCreateDocuments foundry.js:10033
    activateSocketListeners foundry.js:9868
    emit index.js:143
    value socket.js:276
    value socket.js:263
    value socket.js:231
    value self-hosted:1183
    emit index.js:143
    value manager.js:200
    value self-hosted:1183
    emit index.js:143
    value index.js:105
    value manager.js:192
    value self-hosted:1183
    emit index.js:143
    value socket.js:323
    value self-hosted:1183
    emit index.js:143
    value transport.js:99
    value transport.js:92
    onmessage websocket.js:76
    (Async: EventHandlerNonNull)
    value websocket.js:75
    value websocket.js:61
    value transport.js:44
    value socket.js:159
    a socket.js:100
    value manager.js:108
    s manager.js:39
    xt index.js:29
    connect foundry.js:5295
    connect foundry.js:5294
    create foundry.js:5281
    <anonym> foundry.js:62610
    (Async: EventListener.handleEvent)
    <anonym> foundry.js:62593
``

**Second error: GM roll npc weapon
Steps to reproduce:**

1. All steps above
2. Create new scene and place the player and npc tokens in the scene
3. As GM mark/target the player token with the imported actor (i.e. Dragon) and make a weapon roll for “Fighting” (i.e. „Bite/Claws“ from the Dragons character sheet).
4. Player gets error message „Player 2 lacks permission to update chatMessage“
5. Reroll as GM without targeting the player token
6. No permission error is shown
![grafik](https://user-images.githubusercontent.com/83549920/159699940-019fd27e-2573-47fa-86f3-9ebd1720f72f.png)
![grafik](https://user-images.githubusercontent.com/83549920/159699952-7d64aea6-01ee-4d89-b709-5fd89faf7573.png)
![grafik](https://user-images.githubusercontent.com/83549920/159699967-094c9b9c-ca30-46a8-b8a6-35d81e706976.png)

``
Uncaught (in promise) Error: User Player2 lacks permission to update ChatMessage [PPZt8D9Cy61ts7Wd] [No packages detected]
[foundry.js:2253:46](http://localhost:3000/scripts/foundry.js)
    findTargets RollControl.js:642
    AsyncFunctionThrow self-hosted:704
    (Async: async)
    doActions RollControl.js:282
    <anonym> start.js:226
    _call foundry.js:294
    call foundry.js:279
    getHTML foundry.js:15269
    InterpretGeneratorResume self-hosted:1490
    AsyncFunctionNext self-hosted:700
    (Async: async)
    postOne foundry.js:57804
    _onCreate foundry.js:15318
    callback foundry.js:10083
    callback self-hosted:1287
    documents foundry.js:10033
    map self-hosted:224
    _handleCreateDocuments foundry.js:10033
    activateSocketListeners foundry.js:9868
    emit index.js:143
    value socket.js:276
    value socket.js:263
    value socket.js:231
    value self-hosted:1183
    emit index.js:143
    value manager.js:200
    value self-hosted:1183
    emit index.js:143
    value index.js:105
    value manager.js:192
    value self-hosted:1183
    emit index.js:143
    value socket.js:323
    value self-hosted:1183
    emit index.js:143
    value transport.js:99
    value transport.js:92
    onmessage websocket.js:76
    (Async: EventHandlerNonNull)
    value websocket.js:75
    value websocket.js:61
    value transport.js:44
    value socket.js:159
    a socket.js:100
    value manager.js:108
    s manager.js:39
    xt index.js:29
    connect foundry.js:5295
    connect foundry.js:5294
    create foundry.js:5281
    <anonym> foundry.js:62610
    (Async: EventListener.handleEvent)
    <anonym> foundry.js:62593
``

**Setting the players permission role to „Assistant GM“ fixes these issues. Which is not really practical for obvious reasons.**

I hope this is not a configuration issue on my side, but I run my tests in a clear world and only the above-mentioned modules.
Are there specific permissions for SWADE tools that players must have that I don't know about?

**Comment by lipefl** [comment]
Fixed in v1.8.13
This was something i saw when running games, but i wasn't sure it was coming from SWADE Tools. It doesn't interfere with any funcionality, but it was really annoying. Thanks!
