### ISSUE TITLE
Vehicle Weapons

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#122]
Does Swade Tools treat vehicle weapons differently? I've been playing round with Rifts, which has a lot of vehicles and robots and power armor. When you put a pilot in the seat of a Robot and add vehicle weapons, the attacks don't seem to resolve against targets like regular weapons do. Attacking a non-vehicle results in a roll, but not a "result" and no option to roll damage. The only way I could get it to kind of work was to manually create a weapon on the pilot that simulates the stats of the vehicle.

**Comment by lipefl** [comment]
Vehicle weapons are treated the same way. It's probably a bug. I tested here (a vehicle targeting another token) and everything is fine. Do you see any errors on console log when rolling?

**Comment by gravagehulk** [comment]
It looks like there are console errors. Here's an example of a UAR-1 Enforcer Bot (vehicle) attacking a dragon hatchling. The roll is made, but it doesn't provide a result with a damage card and then there are all the console errors.

![image](https://user-images.githubusercontent.com/69117052/160290567-65d44b71-07d7-4f03-9030-8efc0e4f6375.png)

**Comment by lipefl** [comment]
I made a little fix that might solve the problem. Please, update to v1.8.14 and test again.
But it seems it's something about the weapon's range. Can you send me the json of the weapon? Just for me to check if there's another problem.

How to get the json of the weapon:
1 - Drag it to the items bar
2 - Right Click and Export Data
3 - It'll generate a json file.

**Comment by gravagehulk** [comment]
Still not working on 1.8.14. Attached screenshot with console errors. Tried two different vehicle weapons. Also attached requested json of railgun.
[fvtt-Item-heavy-rail-gun.json.zip](https://github.com/lipefl/swade-tools/files/8358387/fvt
<img width="1351" alt="Screen Shot 2022-03-27 at 3 11 08 PM" src="https://user-images.githubusercontent.com/69117052/160299086-81011134-e4c8-4e83-af33-c4e7a1961a66.png">
t-Item-heavy-rail-gun.json.zip)

**Comment by lipefl** [comment]
Fixed now in v1.8.15. Thanks for all the info.
It was a little more tricky than i thought.

**Comment by gravagehulk** [comment]
Oh, awesome. I’ll test it out. Thanks!

**Comment by gravagehulk** [comment]
It seems to be working! Thanks so much for this. It will make Rifts infinitely more playable.
