### ISSUE TITLE
It doesn't work for me with the new version. SWADE System Update v1.0.7

### ISSUE THREAD

**Issue by mk1lolo** [lipefl/swade-tools#123]
It doesn't work and it doesn't appear in the module settings.
![image](https://user-images.githubusercontent.com/44495368/160377118-99a3bde8-3cc5-42e5-bf74-dac6ac59de21.png)

**Comment by lipefl** [comment]
Fixed in v1.8.16. 
Sorry, i accidentaly put some code where it shouldn't be in the last update.
Thanks for the heads up.
