### ISSUE TITLE
Improvement : vehicle variable type

### ISSUE THREAD

**Issue by SpaceCal** [lipefl/swade-tools#127]
Could it be possible to change the vehicle's variables "topspeed", "crew" and "passengers" from text to integer ? So it would be possible to use objects to add or remove values from it.

**Comment by lipefl** [comment]
Sorry, i can't help. This is something from swade system. You should open your issue there.

**Comment by lipefl** [comment]
Sorry, i can't help. This is something from swade system. You should open your issue there.
