### ISSUE TITLE
Normalize hooks call

### ISSUE THREAD

**Issue by EternalRider** [lipefl/swade-tools#129]
this is the swade system hooks:
`swadeAction(actor, item, action, roll, userId)`

but this mod call the hooks is :
`Hooks.call('swadeAction', this.actor, this.item);`

it will cause :
`[SwadeActor, SwadeItem, undefined, undefined, undefined]`

**Comment by lipefl** [comment]
I'm not sure what do you mean. It's probably something from swade system.

**Comment by lipefl** [comment]
This is just for compatibilty with some modules. Is this causing any problem?
