### ISSUE TITLE
AP handle

### ISSUE THREAD

**Issue by EternalRider** [lipefl/swade-tools#130]
![image](https://user-images.githubusercontent.com/46736326/165802098-81bc72d6-080b-4f13-8d4b-d32f64219988.png)

AP should be hanle as offset amror, and result is at least 0.
it should not be synonymous with damage.

**Comment by lipefl** [comment]
I'll check it.

**Comment by lipefl** [comment]
It was a problem with armor detection. Fixed in v1.9.3
