### ISSUE TITLE
Wound Cap is no effective

### ISSUE THREAD

**Issue by EternalRider** [lipefl/swade-tools#131]
![image](https://user-images.githubusercontent.com/46736326/165803935-ecdc8a9a-cfba-4b02-ad56-2f0194829c3d.png)

there is active wound cap, but it still give 4 wound as result.

**Comment by lipefl** [comment]
The result is not based or limited by wound cap.

**Comment by lipefl** [comment]
I checked in the code and in the rules. The wound cap limit is 4. 
"Characters can never suffer more than four Wounds in a single hit"
