### ISSUE TITLE
Add GM Modifier changes keep highest die roll to aggregate total when applied.

### ISSUE THREAD

**Issue by architech99** [lipefl/swade-tools#132]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

- Foundry VTT Version: 9.269
- Operating System: Linux (Ubuntu)
- How Are You Using Foundry: Native Application (Electron)
- Modules Enabled?: yes

![My Active Modules](https://user-images.githubusercontent.com/1461748/166115920-9bde1576-ef5a-4b13-bb01-27b715c7e63c.png)

### Issue Description

After rolling the dice, I receive the expected results in the chat card. After clicking the Add GM Modifier action in the card, setting a modifier (i.e. -1), and clicking "Add GM Modifier" to commit it, The card removes the initial individual die roll results and aggregates the total instead.

### Relevant logs and/or screenshots

![1: Original Roll Dialog](https://user-images.githubusercontent.com/1461748/166115931-8cdb6978-a777-4a01-abd4-f0fddca63674.png)

![2: Initial Chat Card Result](https://user-images.githubusercontent.com/1461748/166115930-4555c789-b029-439d-bcac-e12983919ff5.png)

![3: Click Add GM Modifier](https://user-images.githubusercontent.com/1461748/166115929-08184c7b-c589-405e-97d8-db220bc0be0a.png)

![4: Chat Card after applying modifier](https://user-images.githubusercontent.com/1461748/166115928-4a9cbcbf-7e17-462b-9025-bef2e2a1c2ba.png)

### Possible Solution and/or Root Cause

I would expect it to keep the original formula and apply the modifier to the individual die results.

**Comment by lipefl** [comment]
Fixed in v1.9.4. Thanks!
