### ISSUE TITLE
Armor piercing adding to damage even with no armor

### ISSUE THREAD

**Issue by piedoomexplode** [lipefl/swade-tools#133]
![Deadlands • Foundry Virtual Tabletop 4_30_2022 11_34_54 AM_LI](https://user-images.githubusercontent.com/22184579/166117358-318e5ee5-78f0-40e9-977e-f70d6e13c380.jpg)

I uploaded the picture to detail what is going on. The example shows a roll of 5 with an AP 2 weapon scoring a shaken result on a monster with a toughness of 6 that has no armor. The AP should simply ignore armor and in this instance, there should be no shaken result as the monster has no armor. Thank you for your time.

**Comment by lipefl** [comment]
This was fixed in the last update. Please update your module.
I'll close this issue, feel free to reopen if the problem persists
