### ISSUE TITLE
Automatic remove status (at least shaken) does not work any more

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#135]
Hi, 
yesterday night, the shaken auto-roll for remove the status doesn't work anymore (PC and NPC).
![image](https://user-images.githubusercontent.com/4520046/167246343-b8a20f43-9f14-412b-81c1-a460dca43898.png)
and the option (not to remove the auto roll is on "no")
![image](https://user-images.githubusercontent.com/4520046/167246400-14e5c698-9266-4989-a314-c8ddfd038dab.png)

**Comment by sladecraven** [comment]
Tested during a game on 07 May 2022, and it was working perfectly.

**Comment by lipefl** [comment]
I don't see the problem either. Did you refresh foundry after changing the option?

**Comment by lipefl** [comment]
You can try these alternatives: 
- Change the option for automatic rolls to "Yes", reset. Change back to "No", reset. And test.
- Disable all other modules, except SWADE Tools. And test.

For information, i'm using 
Foundry 9.269
Swade System 1.0.10
Swade Tools 1.9.5

**Comment by Arnok13** [comment]
yeah, that's work !
can be closed.
