### ISSUE TITLE
two wild attacks on two rounds and no more vulnerable status

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#141]
Hi,

when a character make the first wild attack the vulnerable status is automatically setted.
When the second wild attack is done, the caracter is still vulnerable, but at the end of its turn, the vulnerable status disapear (may be due to the automatic removal status mechanism).

Is it possible to fix it ?

**Comment by lipefl** [comment]
I tested and it works correctly here, most of the time. Inconsistently it seems to be something related to swade system initiative not working correctly all the time. I'll open an issue in swade system to investigate.

**Comment by Arnok13** [comment]
https://user-images.githubusercontent.com/4520046/168123611-0c399c51-2aea-4dd0-b3e0-a47a4a1f7987.mp4

i reproduce it quite easily (every combat turn).

**Comment by lipefl** [comment]
It's something to do with the start of round, if you put only two actors, it'll happen more often. In your video, you can see it doesn't happen all the time.

**Comment by lipefl** [comment]
Here's the issue in swade system that's causing the problem.
https://gitlab.com/peginc/swade/-/issues/508

**Comment by Arnok13** [comment]
i'm not really sure. It looks like more an issue with the auto removal of status in the core system (not the initiative order). if you set Vunerable status before the auto removal, even if you set it, it will be removed.
That's the cas in 80% of the case (don't understand why sometimes the bug didn't happen).

https://user-images.githubusercontent.com/4520046/168166502-82e36100-6c3e-4885-bcaf-95840550103e.mp4

hope it helps. 

I will no more bother you with this subject ;)

**Comment by lipefl** [comment]
I made some more tests, the errors might not be directly related... so i'll reopen here to investigate further.

**Comment by lipefl** [comment]
I finally found the problem. Fixed in v1.9.8
Sorry for the delay, this was really hard to find. 
Thanks :)

**Comment by Arnok13** [comment]
thanks to you ! you are the best ;)
