### ISSUE TITLE
Updating Italian Translation

### ISSUE THREAD

**Issue by smoothingplane** [lipefl/swade-tools#142]
{
    "SWADETOOLS.ActDmgHint": "Danni da tirare quando si fa clic su Colpito/Incremento",
    "SWADETOOLS.Additional": "Aggiuntivi",
    "SWADETOOLS.AlreadyConvic": "Questo personaggio ha già l'Ispirazione attiva",
    "SWADETOOLS.ApplyDamage": "Applica Danno",
    "SWADETOOLS.AsGM": "come Gamemaster",
    "SWADETOOLS.AutoDisableWarn": "Se selezionato, Swade Tools non abiliterà automaticamente le seguenti impostazioni di sistema SWADE all'avvio: ",
    "SWADETOOLS.AutoInitWarn": "Questa opzione è attiva di default utilizzando SWADE Tools, ma è stata disabilitata nelle Impostazioni di Sistema per evitare conflitti",
    "SWADETOOLS.Bennies": "Benny",
    "SWADETOOLS.Benny": "Benny",
    "SWADETOOLS.BlockSetting": "Bloccare",
"SWADETOOLS.BoostLowerHint": "Usa numeri negativi per Riduci Tratto",
    "SWADETOOLS.BoostMark": "Incremento",
    "SWADETOOLS.BoostSkill": "verrà aggiunto con un indicatore [Boost] per",    
"SWADETOOLS.bullets": "colpi",
    "SWADETOOLS.CalledShot": "Colpi Mirati",
    "SWADETOOLS.CalledShotHint": "Le penalità vengono aggiunte automaticamente, aggiungi modificatori extra manualmente. I colpi alla testa infliggono +4 danni.",
    "SWADETOOLS.CombatReflexesSetting": "Riflessi in Combattimento",
    "SWADETOOLS.ConfigDisabled": "la configurazione è stata disabilitata per evitare conflitti con Swade Tools",
    "SWADETOOLS.ConfigEnabled": "la configurazione è stata abilitata automaticamente da Swade Tools",
    "SWADETOOLS.ConstructSetting": "Costrutto",
    "SWADETOOLS.ConvEnd": "L'ispirazione sta finendo. Potresti spendere un Benny per tenerla fino al prossimo round.",
    "SWADETOOLS.ConvictionKept": "L'Ispirazione è stata estesa al turno successivo!",
    "SWADETOOLS.ConvKepp": "Spendi un Benny per l'Ispirazione",
    "SWADETOOLS.CriticalFailure": "Fallimento Critico!",
    "SWADETOOLS.Customization": "Personalizzazione",
    "SWADETOOLS.Damage": "Danno",
    "SWADETOOLS.Default": "Default",
    "SWADETOOLS.DeleteManually": "Cancella Manualmente",
    "SWADETOOLS.DieSteps": "Differenza di Dado",
    "SWADETOOLS.Disabled": "Disabilitato",
    "SWADETOOLS.DodgeSetting": "Schivare",
    "SWADETOOLS.DoSoak": "prova ad Assorbire il Danno",
    "SWADETOOLS.DumbLuckSetting": "Fortuna Cieca",
    "SWADETOOLS.DurationHint": "Lascialo vuoto per nessuna durata",
    "SWADETOOLS.EditBtn": "Aggiungi Modificatore GM",
    "SWADETOOLS.ElanSetting": "Impeto",
    "SWADETOOLS.ExtraPP": "PP Extra",
    "SWADETOOLS.Extreme": "Gittata Estrema",
    "SWADETOOLS.FailedPP": "Attivazione Potere Fallita (1 PP Speso)",
"SWADETOOLS.Failure": "Fallimento",
    "SWADETOOLS.Fighting": "Combattere",
    "SWADETOOLS.FightingWarn": "è stato modificato da Combattere, in base alle tue impostazioni di Swade Tools, in:",
    "SWADETOOLS.FormationFighterSetting": "Formation Fighter",
    "SWADETOOLS.FrenzySetting": "Frenesia",
    "SWADETOOLS.FriendlyPCMacroOk": "Tutti i PG sono amichevoli e gli NPC ostili!",
    "SWADETOOLS.FriendlyPCMacroQuestion": "Questo contrassegnerà tutti i personaggi attuali (PG) in amichevoli e i PNG come ostili nella configurazione del token. Procedere?",
    "SWADETOOLS.gangUpBonus": "Bonus Tutti Assieme",
    "SWADETOOLS.GMMod": "Mod. GM",
    "SWADETOOLS.GrittyDamage": "Danni Realistici",
    "SWADETOOLS.GrittyDamageHint": "Scegli una tabella per tirare per Danni Realistici",
    "SWADETOOLS.HardChoicesSetting": "Decisioni Difficili",
    "SWADETOOLS.HardChoicesWarn": "Quando usi Decisioni Difficili, i Benny dei PNG Protagonisti saranno ignorati. Vuoi, inoltre, disabilitare Jolly Impazziti e impostare i Benny Iniziali del GM a zero? Questa impostazione è di default per Decisioni Difficili.",
    "SWADETOOLS.HardySetting": "Coriaceo",
    "SWADETOOLS.HardyWarn": " essendo Coriaceo, un secondo risultato di Scosso non causa una Ferita",
    "SWADETOOLS.Have": "ha",
    "SWADETOOLS.ImprovedBlockSetting": "Bloccare Migliorato",
    "SWADETOOLS.IronJawSetting": "Incassatore",
    "SWADETOOLS.IsVulnerable": "è Vulnerabile",
    "SWADETOOLS.ItsBound": "è Bloccato, non può effettuare azioni fisiche e può solo provare a liberarsi usando Atletica o Forza-2",
    "SWADETOOLS.ItsEntangled": "è Avviluppato e non può muoversi, ma può solo provare a liberarsi usando Atletica o Forza-2",
    "SWADETOOLS.Joker": "Jolly",
    "SWADETOOLS.JokersWild": "Pesca il Jolly!",
    "SWADETOOLS.JokersWildMsg": "Tutti ricevono un Benny!",
    "SWADETOOLS.LowerSkillIgnored": "verrà ignorato per",
    "SWADETOOLS.ModAttr": "Mod. Attributo",
    "SWADETOOLS.ModHint": "Accetta numeri o dadi (es.: -2 or 1d6)",
    "SWADETOOLS.Modifier": "Mod.",
    "SWADETOOLS.ModItem": "Mod. Oggetti",
    "SWADETOOLS.ModSkill": "Mod. Abilità",
    "SWADETOOLS.No": "No",
    "SWADETOOLS.NoActorFound": "Nessun Personaggio trovato. Seleziona un Token.",
    "SWADETOOLS.NoActorFoundReroll": "Nessun Personaggio è stato trovato per spendere il Benny (o ci sono personaggi con il solito nome), spendi il Benny e ritira manualmente",
    "SWADETOOLS.NoBennies": "non ha Benny",
    "SWADETOOLS.NoDmgActionDefined": "Non ci sono danni definiti nell'azione di questo oggetto. È stato utilizzato il danno di default (se definito).",
    "SWADETOOLS.NoItemEquipped": "Nessun oggetto equipaggiato per il token selezionato",
    "SWADETOOLS.NoMercySetting": "Senza Pietà",
    "SWADETOOLS.NoOperator": "Nessun Operatore in questo Veicolo",
    "SWADETOOLS.NoOperatorSkill": "Nessuna Abilità per Operare trovata in questo Veicolo",
    "SWADETOOLS.NopowerInActor": "Il personaggio controllato non possiede un potere con il nome",
    "SWADETOOLS.NoSkill": "non ha l'abilità",
    "SWADETOOLS.NoskillInActor": "Il personaggio controllato non possiede un abilità con il nome",
    "SWADETOOLS.NoSkillQuestion": "non ha abilità. Vorresti usarne una?",
    "SWADETOOLS.NoTarget": "Nessun bersaglio selezionato.",
    "SWADETOOLS.NotBelowd4": "non può avere un tratto inferiore al d4",
    "SWADETOOLS.NotEnoughPP": "non ha abbastanza Punti Potere",
    "SWADETOOLS.NotEnoughShots": "non ha abbastanza munizioni",
    "SWADETOOLS.NoTokenSelected": "Nessun token selezionato",
    "SWADETOOLS.NotShaken": "Il Personaggio non è più Scosso",
    "SWADETOOLS.NoweaponInActor": "Il personaggio controllato non possiede un oggetto con il nome",
    "SWADETOOLS.OnlyGM": "Solo il GM ha il permesso di farlo",
    "SWADETOOLS.OtherUnskilled": "Altro (Non Competente)",
    "SWADETOOLS.OutOfControlFail": "va Fuori Controllo",
    "SWADETOOLS.OutOfControlRoll": "cerca di evitare di andare Fuori Controllo",
    "SWADETOOLS.OutOfControlSuccess": "evita di andare Fuori Controllo",
    "SWADETOOLS.OutOfControlTable": "Tabella Fuori Controllo",
    "SWADETOOLS.OutOfControlTableHint": "Scegli una tabella per tirare automaticamente quando un veicolo va Fuori Controllo",
    "SWADETOOLS.PermissionActor": "Non hai il permesso di usare questo Personaggio",
    "SWADETOOLS.PPHint": "PP da aggiungere al costo. Può essere negativo.",
    "SWADETOOLS.RaiseCalcBtn": "Calcola Incrementi",
    "SWADETOOLS.RaiseDmg": "Danni Aggiuntivi",
    "SWADETOOLS.Raises": "Incrementi",
    "SWADETOOLS.RangedInMelee": "Arma a Distanza in Mischia: Utilizzare Parata",
    "SWADETOOLS.RapidFireSetting": "Fuoco Rapido",
    "SWADETOOLS.Recharged": "Ricaricato",
    "SWADETOOLS.RechargeQuestion": "Ricaricare?",
    "SWADETOOLS.RemDistr": "non è più Distratto",
    "SWADETOOLS.RemShaken": "non è più Scosso",
    "SWADETOOLS.RemStunnedRaise": "non è più Stordito, ma rimane Vulnerabile fino alla fine del suo turno",
    "SWADETOOLS.RemStunnedSuc": "non è più Stordito, ma rimane Distratto e Vulnerabile",
    "SWADETOOLS.RemVuln": "non è più Vulnerabile",
    "SWADETOOLS.RerollBtn": "Ritira Spendendo un Benny",
    "SWADETOOLS.RetargetBtn": "Usa bersagli del GM",
    "SWADETOOLS.RoFFinalMod": "Modificatore Finale",
    "SWADETOOLS.RollDamage": "Tira il Danno",
    "SWADETOOLS.Rounds": "round",
    "SWADETOOLS.RulesSettings": "Regole di Ambientazione",
    "SWADETOOLS.sayIsShaken": "è Scosso",
    "SWADETOOLS.sayIsStunned": "è Stordito",
    "SWADETOOLS.Scale": "Scala",
    "SWADETOOLS.SeeSituational": "Vedi Modificatori Situazionali",
    "SWADETOOLS.SettingAskCalledShots": "Opzione Colpi Mirati per gli oggetti",
    "SWADETOOLS.SettingAskCalledShotsHint": "Questa opzione mostra una selezione per i colpi mirati quando si utilizzano oggetti d'attacco",
    "SWADETOOLS.settingCustom": "Personalizzazione",
    "SWADETOOLS.settingCustomButton": "Personalizza il modulo",
    "SWADETOOLS.settingCustomHint": "Modifica le opzioni di SWADE Tools predefinite in modo di adattarlo al tuo modo di giocare.",
    "SWADETOOLS.SettingFighting": "Nome Abilità Combattere",
    "SWADETOOLS.SettingFightingHint": "Nome dell'abilità usata per calcolare la Parata e per determinare se il bersaglio sarà colpito basandosi sulla Parata (nella maggior parte dei casi, lascialo com'è).",
    "SWADETOOLS.SettingGangUp": "Calcola Tutti Assieme (crea PG amichevoli e PNG ostili)",
    "SWADETOOLS.SettingGangUpHint": "Usando questa opzione, Tutti Assieme verrà calcolato automaticamente. Nuovi Personaggi (PG) saranno contrassegnati come amici nella configurazione Token e i PNG come ostili (puoi modificarlo in seguito, come in un PNG alleato). Se vuoi riparare tutti i Personaggi attuali, usa la macro: PC Friendly / NPC Hostile",
    "SWADETOOLS.settingName": "Vantaggi, Capacità e Tratti",
    "SWADETOOLS.settingNameButton": "Modifica Nome di Default",
    "SWADETOOLS.settingNameHint": "Modifica il nome di default che influenza i Tiri automaticamente (le abilità sono considerate come strumenti dei Vantaggi). Se stai usando SWADE Core in un linguaggio supportato da SWADE Tools, probabilmente non dovrai cambiare niente qui.",
    "SWADETOOLS.SettingNoAutoRoll": "Disabilita i tiri automatici durante il combattimento",
    "SWADETOOLS.SettingNoAutoRollHint": "Questa opzione disabilita i tiri automatici per rimuovere Stordimento o Scosso durante il combattimento.",
    "SWADETOOLS.SettingreloadX": "Mostra pulsante Ricarica X",
    "SWADETOOLS.SettingreloadXHint": "Mostra un pulsante per ricaricare un numero specifico di proiettili invece della ricarica completa.",
    "SWADETOOLS.settingRules": "Regole di Ambientazione",
    "SWADETOOLS.settingRulesButton": "Scegli le Regole di Ambientazione",
    "SWADETOOLS.settingRulesHint": "Attiva le Regole di Ambientazione che usi per cambiare le impostazione e le automazioni.",
    "SWADETOOLS.SettingsAutoInitStart": "Non tirare automaticamente l'iniziativa all'inizio di un combattimento",
    "SWADETOOLS.SettingsAutoInitStartHint": "(Richiede Ricarica) Disattiva il tiro di iniziativa automatico all'inizio di un combattimento.",
    "SWADETOOLS.SettingsDefaultStatus": "Usa le icone di status di sistema quando disponibili",
    "SWADETOOLS.SettingsDefaultStatusHint": "Attivalo per usare le icone di status di sistema invece che quelle di Swade Tools.",
    "SWADETOOLS.SettingShootingHint": "Abilità da utilizzare per Vantaggi basati su Sparare.",
    "SWADETOOLS.SettingShowSituational": "Mostra sempre i Modificatori Situazionali per il bersaglio",
    "SWADETOOLS.SettingShowSituationalHint": "Con questa opzione selezionata, i modificatori dei bersagli saranno sempre visibili, non è necessario fare clic su (?)",
    "SWADETOOLS.SettingsItemNameClick": "Mostra le info quando clicchi sui nomi delle armi/poteri/abilità",
    "SWADETOOLS.SettingsItemNameClickHint": "Manterrà il funzionamento predefinito al clic sul nome di un potere/arma/abilità (normalmente mostra alcune informazioni), invece di aprire una finestra di dialogo per tirare.",
    "SWADETOOLS.SettingsJokersWild": "Disattiva il Jolly Impazzito",
    "SWADETOOLS.SettingsJokersWildHint": "Questo disattiva la distribuzione automatica dei Benny quando viene pescato un Jolly in combattimento.",
    "SWADETOOLS.SettingsSimpleRolls": "Tiri dei tratti semplificati",
    "SWADETOOLS.SettingsSimpleRollsHint": "Questa opzione semplificherà i tiri dei tratti mostrando solo un campo per un modificatore personalizzato",
    "SWADETOOLS.SettingUsePP": "Traccia Punti Potere",
    "SWADETOOLS.SettingUsePPHint": "Se non vuoi automaticamente tenere traccia dei Punti Potere, disabilita questa opzione.",
    "SWADETOOLS.SettinguseScale": "Usa Scala",
    "SWADETOOLS.SettinguseScaleHint": "Calcola i Modificatori di Scala negli attacchi. Le creature con Schiacciare (abilità speciale) avranno una casella da spuntare nel loro attacco",
    "SWADETOOLS.SettingUseShots": "Traccia Munizioni",
    "SWADETOOLS.SettingUseShotsHint": "Se non vuoi automaticamente tenere traccia delle munizioni utilizzate dalle armi, disabilita questa opzione.",
    "SWADETOOLS.SettingWildAttackSkills": "Abilità utilizzabili con Attacco Selvaggio",
    "SWADETOOLS.SettingWildAttackSkillsHint": "Lista di abilità utilizzabili con Attacco Selvaggio, separate da una virgola. Es: Combattere, Atletica, Sparare",
    "SWADETOOLS.Shooting": "Sparare",
    "SWADETOOLS.ShowDialogCheck": "Mostra finestra (danni e altre azioni)",
    "SWADETOOLS.SituationalRules": "Regole Situazionali",
    "SWADETOOLS.SoakDmg": "Assorbimento Danni",
    "SWADETOOLS.StatusIconsSetting": "Usa Icone di Stato",
    "SWADETOOLS.StatusIconsSettingDefault": "SWADE Tools",
    "SWADETOOLS.StatusIconsSettingHint": "Passare alle icone di stato predefinite dal sistema o disattivare le icone.",
    "SWADETOOLS.StatusIconsSettingNone": "Disattivare",
    "SWADETOOLS.StatusIconsSettingSystem": "SWADE system",
    "SWADETOOLS.StillShaken": "rimane Scosso",
    "SWADETOOLS.StillStunned": "rimane Stordito",
    "SWADETOOLS.Success": "Successo",
    "SWADETOOLS.SwatSetting": "Schiacciare",
    "SWADETOOLS.Targetchoose": "Bersaglio",
    "SWADETOOLS.Targethit": "Colpito",
    "SWADETOOLS.Targetmiss": "Mancato",
    "SWADETOOLS.Targetnone": "Nessun Danno",
    "SWADETOOLS.TargetNumber": "Cambia Numero Chiave",
    "SWADETOOLS.Targetraise": "Incremento",
    "SWADETOOLS.Targetshaken": "Scosso",
    "SWADETOOLS.Targetshakenvehicle": "Fuori Controllo",
    "SWADETOOLS.TargetsTitleDamage": "Bersagli: clicca per applicare il danno (solo GM)",
    "SWADETOOLS.TargetsTitleSkill": "Bersaglio: clicca per tirare il danno",
    "SWADETOOLS.TargetTooFar": "Il Bersaglio è oltre la Gittata Estrema",
    "SWADETOOLS.Targetwound": "Ferita",
    "SWADETOOLS.Targetwounds": "Ferite",
    "SWADETOOLS.TipRoFLower": "Quando usi la CdT, il risultato inferiore viene ignorato.",
    "SWADETOOLS.TipRofRoll": "Per CdT, colpito/incremento sono definiti manualmente",
    "SWADETOOLS.TipTargetNumber": "(N) è il numero chiave per colpire (visibile solo al GM)",
    "SWADETOOLS.TN": "NC",
    "SWADETOOLS.Total": "Totale originale",
    "SWADETOOLS.UnarmoredHeroSetting": "Eroi Senza Armatura",
    "SWADETOOLS.UndeadSetting": "Non Morto",
    "SWADETOOLS.UnShakenAttempt": "prova a riprendersi da Scosso",
    "SWADETOOLS.UnshakenBennyButton": "Riprenditi da Scosso spendendo un Benny",
    "SWADETOOLS.Unskilled": "Senza abilità",
    "SWADETOOLS.UnStunnedAttempt": "prova a riprendersi da Stordito",
    "SWADETOOLS.UpdateSWADE": "La versione del tuo sistema SWADE non è compatibile con il modulo SWADE Tools. Si prega di aggiornare il sistema SWADE.",
    "SWADETOOLS.UseSkillSelected": "Usa Abilità",
    "SWADETOOLS.WildAttack": "Attacco Selvaggio",
    "SWADETOOLS.WoundCapSetting": "Limite alle Ferite",
    "SWADETOOLS.Yes": "Sì",
    "SWADETOOLS.YesButPC": "Sì, ma solo per i PG",
    "SWADETOOLS.YouHave": "Tu Hai"
}

**Comment by lipefl** [comment]
Updated
