### ISSUE TITLE
Implementation of minimum strenght limitation for melee and thrown weapon

### ISSUE THREAD

**Issue by Lifthraser** [lipefl/swade-tools#146]
As page 66 of swade
MELEE/THROWN WEAPONS: A thrown or melee weapon’s damage die is limited by the user’s Strength die. If a scrawny kid (Strength d4) picks up a long sword (Str+d8), he rolls d4 + d4 damage instead of d4 + d8. Also, if the user’s Strength is less than its Minimum Strength, he doesn’t benefit from any of the weapon’s positive abilities such as Reach or Parry bonuses. He still retains any penalties, however.
Could you please try to make that work somtime please?

**Comment by lipefl** [comment]
Implemented in v1.9.8 
Damage die changes, also applies penalty for equipped armor or using ranged weapon, according to the core.

**Comment by Lifthraser** [comment]
I dont see the penalty for pace applied for armor
![image](https://user-images.githubusercontent.com/79018988/173245512-397d310c-787f-4d80-b42c-2667add4e862.png)

**Comment by lipefl** [comment]
I really forgot about Pace. 
I tried to implement it now, but the problem is when i update it, swade system automatically updates it too. Since swade system already auto calculates Pace, this should be asked to be implemented there.
