### ISSUE TITLE
Rate of Fire > 1 summing

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [lipefl/swade-tools#15]
Using a Frenzy action (standard Fighting with RoF 2), against self token (NPC, not sure if matters), a parry.value=10 and parry.modifier=-1 results in hit with results of 7 and 8.

Expected result here is that the two results are evaluated separately, since they are two separate rolled attacks (with one Wild Die if WC).

**Comment by lipefl** [comment]
RoF higher than 1 are not evaluated to hit/raise, because it'll be hard to determine wich dice will go to wich target.
It just shows a "Target" button to let you choose the target and roll damage. It's also missing a "raise" option, by the way. I'll fix it and make rof rolls more clear in the next update.

**Comment by all-the-good-ones-are-gone** [comment]
Yeah, I'd noticed your comment on Discord, so there's no need to bring that up, I suppose.

Something else I've noticed, I suppose should go in its own ticket is that adding modifiers to a roll (for example, clicking on a gun, and in the pop-up) adding an extra die (the gun is special in that it's bonus damage is d10 instead of d6), drops the non-integer from the chat card.

Two other things I was going to throw in as enhancements would be taking Conviction being active into account (rolls do when your module is disabled), and allowing other modifiers to rolls (such as being able to add additional dice or flat bonuses to damage on the chat card).

**Comment by lipefl** [comment]
Accepting dice as modifier will be a nice addition. I'll take a look about how conviction works in the system and add it too. Thanks.

**Comment by all-the-good-ones-are-gone** [comment]
Presently it appears to be inconsistently applied (for example, Attribute rolls are not using it). All Trait and Damage rolls get an extra 1d6x, and there's an open question on the forum to determine at what level it is rolled:https://www.pegforum.com/forum/savage-worlds/official-answers-on-core-rules/45282-conviction-dice-instancing
Once per round, or once per action, or once per trait or damage roll, or once per individual trait/wild die and damage pool levels.
