### ISSUE TITLE
Strength - Minimum Strength Step Adjustment

### ISSUE THREAD

**Issue by aedgaruk** [lipefl/swade-tools#151]
Hi,
SWADE Tools does a great job of managing the Actor Str v's Item minStr but can it go one step further?

e.g. Edge: Soldier : Professional soldiers get used to carrying heavy loads, and enduring harsh conditions. After a few days getting used to their gear (GM’s call), they treat their Strength as one die type higher when determining Encumbrance (page 67) and **Minimum Strength to use armor, weapons, and equipment without a penalty** (page 66). (This stacks with the Brawny Edge.)

Side Note: Encumbrance has data.attributes.strength.encumbranceSteps allowing for independent modification.

Currently I am able to preserve the Strength data.attributes.strength.die.sides value whilst adjusting the encumbrance value using data.attributes.strength.encumbranceSteps.

What I'm requesting is a similar value associated within "Strength" for comparison with any given item's minStr such that it is independent of the strength.die.sides value, e.g. something like data.attributes.strength.minStrSteps

Presumably a change to the internal logic such that it would be this new value (minStrSteps) that is used to compare against an item minStr value rather than, I assume, the current Str die.sides value would also be required?

Essentially, this would mean a single value could be modified for an Actor with the Soldier or Brawny Edge using Active Effects rather than many changes across individual affected Items carried.

Workaround is to lower the Min. Strength Required for every equipped item utilised by a player with this Edge ... laborious/messy.

**Comment by lipefl** [comment]
Hi, thanks for the idea.
Swade Tools already detects some edges, so it won't be a problem checking for these edges during minStr calculations. This way it'll be automatic.
I'll keep this issue here as an enhancement to the module. But i'm not sure i am adding anything new before Foundry v10 because of the re-work.

**Comment by aedgaruk** [comment]
No worries and understood re: waiting on v10, looks to be right round the corner, fingers crossed.

And "Thank You" for the VTT/SWADE modules ... it's appreciated :)

**Comment by Arnok13** [comment]
i think it is related :
my hero with d6 Strength has an armor with min str d8 and soldier edge, but still has the -1 on all Agility related skills.

**Comment by lipefl** [comment]
@Arnok13 yes, the module doesn't detect these edges yet. You can temporarily lower minStr on the item. This will probably be fixed in the next update.

**Comment by lipefl** [comment]
Just to let you know, this is now available in v1.10.1
SWADE Tools now detects the edges and take it into account
