### ISSUE TITLE
SWADE 1.2.3 Item Card property 'Trademark weapon'

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#152]
SWADE core rewampped item cards and now it has option to set weapon as 'trademark weapon' (also Improved vesion) and it autocalculates bonus to attackroll & parry.

Would be awesome if that Attack-roll bonus from 'Trademark...' would carry over to SWADE Tools attack-dialog so we could get rid of modifying weapons stats for those bonuses from the edge. 
Currently it has to be added to weapon stats and if 'Trademark weapon' option is used simultaneously using core popup (from gear tab) adds too big bonus  (yeah my players sometimes get confused and mix those 2 ways to roll)

Tested on 
Foundry 9 (build 269)
SWADE core 1.2.3
SWADE Tools 1.9.10

**Comment by lipefl** [comment]
I think there's a problem with Trademark Weapon in this new version. I tried updating it and it remains "none" after i close/reopen the item window.

Tested with 
Foundry v10.286
Savage Worlds v2.0.3

**Comment by lipefl** [comment]
SWADE system v2.0.4 apparently fixed the problem with trademark weapon. Now SWADE Tools recognize it. Please update to v1.10.4

**Comment by sanpats** [comment]
Can you backport this feature to Foundry-v9-compatible version?

**Comment by lipefl** [comment]
Hi @sanpats, it's not possible, since you can't update SWADE tools while using v9. 
But you can manually change this function in /class/ItemRoll.js
It might work, but i can't say for sure.

addSkillMod(){
        this.addModifier(this.item.data.trademark,gb.trans('TrademarkWeapon.Label','SWADE'))
        this.addModifier(this.data.skillMod,gb.trans('ModItem'));
        
    }
