### ISSUE TITLE
https://foundryvtt.com/packages/swade-tools shows really old info

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#154]
Foundry VTT official modulelist shows obsolete version for SWADE Tools and it looks like the last update is made a year ago.
For uninformed the module looks abandoned...

This is great mod and it should get more attention from players! Please consider updating the infos and thus make module more visible again.

**Comment by lipefl** [comment]
Thanks! I always forget to update it in the foundry website.
It's fixed now.
