### ISSUE TITLE
Attack roll popup not working

### ISSUE THREAD

**Issue by simondw2000** [lipefl/swade-tools#155]
Hi,
The module doesn't seem to be taking over the attack roll process. The standard "in chat" roll messages are coming up and the popup from SWADE Tools is not.

I have tried disabling every module except SWADE Tools and the issue persists.
I am not getting any console errors.

This was working perfectly yesterday and has broken since I updated to Foundry v10 this morning (along with updating the game system and modules).

Versions
Foundry: v10.286
SWADE: v2.0.3
SWADE Tools: 1.10.0

**Comment by simondw2000** [comment]
Just to make sure I'm being clear, I mean this popup...

![68747470733a2f2f692e696d6775722e636f6d2f594731495535572e6a7067](https://user-images.githubusercontent.com/30345746/192994435-750188d1-3a90-4e1a-9820-a01822c4e8f7.jpg)

**Comment by lipefl** [comment]
Fixed in v1.10.1
Thanks!

**Comment by simondw2000** [comment]
Wow, that's for the quick response @lipefl 

Just to make you aware, SWADE Tools seems to have disappeared as an option for "HUD Roll Handler" in Token Action HUD, but I'm sure it was there before the major version update as I've been using both modules together for a while now.

I don't know whether that would be an issue in your module or theirs though.

**Comment by lipefl** [comment]
Token HUD compatibility works automatically and it's done by SWADE Tools. I checked here and only gear wasn't working. Fixed in v1.10.2

**Comment by simondw2000** [comment]
@lipefl you are a legend!! Thanks again. Confirmed working.
