### ISSUE TITLE
Confusion over the Soak button

### ISSUE THREAD

**Issue by steveculshaw** [lipefl/swade-tools#156]
Firstly, thanks for the great module ... it's been a life saver for our playing SWADE in Foundry!

I keep getting the question from players about using the Soak button in the Chat damage ...
![image](https://user-images.githubusercontent.com/64320/193259468-448a4f2e-2cf0-46ce-9860-92156e60bb24.png)

They are always asking which "one" to click, the benny or the crossed through blood drop.

Am I right in saying it's a single button that uses a benny and rolls a soak check?

**Comment by lipefl** [comment]
Yes, it's the same. The blood drop is just to signalize is not a "use benny to reroll" and the benny is there to show that it'll be spent.
