### ISSUE TITLE
wound calculator issue

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#161]
Hi,

it seems to me that the wound calculator doesn't take the Toughness in count.
So if a character take 12 points from damage, it says thar the targer has 3 wounds and is shaken.

ON my sample, the target has a Toughness of 5 so 4 points of damage should be no wound and not shaken

![image](https://user-images.githubusercontent.com/4520046/194116877-183df985-64b5-4a98-bb0e-030287c147a5.png)

**Comment by Arnok13** [comment]
sorry for the french language

**Comment by lipefl** [comment]
i dont see it happening here. I think it might have something to do with "Called Shot" option. Try disabling it to see if it works. 
Anyway, can you export the actor and send me? So i can find the problem with called shot.
No problem for the french language :)

**Comment by lipefl** [comment]
Nevermind, i found it. Fixed in v1.10.6
Thanks!

**Comment by Arnok13** [comment]
thanks it's ok now.
