### ISSUE TITLE
Weapon Range modifier missing?

### ISSUE THREAD

**Issue by aedgaruk** [lipefl/swade-tools#162]
Hi,

I thought SWADE Tools calculated and factored in the Range to target and applied/displayed the modifier based on the weapon range stats? ... since upgrading to v10 it no longer seems to be the case.

I've only just started using SWADE Tools and just now upgraded so apologies if I've mistakenly raised the issue at your door, so to speak.

Anyway, your module really brings some great QoL content to the virtual-table.

Appreciate it, Cheers
Andy

**Comment by lipefl** [comment]
Yes it does calculate range. It was an error. Fixed in v1.10.6
Thanks!

**Comment by aedgaruk** [comment]
Cheers for the prompt response!
