### ISSUE TITLE
Dead character still give gang up bonus to allies.

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#165]
Dead and shaken characters should not contribute to gang up bonus of allies.
![image](https://user-images.githubusercontent.com/22677493/196015169-80a1bc83-2948-42b7-bb81-dacb4ba8e2a3.png)
![image](https://user-images.githubusercontent.com/22677493/196015190-fe374e67-49f1-499b-b6f3-33a1873a5e47.png)

**Comment by sanpats** [comment]
PS. Gobline gave +2 gang up bonus instead of +1 because they have Formation Fighter edge.

**Comment by lipefl** [comment]
As far as i know, Shaken characters do count for gang up (only Stunned do not count), so the example you showed is correct. 
I've tested with defeated token and it's not counting as expected.

**Comment by sanpats** [comment]
You are correct regarding the shaken character do count for gang up, but for defeated token, I have tested further, it's not counted if it's still in the combat tracker. However, if removed from combat track, it's counted.
![image](https://user-images.githubusercontent.com/22677493/196039638-a57c819e-aa03-45d1-aa32-eaa42487ac85.png)
![image](https://user-images.githubusercontent.com/22677493/196039643-506834d0-be77-442e-a7d7-8461247456d7.png)

**Comment by sanpats** [comment]
If still in combat tracker, the module behave correctly.
![image](https://user-images.githubusercontent.com/22677493/196039792-1dbcf012-2590-43ab-8cce-61f62a3d73fa.png)
![image](https://user-images.githubusercontent.com/22677493/196039799-c616093a-40ce-42db-b545-ec7ede47055f.png)

Not so, if remove the incapacitated one from combat.
![image](https://user-images.githubusercontent.com/22677493/196039843-5d94f149-9264-4739-8045-ad8220446acd.png)
![image](https://user-images.githubusercontent.com/22677493/196039855-9f3da921-1aa7-4bdd-9569-57445dd5b0fb.png)

**Comment by lipefl** [comment]
Fixed in v1.10.8
