### ISSUE TITLE
Stun and Bound status won't also show the Distracted status icon.

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#166]
When set a character to be stunned or bound, Only the stunned or bound icon and the vulnerable icon shown, no Distracted icon. The attack card still recognize that the character is distracted though.
![image](https://user-images.githubusercontent.com/22677493/196015289-77cbe6a4-6a6e-4944-a060-17175215e62e.png)

**Comment by sanpats** [comment]
![image](https://user-images.githubusercontent.com/22677493/196015306-bdbf64e0-4edc-4c1c-a1a8-41cef59b2ab4.png)

**Comment by sanpats** [comment]
![image](https://user-images.githubusercontent.com/22677493/196015325-3cc106c3-867c-4645-bbfd-fe1a5c16ec31.png)
![image](https://user-images.githubusercontent.com/22677493/196015327-23c499be-c50b-4f0f-b954-079a4acb38d6.png)

**Comment by lipefl** [comment]
This seem to be a bug only happening with not linked actors (normally extras). I'll verify.

**Comment by sanpats** [comment]
I tested and can confirm. It's a bug only for extras.

**Comment by lipefl** [comment]
Fixed in v1.10.8
