### ISSUE TITLE
Defeated actors still roll for unshaken if still in combat tracker.

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#167]
Defeated actors still roll for unshaken if still in combat tracker.

Zombie is incapacitated/defeated.
![image](https://user-images.githubusercontent.com/22677493/196040531-f028035f-fee3-4fdd-b41d-50663a396db9.png)

Still roll to unshaken.
![image](https://user-images.githubusercontent.com/22677493/196040558-192fbed1-f214-43c5-944f-c7ddeb70a52c.png)
![image](https://user-images.githubusercontent.com/22677493/196040572-94a9af3f-6613-43f2-bffc-fe384c946ed0.png)

**Comment by sanpats** [comment]
Not sure if this is intended.

**Comment by sanpats** [comment]
May be this is correct behavior as character might still recover?

**Comment by lipefl** [comment]
It's not intended, probably a bug. Thanks!

**Comment by sanpats** [comment]
Ah yes, incapacitated character "cannot take actions of any kind", and unshaken is an action, a free action.

**Comment by lipefl** [comment]
Fixed in v1.10.8
