### ISSUE TITLE
Actors that are both Bound and Stunned behave incorrectly

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#168]
Issue 1: Actors that are both Bound and Stunned will show multiple Distracted and Vulnerable icons, but still calculate penalty correctly when attack, defend, etc.
![image](https://user-images.githubusercontent.com/22677493/196061884-eaf33a2e-aef9-472e-9b96-25b76eb9c85d.png)

Issue 2: Actors that are both Bound and Stunned when remove one of these two statuses will remove Distracted and Vulnerable icons entirely, but still calculate penalty correctly when attack, defend, etc.
![image](https://user-images.githubusercontent.com/22677493/196061959-659480b5-8ca9-4368-8f01-91eff36027b2.png)

**Comment by sanpats** [comment]
This happens to both linked and non-linked actors.

**Comment by lipefl** [comment]
This is now handled by SWADE system (from v1.10.9)
