### ISSUE TITLE
Incapacitated actors that are not marked as defeated still roll to unshaken

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#169]
This may be an extremely corner case, but as it behaves incorrectly according to the RAW, I decided to report anyway. Incapacitated actors that are not marked as defeated still roll to unshaken. Incapacitated characters should not be able to take any action, including unshaken which is a free action.

![image](https://user-images.githubusercontent.com/22677493/196062238-d62674b5-e972-4528-b8d8-02bca729c545.png)
![image](https://user-images.githubusercontent.com/22677493/196062257-0d6d56ec-4f0b-4847-b61c-b8dcf8a1d0d9.png)
![image](https://user-images.githubusercontent.com/22677493/196062263-ca212ef9-8bd8-435e-8f6a-e0a9a43c108a.png)

**Comment by sanpats** [comment]
related to #165

**Comment by lipefl** [comment]
The first skull (after the eye) must be marked (white). You must click there. So the icon is grayed out like this image you sent. Otherwise it'll count as an able character.

![image](https://user-images.githubusercontent.com/10639148/196180798-33fdfe34-7c24-4b33-b293-34c22f50e725.png)

**Comment by lipefl** [comment]
Same as #170
