### ISSUE TITLE
SWADE Tools doesn't follow SWADE system setting regarding alternate Entangled status

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#171]
SWADE system gave a setting called "Fantasy Companion Entangle"
![image](https://user-images.githubusercontent.com/22677493/196531983-0132919a-7c30-4f4f-acf4-3e67af4756b8.png)
Which give Vulnerable instead of Distracted when Entangled.
![image](https://user-images.githubusercontent.com/22677493/196532242-9f1f1402-9db4-4503-a73c-db1d5e8254f1.png)
However, when turn SWADE Tools on, Entangled will give both Distracted and Vulnerable.
![image](https://user-images.githubusercontent.com/22677493/196532566-0dbb0402-92f1-4a5e-a2a4-1f1bf6b5cc82.png)

**Comment by lipefl** [comment]
I noticed SWADE system now handles status the same way SWADE Tools does. I'll remove thi

**Comment by lipefl** [comment]
This is now handled by SWADE system and should work fine (from v1.10.9)
