### ISSUE TITLE
Follower in a group in the Combat Tracker will remove Vulnerable status even when using Wild Attack that turn

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#172]
Both Human Zombies are Vulnerable from making Wild Attacks, one is a group leader and another is a follower in an initiative grouping.
![image](https://user-images.githubusercontent.com/22677493/196800239-bd1b398f-7b4f-4f03-a11d-4ea57074bbee.png)

Both make a Wild Attack again that should renew the Vulnerable status so they are not expire this turn.
![image](https://user-images.githubusercontent.com/22677493/196800541-44bc0996-8b35-42c0-9a25-87a0fa4140c6.png)

But the follower zombie still has Vulnerable status removed.
![image](https://user-images.githubusercontent.com/22677493/196800685-15968ea5-5ae5-4a2f-a7da-e4f25afa07e2.png)

If I manually give Vulnerable to both Zombies last turn instead, and both make Wild attacks this turn, both will have Vulnerable removed.

May be it's related to conflict between SWADE system and SWADE Tools both tried to automate statuses that you mentioned last issue?

**Comment by sanpats** [comment]
I tested further even without grouping 2 out of 3 zombies will still removed Vulnerable even if they make Wild Attacks the second time in a roll.
![image](https://user-images.githubusercontent.com/22677493/196806739-fbabcfc9-2c05-4262-a201-fb5d2c71a116.png)

**Comment by lipefl** [comment]
Fixed in v1.10.9
Thanks!
