### ISSUE TITLE
"Show info when clicking weapon/power/skill name" setting is working incorrectly

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#173]
"Show info when clicking weapon/power/skill name" setting suppose to show the description of these items.
![image](https://user-images.githubusercontent.com/22677493/196809404-cf215f8d-3242-4a5d-80b9-262f4e41d297.png)

But instead it still show the roll dialog unlike the SWADE system default.
![image](https://user-images.githubusercontent.com/22677493/196809644-ba749615-62b5-4c53-a32f-0dc26035b7d1.png)

It's instead show info on the Quick Access menu which is the SWADE system roll dialog. I think that is not an intended behavior.
![image](https://user-images.githubusercontent.com/22677493/196809840-f1b26b74-3c14-490e-9fe7-db0e3472a167.png)

**Comment by lipefl** [comment]
Fixed in v1.10.9
