### ISSUE TITLE
Odd weapon damage formula not working.  

### ISSUE THREAD

**Issue by karolusb** [lipefl/swade-tools#174]
I have a 'weapon' whose damage is @spi+1d4 (spiritual weapon from the APG).  

The first issue I had was that it would roll 1d10 for the spirit, which is the original statline, but the character has an item that raises spirit so it should have been rolling a d12.  I cannot replicate this issue because:

Now it just doesn't roll a stat at all.  Replacing spi with sma, agi, str, and vig all work fine.  The roll works in betterrolls, and core.  This has persisted through restarts and the most recent software update.  
![swade_tools_error](https://user-images.githubusercontent.com/54753235/197376652-1dd2fcc5-67d2-4ed1-8f87-974dab312bae.JPG)

**Comment by lipefl** [comment]
It was a typo in SWADE Tools code. Fixed in v1.10.9
Thanks!
