### ISSUE TITLE
Unstoppable

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#177]
Hello,

Is there a way to implement 'Unstoppable' on the card for SWADE Tools?
Pathfinder introduced a mechanic that would limit damage incurred in one attack to 1 Wound in order to keep a boss up amidst the possibility of exploding dice. 

My thought if possible would be to add a button that converts 2+ Wounds [& Shaken] to 1 Wound [& Shaken]. Simple example below [Using the -12 to fake it]:
![Unstoppable_3](https://user-images.githubusercontent.com/116909768/198698405-0d6e630d-5a6c-4e33-892c-f5a6a7eb6adf.png)
There are times in which this is ignored such as an attacker getting a Joker, so I'm not so sure fully automating all conditions would work without a lot of troubleshooting but something simple like a button could put it in the hands of the GM to make the call.

Thanks!

**Comment by lipefl** [comment]
Yes, it can be done even with the joker detection. I'll update here when it's done.

**Comment by lipefl** [comment]
v1.10.10 now recognizes Unstoppable and shows 1 Wound max (except when the attacker has the Joker)
