### ISSUE TITLE
SWADE Tools is using obsolete Power Points pool.

### ISSUE THREAD

**Issue by sanpats** [lipefl/swade-tools#180]
As of SWADE System 2.1.2+, there are breaking changes to the structure of power point pool. Currently SWADE tools is no longer use the power points in the Actor Sheet.

In Actor Sheet, it's 5/10:
![image](https://user-images.githubusercontent.com/22677493/201008083-38ca7f8c-d721-4b4b-bf3c-9d7fbc2b17ae.png)

SWADE Tools is still think it's 3/10:
![image](https://user-images.githubusercontent.com/22677493/201008286-a4e2ed60-522f-4f0b-af24-7121a4eeabb2.png)

**Comment by lipefl** [comment]
Fixed in v1.10.11
Thanks!
