### ISSUE TITLE
Desperate Attack

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#185]
Morning,

Is there a way to add Desperate Attack to the Fighting card/prompt? Savage Pathfinder added the rule in and my players tend to gravitate to it in hard to hit situations like small creatures or well-trained combatants.

DESPERATE ATTACK
Determined to land a blow, the warrior unleashes a frantic attack, focusing on hitting his target at the expense of damage. He adds +2 or +4 to any Fighting roll and subtracts a like amount from damage if he hits. This can be determined per attack (before rolling), and can't be combined with Wild Attack.

Thought I'd ask because we use a toggle effect but if it could be an option much like Wild Attack is, it'd be great.

Thanks again for this great mod!

**Comment by lipefl** [comment]
Available in v1.10.12
You have to enable it in Settings to show.

**Comment by Neurochimp** [comment]
Thank You!
