### ISSUE TITLE
MDC Weapons and Armor for Rifts automation

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#186]
I was able to get the SWADE developer to add fields in the weapons and armor traits to account for mega damage. This is just a variation of Heavy Weapons and Heavy Armor. 

Is there any way we could get some automation added that checks to see if the weapon damage is MDC when attacking MDC armor? Non-MDC weapons should not do any damage to MDC armor.

<img width="397" alt="Screen Shot 2022-11-22 at 14 10 38 PM" src="https://user-images.githubusercontent.com/69117052/203412606-37499af7-ab0f-4ed1-87f4-f38f8a1f98a0.png">

<img width="392" alt="Screen Shot 2022-11-22 at 14 10 20 PM" src="https://user-images.githubusercontent.com/69117052/203412622-0b03a788-3035-4e4b-a2a2-6c007647d3d9.png">

**Comment by lipefl** [comment]
I think so. Does it work like Heavy Armor/Heavy Weapon?

**Comment by gravagehulk** [comment]
> I think so. Does it work like Heavy Armor/Heavy Weapon?

Yes! Exactly like that.

**Comment by lipefl** [comment]
Available in v1.10.12

**Comment by gravagehulk** [comment]
Tested and it seems to work great. Thank you!
