### ISSUE TITLE
Run Die Request

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#187]
Hello again,

Hoping this might be simple. Can rolling the Run die get the same rather simple dialog box that trait rolls get? I prefer the simplicity that SWADE Tools provides on most rolls except where needed in combat.
![run_box](https://user-images.githubusercontent.com/116909768/203550642-16801f31-4e05-4b7f-aa55-c4e0dfe8cec7.png)

**Comment by lipefl** [comment]
Available in v1.10.12

**Comment by Neurochimp** [comment]
This works off the character sheet but not the HUD. That still only responds to a right click. Should I escalate this here or there?

**Comment by Neurochimp** [comment]
Thanks soo much for working on this so fast though!

**Comment by lipefl** [comment]
What do you mean by HUD? I only worked in the character sheet. I'm not sure what do you mean by "that still only responds to a right click". If you can clarify where it's not working... 

Thanks!

**Comment by Neurochimp** [comment]
Sure. Sorry. There is a module that provides a heads up display for quite a few games including Savage Worlds. I put in a ticket with him because he added the run die in a recent update but it wasn't showing correctly after modifiers. Once that was fixed, it seemed to not function like the rest of the traits from the HUD which is why I first brought it up here since your module provides the simplified dialog boxes. I see that it works from the character sheet but still not the HUD so I was unsure whether it sits here or with the other module.
https://github.com/Drental/fvtt-tokenactionhud
![run_hud](https://user-images.githubusercontent.com/116909768/203679467-b87bf80f-fa73-4933-b122-fe76a1d153f8.jpg)

**Comment by lipefl** [comment]
Oh, ok, fine. The compatibility with SWADE Tools is on my end. 
The "right click" for me was a surprise, but i think i'll leave it this way, so the user can use both. I'll add the left click for Running Die as well in the next update, but it should be fixed there too, because not everybody uses SWADE Tools.

**Comment by Neurochimp** [comment]
Hi. Noticed on the Discord chat that it's been reported that the Run die is exploding using the simple dialog box in SWADE Tools. The Run die is one of the few rolls that doesn't explode. I tested with the older large box & it does not just to be sure.

**Comment by lipefl** [comment]
Yes, i probably forgot to remove the "explosion" command. I'll fix it as soon as i can (and also the Token HUD thing)

**Comment by lipefl** [comment]
Fixed in v1.10.13
Thank you!

**Comment by Neurochimp** [comment]
Thank you!
