### ISSUE TITLE
SWADE Tools & Elevation

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#189]
Not sure, if this is a bug or an enhancement: I have 2 characters 11 inch away from each other. One at the ground level (elevation 0) and one at elevation 5. When I shoot at the other one with a short bow, I hit with an 4. But it should be a 6 like it is when I move one of the token farer away to 12 inch. So my short bow calculates range on the ground floor correctly, but seems to ignore elevation. It would be great, if the SWADE Tools could handle also elevation.
In case it's a bug, let me know, if you need more data (I'm using Foundry 10-291, SWADE 2.1.6 & SWADE Tools 1.10.13).

**Comment by lipefl** [comment]
It's probably a bug, SWADE Tools take elevation into account. It might be some change in v10. I'll look into it. Thanks!

**Comment by lipefl** [comment]
Fixed in v1.10.14
