### ISSUE TITLE
Counting shots to core SWADE

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#19]
Now since SWADE v0.16.0 the ammo usage and reloading is part of the core. 
Could that be implemented into SWADE Tools too, or just use core system as is (need that reload button to weapon card)? Currently Tools overrides Core ammo usage&reload system.

**Comment by lipefl** [comment]
I'll take a look and see what can be done. I haven't tested v0.16 yet.

**Comment by lipefl** [comment]
So, i've installed v0.16 and swade tools do override, but they work basically in the same way. Just to be sure, your suggestion is just to add the Reload Button in the weapon dialog too?
The only difference between the core and swade tools is "ammunition" gear, but unfortunately i couldn't make it work, i didn't find the "ammunition" option in gear. Did you find it?

**Comment by Alis-72** [comment]
Its actually in weapons card: when enabled from settings, new box appears under Actions, and you type in name of the ammo-item.
