### ISSUE TITLE
SWADE Tools/Token HUD - Chat & Simple Dialog Box Both Populate 

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#191]
Hi again,

I have another issue that surfaced this morning & it's one that I'm having difficulty placing the module behavior.

Both SWADE Tools & Token Action HUD updated in the last day. When selecting from the character sheet, SWADE Tools simple dialog box appears. When using the HUD, I'm getting **both** the simple dialog as well as the chat dialog box for the selection.

Isolating both modules individually, they follow their own logic & the dialog boxes don't double up.  I've included a snip from the screen side by side. Attributes & the Run die do something similar - it skips the chat dialog and goes directly to the more complex dialog box.

![New_Issue_HUD](https://user-images.githubusercontent.com/116909768/206866027-b15ad4c1-15ce-4c4a-8493-d7c7b33f272d.png)

Let me know if this is Tools. If it isn't I'll put in a ticket with the HUD github.

Thanks,

**Comment by lipefl** [comment]
Fixed in v1.10.15
I think there's a problem there too. When i use the right click (without SWADE Tools), it fires twice.

**Comment by Neurochimp** [comment]
Thank you! I have confirmed the right click behavior & put a ticket in on that module's github.
