### ISSUE TITLE
[improvement] Use of Arcane device

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#192]
Hi,

when Swade Tools is activated Arcane device cannot work, the specific buttons that usually appears in the chat does'nt show at all.
Is it possible to display those buttons ?

Best regards.

**Comment by lipefl** [comment]
I had no idea they implemented this. I will have to figure it out how it works. Can you explain? Thanks!

**Comment by lipefl** [comment]
v1.10.16 now handles Arcane Devices. Thanks!

**Comment by Arnok13** [comment]
wouahou ! i have had no time yet to explain it. Amazing!
