### ISSUE TITLE
Covert provided with shield are not present in the calculation for ranged attacks

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#193]
Hi,

it seems that covert provided by shields (at least small ones) are not in the parry calculation for ranged attacks.

Best regards.

**Comment by lipefl** [comment]
Hi, as far as i know, shields cover dont protect automatically. It's basically when the GM feels like it should, since there's no "front or side" in swade tokens.

![image](https://user-images.githubusercontent.com/10639148/208245801-62c49a22-3606-46c0-bcb0-e3e52bff4733.png)
