### ISSUE TITLE
[improvement] Actions on weapons

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#194]
Hi,

is it planned to add the new actions on weapons in the swade tools Attack macro ?
Thanks for your time.

Best regards.

**Comment by lipefl** [comment]
You have to click "Show Dialog" for it to show the full dialog with all actions.

![image](https://user-images.githubusercontent.com/10639148/208246028-eb5cbebc-6705-454a-8aaf-7654bddd5fbb.png)
