### ISSUE TITLE
Mystic Powers

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#196]
Hello - Happy New Year!

Savage Pathfinder implemented a new form of limited Arcane Background called Mystic Powers for classes like the Monk, Paladin, & Ranger. The caveat with Mystic Powers is that they auto-succeed by spending the required power points. They do not require a die roll & the raise effect can be garnered via spending another 2 power points rather than rolling high.

Would it be possible to have a button that just pushes the Power to chat & deducts pp but doesn't require a roll? Maybe it only appears if the trait field is empty. 
It'd be not only useful for this but also the Cleric's Destroy Undead Class Edge and Innate Powers [setting pp required to 0 in this case].
![Mystic Powers](https://user-images.githubusercontent.com/116909768/210189538-ddf07731-db43-4577-aa9b-40f04d551bfa.png)
![Innate Powers](https://user-images.githubusercontent.com/116909768/210189542-bf285e48-02e6-41d8-b7b6-c0eb5f2d2b13.png)
![Destroy Undead](https://user-images.githubusercontent.com/116909768/210189543-17db2dd8-aa5f-488d-827e-0c58b2f4eda8.png)
I've included snapshots from the book just in case you need to review them.

Thanks,

**Comment by lipefl** [comment]
Hi! Happy New Year!
The problem here is there's no way to know if a power is a mystic power. If you have any ideas, but i think this must be implemented in the swade system first. Probably, a new kind of action or a checkbox "Mystic Power"

**Comment by Neurochimp** [comment]
Would this field work?
![Mystic Powers 2](https://user-images.githubusercontent.com/116909768/210271309-8a9ddf86-b414-48b1-bd71-64dd2c48f263.png)
If you add a label to the field 'Arcane' such as 'Mystic' it groups Powers under the same header. When you've done so it generates a Power pool for that group. _Which is great for standard SWADE or Rifts. Pathfinder doesn't use multiple Power pools. But that's another matter altogether I hope they're going to solve._

I was in the midst of putting in a ticket on the SWADE gitlab but then I realized they might just tell me that I should put 'Mystic' or 'Innate' in that field. It really doesn't solve the Cleric's use case because 'Destroy Undead' pulls from his normal Power Pool but doesn't require a roll. If it's viable, it would solve for the other two use cases though.

**Comment by Neurochimp** [comment]
Right now I set these Powers up as 'Fighting +3' for the Monk & 'Faith +3' for the Cleric. Which means it succeeds in all cases except a critical failure which we ignore or think of something funny [as long as no one's targeted]. Also ignore raises because it has no effect but it does both things I feel I need - it sends it chat & it deducts the points [except in critical fail's case].

**Comment by lipefl** [comment]
The "Mystic" Arcane would "solve" it, but, as you said, it'll deduct from the Mystic Power Points Pool. Not exactly the intended effect. How about you ask there in SWADE gitlab and we can work with what they say? Maybe there's an easier way and already in the system. Maybe they'll just put an option to an unique Power Pool.

**Comment by Neurochimp** [comment]
I'll get a ticket in over there then. Sorry, started a new job last week and though I did get a 3 day weekend, it means cramming 5 days of work into 4.

**Comment by Neurochimp** [comment]
https://gitlab.com/peginc/swade/-/issues/671

**Comment by Neurochimp** [comment]
Well I got half of what I asked for in 2.2. A toggle box was added for Innate Power.

**Comment by lipefl** [comment]
I think they're simmilar, so we can work with that. I'll let you know here when it gets updated.

**Comment by lipefl** [comment]
Innate Power is now available in v1.11.0
Please update.
