### ISSUE TITLE
Templates on powers cards, Elemental Weakness and several suggestions

### ISSUE THREAD

**Issue by Enmel** [lipefl/swade-tools#201]
Good day!

I have always used SWADE Tools since I really like how the combat flows, although the day before yesterday I gave better rolls a test and although I prefer Swade tools there are a couple of things that they do very well.

When casting spells, the card enables you a button depending on which area templates are available (if the spell allows them). By pressing the button you select the template of the spell. Like a shortcut. Also includes elemental resistance and elemental weakness damage modifiers.

I think they are details of quality of life that contribute a lot. As it would be to add the spell modifiers so that they at least discount the pps or increase the damage dice of the spell.

**Comment by lipefl** [comment]
Templates shortcuts are in the plans for future updates. 

There's a couple of things i didnt fully understand: 
1- What do you mean by "elemental resistence and weakness"? 
2- The spell modifiers (damage dice, etc) are handled by actions. So, how it'll be different?

Can you provide a video or maybe screenshots?
