### ISSUE TITLE
Actions on Simple Window

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#204]
Hello,

I've added to one of my weapons an action that calls for a resistance roll. The behavior in SWADE core is that it sends to the chat a card with a button for those impacted to auto-roll the resisting stat.  What happens when I just have SWADE Tools & SWADE core enabled is what is pictured below. It comes up with undefined then the name of the action - the Error is TypeError this.roll is undefined.

I've resisted using actions [they're new more or less] but I've found that calling for a fear, grapple, or stun resistance roll directly from the power or weapon does make things a bit easier on everyone.

Is there anything that can done to fix this?
![Acttion_Issue](https://user-images.githubusercontent.com/116909768/218496178-51664777-ad49-45c1-9b1c-849386934d27.png)
![Shock_Wp](https://user-images.githubusercontent.com/116909768/218496603-0688a410-26dc-4526-b128-a13a2ec98fe5.png)

**Comment by lipefl** [comment]
Resist actions now roll trait from selected targets. Please update to v1.11.0
