### ISSUE TITLE
Option to ignore scale penalties for monster features such as swat.

### ISSUE THREAD

**Issue by piedoomexplode** [lipefl/swade-tools#205]
As the title says. I've looked and haven't seen anything that will let me adjust the scale penalties so i'm having to throw in a gm modifier to accommodate for swat if a monster has it. Swade tools is great and thanks for all the work you are doing!

**Comment by lipefl** [comment]
You can add the "Swat" Special Ability to the monster. This will show a "swat" checkbox in the attack.
