### ISSUE TITLE
Vehicle sheet 'operation skill' not used in roll dialog

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#206]
Vehicle sheet 'Maneuver Check' does not use skill set in Description -> 'operation skill' but rolls  as Unskilled.

Tested on 
Foundry v10 291
SWADE v2.2.5
SWADE tools v1.10.16

**Comment by lipefl** [comment]
I tested and it's working fine. The only bug is that is showing "d4-2" regardless of the skill, but it's rolling the right die. Can you check if that's the case? I'll fix it.

**Comment by lipefl** [comment]
It's really a bug, someone found the problem on discord. It only works when Simple Rolls is active, while still showing d4-2, i'll look into it. Thanks!

**Comment by lipefl** [comment]
Fixed in v1.11.0
Please update.
