### ISSUE TITLE
Some tokens stopped targeting and automating

### ISSUE THREAD

**Issue by mcultraman** [lipefl/swade-tools#208]
Last game I had, my extras were targeting the pc's like normal and their rolls compared to their stats, but two other tokens did not. Everything was up to date, I tried various other fixes.

**Comment by lipefl** [comment]
It could be that the tokens were not linked to an actor. I need more information on this. Can you test? See if there's anything on the console log (F12) ?

**Comment by mcultraman** [comment]
I tested both tokens. They were representing the right actors. I linked
their data to see if that would help, still nothing.

I have no idea what to look for in the console log.

**Comment by mcultraman** [comment]
I looked through console, didn't see anything red. Here is the actor data.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lipefl** [comment]
I think avast blocked the file. Could you send through github.com?

**Comment by mcultraman** [comment]
I can't, it won't take json files.

**Comment by lipefl** [comment]
I'm sorry, i wasn't aware github was blocking json files. Just rename it to .txt and you can send it here. Alternatively you can copy the entire content here (in that case, if there's more than one file, please use one comment for each).

**Comment by mcultraman** [comment]
[fvtt-Actor-cult-boss.txt](https://github.com/lipefl/swade-tools/files/11073279/fvtt-Actor-cult-boss.txt)
[fvtt-Actor-sing-wu.txt](https://github.com/lipefl/swade-tools/files/11073280/fvtt-Actor-sing-wu.txt)

Here they are.

**Comment by mcultraman** [comment]
Thanks, I'll try that out.

**Comment by lipefl** [comment]
I'll close this issue. Feel free to re-open if you have any problems.
