### ISSUE TITLE
handle cover

### ISSUE THREAD

**Issue by EternalRider** [lipefl/swade-tools#209]
The current cover reduction can only be added either manually by the user doing the shooting before the roll, or by the GM after the roll and applied to the entire roll.
However, for situations such as fire suppression, where a single roll is made against multiple targets, it is not possible to distinguish between the different cover levels for each target, which makes it a little difficult to play the game.
If possible, it would be nice to have the cover reduction automatically determined as well as the range reduction.

Translated with www.DeepL.com/Translator (free version)

**Comment by lipefl** [comment]
1 - It'll be very complex and probably messy (meaning automation when you often don't want it).
2 - Great. But this needs to be implemented in SWADE system first. There's no "cover" field in it (at least, as far as i know). Maybe if you ask them to implement, i can work with that.

**Comment by EternalRider** [comment]
this [issue](https://gitlab.com/peginc/swade/-/issues/313) has been there 1 years ago......
I mean, before they do something, this mod can add this function by identify an object named "Cover" by treating cover as edge, feature, and ae.
It is possible to identify the specific cover subtraction from the name, e.g. "Cover2".
It is also possible to identify only the number of objects with "Cover", each of which is considered -2.
You can also identify "Light Cover", "Medium Cover", "Heavy Cover", "Near Total Cover " and then take the high.

**Comment by EternalRider** [comment]
> this [issue](https://gitlab.com/peginc/swade/-/issues/313) has been there 1 years ago...... I mean, before they do something, this mod can add this function by identify an object named "Cover" by treating cover as edge, feature, and ae. It is possible to identify the specific cover subtraction from the name, e.g. "Cover2". It is also possible to identify only the number of objects with "Cover", each of which is considered -2. You can also identify "Light Cover", "Medium Cover", "Heavy Cover", "Near Total Cover " and then take the high.

Only one of the three methods is needed to achieve sufficient results.
I personally prefer the last one.

**Comment by lipefl** [comment]
I see. This issue is for Dodge edge wich SWADE Tools already recognizes.
But... I was looking here, and Shields have Cover. If automation recognizes shields, you can use them as "Light Cover", "Medium Cover", etc. The only problem i see is when you don't want to consider "shield cover" since its only "from the front and shielded side" from rules. But you can just unequip the item, or the module can have an option do de-activate that for everything. 
I can work with that.

**Comment by EternalRider** [comment]
感激不尽！
Thank you so much!

**Comment by lipefl** [comment]
Added to v1.11.1 (activated by default, items need to be equipped to work)
