### ISSUE TITLE
Vehicular weapons not working

### ISSUE THREAD

**Issue by parvusdomus** [lipefl/swade-tools#21]
When clicking in a vehicular weapon (be it in the name or icon) in the vehicle sheet, it doesn't triggler the swade tools shooting roll.

Ideally it should do it and use the shooting skill of the character manning the weapon.

**Comment by lipefl** [comment]
Yes, i am aware. Vehicles are not supported yet. I probably forgot to put this information in the readme. But i plan to implement it soon.
