### ISSUE TITLE
Full Auto and 3RB

### ISSUE THREAD

**Issue by greggevans72** [lipefl/swade-tools#210]
My group and I are using Swade Tools in SWADE Rifts. We are noticing that if an Extra tries to do Full Auto or 3RB the weapon is used as if untrained. If I fill out the "Action Trait" with Shooting then it will work. It's my understanding that I shouldn't have to do that though.

**Comment by lipefl** [comment]
I tested and i don't see any problems. Have you filled the "Trait" field? If the "action trait" (inside the action) is empty , it'll use the "Trait" field of the weapon.

![image](https://user-images.githubusercontent.com/10639148/229520065-cccd1911-2135-47a9-a21a-b0389e79cd96.png)

![image](https://user-images.githubusercontent.com/10639148/229520208-d68df5e3-22d3-4c94-b56b-e9835c644f87.png)

![image](https://user-images.githubusercontent.com/10639148/229520261-eb258856-f1d0-4a96-b25e-7e03367fd545.png)

**Comment by lipefl** [comment]
Sorry, for some reason, I can't see the screenshot. 

But i found the problem, it's really a bug for NPCs... PCs works just fine. I'll fix it. Thanks!

**Comment by lipefl** [comment]
Fixed in v1.11.1
Please update.
