### ISSUE TITLE
Elan stacking with each reroll

### ISSUE THREAD

**Issue by architech99** [lipefl/swade-tools#216]
We ran into an interesting issue during last night's game. It looks like Elan is getting applied once each time there is a benny spent to reroll. In this case, there was a roll. The player spent a benny to reroll, which added Elan. Then spent another benny to reroll and it added the Elan bonus twice. So, I think something is up in the roll objects.

![elan-stacking](https://user-images.githubusercontent.com/1461748/233743619-28e2210d-9f3f-48d5-bc0e-8b21d05af1a1.png)

**Comment by lipefl** [comment]
I tested here, it's not happening for me. I know Elan checks if it's already applied, but it could be a bug. Have you tested with another actor?

Also.. can you provide the versions?
SWADE Tools
SWADE system
Foundry

**Comment by architech99** [comment]
SWADE System: 2.2.5
SWADE Tools: 1.11.1
Foundry: 10.291

I did just try it with another actor. The first and second reroll did not add it. The third re-roll did (looking back at the chat log from Thursday's game, that's what happened there as well). So, it correctly adjusts it on the first two re-rolls but adds a second Elan bonus if you spend a third benny.

**Comment by lipefl** [comment]
Oh! I get it. It's really a bug! Thanks!

**Comment by lipefl** [comment]
Fixed in v1.12.0
You must also update SWADE system, since v1.12 is only compatible with SWADE 2.3
