### ISSUE TITLE
Reload Magazine Not Functioning

### ISSUE THREAD

**Issue by RedVanGhoul** [lipefl/swade-tools#217]
With SWADE 2.3 going live, they added the ability to set up consumables as magazines for reloading. However, SWADE Tools doesn't seem to play well with this system and is always throwing an error about "Not having enough Ammo to Reload this Weapon" even when it is set to Magazine Style Reload.

Ammo Settings
![image](https://user-images.githubusercontent.com/67716629/233789594-2ab87337-494e-4a4c-8ac8-3539ef9d1e85.png)
![image](https://user-images.githubusercontent.com/67716629/233789614-dc003f34-72f5-4697-bfb6-90a36d76f604.png)

Using SWADE Tools
![image](https://user-images.githubusercontent.com/67716629/233789639-2b47a9fb-141c-4c96-8fee-96ecbd20dc45.png)
![image](https://user-images.githubusercontent.com/67716629/233789653-a76343b4-67cc-4b67-ad23-8579158e5fef.png)

Using Chat Card/Inv Card
![image](https://user-images.githubusercontent.com/67716629/233789737-7bd1567e-cb2f-42ed-a2ff-d3d38ba010aa.png)
![image](https://user-images.githubusercontent.com/67716629/233789764-1ec94ffd-1e76-4c49-8c4a-a4a00f3b3fec.png)

**Comment by lipefl** [comment]
I tested it here, if you create the item in the "Misc" Category, it'll work. It's probably not recognizing it from Consumables because it checks for quantity. I'm not sure how it should work from consumables, it consumes "Charges"? 
Also... Can you provide info about each Reload Type? What's the difference?

**Comment by RedVanGhoul** [comment]
SWADE 2.3 change reloading so that you can now choose to reload from a consumable and treat it as a magazine, rather than simply drawing ammunition from a "Gear" item. The charges on the consumable are treated as the bullets, and as shown in the last picture there is now a section on the gun's item sheet called "Loaded Ammunition" which gives the Consumable's name.
When reloading a fresh magazine or removing the current magazine (which requires a right click on the item in your inventory) it creates a new consumable with a number of charges equal to however many bullets were in the gun prior to reloading.

The [GitLab for SWADE](https://gitlab.com/peginc/swade/-/blob/develop/CHANGELOG.md) explains it, but the basic gist is that they've added new ways to handle reloading and SWADE Tools only seems to function the old way. I don't know what all the different methods do, but from what I can tell selecting "Full" under Reload Type on an item is the old way of handling it, and SWADE Tools seems to only want to try doing it that way (Bullets are a Gear item, as opposed to a Consumable being a Magazine).

**Comment by lipefl** [comment]
I see. It's a compatibility problem. I'll analyze it, maybe i'll leave everything for swade system to handle.
I'll let you know.
Thanks!

**Comment by RedVanGhoul** [comment]
You're welcome!

**Comment by lipefl** [comment]
Fixed in v1.12.0. Reload is now handled by SWADE system
