### ISSUE TITLE
Ammo usage when reload type = none not working as expected

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#218]
Just noticed: if weapon's Reload Type is set to 'none' (for 'reload 0' bows etc that do not require reload action) and Ammuntion is set, SWADE Tools attack dialog pops out "xxx don't have enough shots" and shows reload button that does nothing (as intended by Reload Type)

Systems own attack dialog works as intended (=makes attack normally and substracts one from set Ammunition).

Rest of the reload types work correctly.

Tested with 
Foundry v10 291
SWADE 2.3.6
SWADE Tools 1.12.0

**Comment by lipefl** [comment]
So, "none" Reload Type is the same as the old "auto reload" option, right?

**Comment by Alis-72** [comment]
Yes, exactly.

**Comment by lipefl** [comment]
Fixed in v1.12.1
Thanks for the all the help!
