### ISSUE TITLE
Melee Weapons causing "No Ammunition is Set" Error when SWADE Tools is enabled.

### ISSUE THREAD

**Issue by Deadlander** [lipefl/swade-tools#220]
Pretty much exactly as titled. Here is a video showing the issue. It only happens when SWADE Tools is enabled.

https://github.com/lipefl/swade-tools/assets/13036735/8fad61dc-c162-4852-9e0b-760570ae0b41

**Comment by Deadlander** [comment]
Also here is the console error enlarged and expanded:
![image](https://github.com/lipefl/swade-tools/assets/13036735/5efceb68-e6cd-486a-b3bb-4dcf5a4d79c6)

**Comment by lipefl** [comment]
Fixed in v1.12.2
Thanks!
