### ISSUE TITLE
Powers using wrong Template

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#224]
- Foundry 10.291 / SWADE 2.4.2 as well as Foundry 11.299 / SWADE 3.0.2 (I have two Foundry instances running)
- SWADE Tools 1.12.4
- no other modules

When I drag a template from my power to the map, it always uses the Large Burst Template (3) and not the selected Small Burst Template (1) or Medium Burst Template (2):
![Template](https://github.com/lipefl/swade-tools/assets/119852651/b640cf58-125b-49fb-8354-a6b029e14a05)

When I drag the template using the SWADE system button it uses the correct template.
Let me know, if you need more data.

**Comment by lipefl** [comment]
Fixed in v1.13.0
I wasn't able to test this version in v10, only v11, but since it was just a few adjustments, i think it'll work fine.

**Comment by Vogliadicone** [comment]
Thanks, works great under v10 as well!
