### ISSUE TITLE
Expanded Innate Power Chat Card

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#225]
Hello!

Just returning to revisit the Innate Power change to the module from back in March.

Would it be possible to get it to send to the chat card the text from the power that can then be expanded or contracted as needed?

Pic 1 is how a Power displays. If you click on the name, it expands to what is seen in Pic2. Pic 3 is currently what Innate Powers sends to the chat.
![Chat_Card](https://github.com/lipefl/swade-tools/assets/116909768/b93fda63-6c0c-40ed-a5e0-33fb28bf5980)

**Comment by lipefl** [comment]
Updated in v1.13.1
Thanks!
