### ISSUE TITLE
v11 "Dead" Large Skull Icon Not Removable After AutoApply From Wounds

### ISSUE THREAD

**Issue by josh-koonce** [lipefl/swade-tools#227]
I am not a professional bug tester, so pardon my incompetence.

Since the v11 update, where SWADE tools shows as compatible, whenever I kill a token via WOUNDS ONLY, I cannot remove the large skull icon from the token no matter how I approach it.

If I need to bring the character back to life (misroll or mistarget, etc), I can mark it as undefeated and set its wounds to 0, but the large skull icon can't be removed even with the right click context menu.

You don't even need to have the token in the combat tracker for this to occur. So setting it as defeated/undefeated is actually kind of irrelevant.

If I use the context menu to apply the large skull icon with the right click, prior to messing with wounds at all, it applies and removes normally.

![SWPFBug](https://github.com/lipefl/swade-tools/assets/99095735/0f49e6cc-6f03-4b3b-87c3-16108ac39b63)

**Comment by lipefl** [comment]
Fixed in v1.13.1
Thanks!
