### ISSUE TITLE
[Request] Please use weblate to manage translations

### ISSUE THREAD

**Issue by bnp800** [lipefl/swade-tools#228]
Weblate is a very helpful tool for translators, please consider using weblate hosted by foundry hub to manage translations.

For more information please check this: https://foundry-hub.github.io/weblate/

**Comment by lipefl** [comment]
I just sent the form to Foundry Weblate. I'll comment here when i have any news.

**Comment by lipefl** [comment]
I haven't had any response since. I'll reopen this if I get one.
