### ISSUE TITLE
Tracking Power Points not working

### ISSUE THREAD

**Issue by trechriron** [lipefl/swade-tools#23]
When I try to use a power, the chat box displays "not enough power points". I have set the counter on the powers page to 10 / 10, 0/10 and 10/0 and nothing changes. I also do not see PP subtracting or adding to the total.

FVTT v. 0.7.9
SWADE 0.16.2 (premium content)

**Comment by Alis-72** [comment]
All 'Arcane' has separate powerpoints and default value is 0/0 for powerpoints.
SWADE Tools only reads powerpoints from 'Arcane' without any description. So currently it doesnt support multiple arcane backgrounds.
With Official sheet, if every spell has something written in 'Arcane field' the 'all' field does not show and thus is defaults top 0/0.

Demo: switch to Community Sheet and see powerpoints under 'all' powers. Add powerpoints to it and all powers under different Arcane only use this pool and not their own.
Switch back to Official Sheet and 'All' list disappears (if there is no spells without  any text in 'Arcane'  box)

It would be optimal if SWADE Tools could user that 'Arcane' field of spells and choose correct powerpoint pool.

**Comment by lipefl** [comment]
I'll test it. I didn't take into account more than one AB when i did it, it's probably a bug due to this. I'll take a look. Thanks
