### ISSUE TITLE
Toekn Hud Bind

### ISSUE THREAD

**Issue by mrcomac** [lipefl/swade-tools#230]
Hi there,

I can see you have a bind to capture token hud actions

https://github.com/lipefl/swade-tools/blob/3b0e832b8cf72d7dc002148258102e5a5b9e2a41/scripts/class/TokenHud.js#L33

Since that one is capturing based on css tags, do you mind make swade hud available to trigger outside the module?

for example, br2 enables it from game.br2.internal_function where internal_funcion can be one of those available functions.

this way we can add support to swade tools nativally to action token hud for savage wolds.

cheers

**Comment by lipefl** [comment]
Hi, i've added these functions to open SWADE Tools dialog rolls. Let me know if you need anything else.

async game.swadetools.attribute(actor,attribute) => attribute dialog

async game.swadetools.skill(actor,skillItemId) => skill dialog

async game.swadetools.run(actor) => run dialog

game.swadetools.item(actor,itemId) => item dialog
