### ISSUE TITLE
Optimizing Action Cards UX

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#233]
When I click on a action, Core sends a card with all the available actions into the chat. If I click on the name of the action, it shows me the info text for that action:
![Action_1](https://github.com/lipefl/swade-tools/assets/119852651/2117a8dd-ac1e-4d81-b2bd-11555204c3c4)

When I use Swade Tools and click f.e. in the Token Action HUD on the action, I get asked, which Skill I wanna use:
![Action_2](https://github.com/lipefl/swade-tools/assets/119852651/6638476d-2361-43f2-90a7-00d3534d7cd9)
Ant after that I get a card with all available actions:
![Action_3](https://github.com/lipefl/swade-tools/assets/119852651/5bd97d88-dc0d-4c0e-9e55-901b29abcd43)

What I don't get here is the info text for the action. Also the design of the card is not optimal and it gives me in the first place an not working damage button.

I'm not sure, what would be the best solution for this, but I would at least like to have an option to see the text as well. And to maybe hide the not working general damage button.

- Foundry VTT: 11.302
- Swade System: swade 3.0.4
- SWADE Tools: 1.13.1
- Token Action HUD for Savage Worlds v0.6.1

**Comment by lipefl** [comment]
The thing is Token HUD was getting all items through SWADE Tools, when it should get only weapons and powers. But it was fixed to get back to the system default.
Please update to v1.13.2
