### ISSUE TITLE
ENH: Add Support for Automated Animations on Templates

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#235]
I use Automated Animations for attacks and powers. When I place a template via the SWADE core card, the animation is shown immediatly after I placed the template:
![Core_1](https://github.com/lipefl/swade-tools/assets/119852651/0875294d-31a9-498a-b565-dc67e6bf9dd3)
![Core_2](https://github.com/lipefl/swade-tools/assets/119852651/276f6fc2-0ce8-40b1-a916-ffb035639de2)
![Core_3](https://github.com/lipefl/swade-tools/assets/119852651/f0bc57b9-875f-41f3-bfc5-46051ea2756a)

When I place the template via the Button from SWADE Tools, nothing happens:
![SWADE_Tools_1](https://github.com/lipefl/swade-tools/assets/119852651/5a4d5639-e89d-4b2c-befd-f53c69310809)

Could you change the behavior of Swade Tools, so that it shows the animation like SWADE Core?

In case it helps: I'm not sure, but I think, the behavior from SWADE Core might be a result of these (quite new) changes:
[#796 Add support for Automated Animations](https://gitlab.com/peginc/swade/-/issues/796)

- Foundry VTT: 11.302
- Swade System: swade 3.0.4
- SWADE Tools: 1.13.2
- Automated Animations 4.2.60 (I configured AA to show the animation in general with the SWADE action and not the damage roll, but that's not working for templates)
- Sequencer 3.0.11
- Browser: Google Chrome

**Comment by lipefl** [comment]
Fixed in v1.13.3.  Thanks!
