### ISSUE TITLE
SWADE tools not removing icons

### ISSUE THREAD

**Issue by ratpooka** [lipefl/swade-tools#236]
It seems that tools will not actually register or auto removes icons. how can I fix this?

fvtt  11.304
swade 3.0.4
swade tools 1.13.2

![image](https://github.com/lipefl/swade-tools/assets/138188602/e1288636-c607-4ab8-a812-57ef8f8269ea)

![cap1](https://github.com/lipefl/swade-tools/assets/138188602/c0d83937-5f6e-4e26-9867-650135160dd3)
![cap2](https://github.com/lipefl/swade-tools/assets/138188602/239e95b1-7ecf-47d7-88f2-6790594a4639)

**Comment by lipefl** [comment]
It seems that is not removing Shaken automatically. Is that what you mean?
It's probably a bug with the updates. You'll have to remove manually until it gets fixed.
I'll let you know here.

**Comment by ratpooka** [comment]
yeah, that is what I mean. it will not remove any status. Seems to happen more in combat. I have uninstalled everything one thing ate a time down to fvtt itself. same issue. I remade the tokens. same issue. even made a new game world and tested it. same issue.

**Comment by lipefl** [comment]
Fixed in v1.13.3.  Thanks!
