### ISSUE TITLE
ENH: Trigger AA also with a Free Reroll oder when spending a Benny

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#237]
I'm using Automated Animations and configured AA to show the animation with the action roll. So when I click on the "Spellcasting" button in the Action card:
![SwadeTools_1](https://github.com/lipefl/swade-tools/assets/119852651/39a7b8dd-0d53-4eae-b6f8-52bbd79f45fd)
AA shows an animation:
![SwadeTools_2](https://github.com/lipefl/swade-tools/assets/119852651/1ef8bc9e-02a4-489e-b33a-8e0dacd8dbfc)
But when I miss the roll and repeat it via the "Free Reroll" button or by spending a Benny, no animation is triggered:
![SwadeTools_3](https://github.com/lipefl/swade-tools/assets/119852651/f4761e7f-7a07-477b-bfb8-07ee28bbb0b6)

I would like to see the animation also with the Free Reroll and when spending a Benny. I don't know, if you can change the behavior of these buttons easily, so that they trigger the AA as well, but if you can, I would love to see it changed.

- Foundry VTT: 11.304
- Swade System: swade 3.0.4
- SWADE Tools: 1.13.2
- Automated Animations 4.2.60
- Sequencer 3.0.11
- Browser: Google Chrome

**Comment by lipefl** [comment]
The problem here is that i dont know what is triggering AA. 
The rerrol just repeats the roll, same code. Ok, maybe it's missing something, but i can't seem to find it.

**Comment by Vogliadicone** [comment]
I asked on discord in JB2A aa-question and SWADE. As far as I understand, AA has a hook for SWADE that triggers the animation:
https://github.com/otigon/automated-jb2a-animations/blob/main/src/system-support/aa-swade.js

If there is no special system hook, it's the createChatMessage hook:
https://github.com/otigon/automated-jb2a-animations/wiki/Adding-System-Support

If it helps, I could send you the console output of a roll & reroll (with CONFIG.debug.hooks = true).

**Comment by lipefl** [comment]
I think i can solve with these links. Thanks!

**Comment by lipefl** [comment]
Fixed in v1.13.3.  Thanks!

**Comment by Vogliadicone** [comment]
Thanks, works like a charm!
