### ISSUE TITLE
Expend Power Points When Arcane Skill Rolls As An Action

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#238]
Hello,

I was working on one of my NPCs & I created a couple Actions to cover adding situational bonuses, penalties, & ROF/AP to Powers. I noticed that when rolling Spellcasting, Faith, or likely other arcane skills as an Action, it doesn't deduct the Power Points. Can this be fixed so that Actions deduct PP?

Thanks,

Kenn
![Action_PP](https://github.com/lipefl/swade-tools/assets/116909768/0ff91832-6540-4d92-803d-dfabd9f8692f)

**Comment by lipefl** [comment]
It was a bug. Fixed in v1.13.3
Tip: you can use "shots used" field to change the PP Cost in the action.
