### ISSUE TITLE
Getting "Error: This is not a registered game setting"

### ISSUE THREAD

**Issue by QckSilverDragon** [lipefl/swade-tools#24]
As the title says, i get this error anytime i try to make a skill roll for a weapon.

FVT: v0.7.9
SWADE: v0.16.2

Uncaught Error: Error: This is not a registered game setting
    at Dialog.submit (foundry.js:13153)
    at Dialog._onClickButton (foundry.js:13112)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

**Comment by Alis-72** [comment]
Seems that the issue links to Dice So Nice. When I disable that,  weaponroll works.
Error persists with only SWADE Tools + Dice So Nice active.

**Comment by parvusdomus** [comment]
Looks like a combo between DSN, SWADE 0.16.2 and swade tools. If you disable DSN you have no errors. If you leave DSN but go to a previous SWADE version (0.16.1) it works too.

**Comment by lipefl** [comment]
Yes, a friend told me yesterday. It's a bug with dice so nice wild die. I'll fix asap and update.

**Comment by lipefl** [comment]
Sorry guys, i didn't noticed my swade was 0.16.1
The way Dice so nice works changes in 0.16.2
It's fixed now. Please update it.
