### ISSUE TITLE
[ENH] Show available templates in power card

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#240]
Just an minor Enhancement: My group uses the Token Action HUD for SWADE and trigger most rolls via the HUD, which works great with SWADE Tools. But when one of my players wants to use a template, he still has to open the character sheet, to place the template:
![HUD_2](https://github.com/lipefl/swade-tools/assets/119852651/3f1fadc3-9d75-43e2-a435-9573eb973b19)
Would it be possible, to show the clickable template buttons (in this example the 1 2 3) not only in the quick access, but also in the power card:
![HUD_1](https://github.com/lipefl/swade-tools/assets/119852651/c7282271-aa6c-4c24-a109-3dded976666f)
Maybe above or under the duration?

I think, that would be a cool addition even for groups that didn't use the Token Action HUD.

- Foundry VTT: 11.304
- Swade System: 3.0.4
- SWADE Tools: 1.13.3
- Browser: Google Chrome

**Comment by lipefl** [comment]
Available in v1.13.4
