### ISSUE TITLE
Strange issue with Attack macro 

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#241]
Hi,

SWADE 2.4.2
Foundry V10.304
Swade Tools : 1.13.3 

Sometimes the result of an attack with the macro does not appear in the chat :
![image](https://github.com/lipefl/swade-tools/assets/4520046/3539d353-9e11-42b3-9df0-fa1c12d0939b)

there are theses errors

and i cannot apply damage to the target (nothing in the chat for that).

Best regards.

**Comment by Arnok13** [comment]
and no information if the attack is successful or not.

**Comment by lipefl** [comment]
I'm afraid that, because of the changes made, 1.13 is not fully compatible with v10 and swade 2.4 anymore.
I'm running a game with these versions and i use SWADE Tools 1.12.4
You can download it here in "Releases"

**Comment by Arnok13** [comment]
great ! thanks a lot.
