### ISSUE TITLE
Attack macro won't show 'off-hand' gear actions

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#242]
Attack macro does not list (or see) weapons equipped in 'off-hand'
If only off-hand items in quick access, it outputs warning 'No item equipped on selected token'
Weapons equipped in main hand (or two hands) work as intended.

**Comment by lipefl** [comment]
Fixed in v1.14.0
Only compatible with SWADE system 3.1.x (please update SWADE system as well)
