### ISSUE TITLE
[ENH] Desperate Attack is now a standard rule

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#244]
I just realized that in the latest errata for Savage Worlds, the Desperate Attacks where added to the standard rules. See page 3:
https://peg-swade.s3.us-west-2.amazonaws.com/SWADE_Updates_v10.pdf
Therefore it will be added as a modifier to the SWADE Core Module in the next version 3.1:
https://gitlab.com/peginc/swade/-/issues/847

Because of this, it might be an idea to remove the "Rules for Settings" section and move the option to the situational rules or always show the desperate attacks (like the Wild Attack nowadays).
![SWADE_1](https://github.com/lipefl/swade-tools/assets/119852651/398ecbec-b26c-4f52-86f1-407d3c1b6034)

And since you can choose only one of them for an attack, I think, it might be clearer, if "Wild Attack" and "Desperate Attack" would be in one place or list in the attack card:
![SWADE_2](https://github.com/lipefl/swade-tools/assets/119852651/2305c0f7-6089-445f-9783-4e9c58ee474c)

If it's a list, it could be expanded by other options from Core as well, that aren't handled automatically by Swade Tools. Like f.e. Illumination. But ok, that might become to much.
![SWADE_3](https://github.com/lipefl/swade-tools/assets/119852651/94c915bc-3928-4ec5-a2be-8e1c422ec603)

I laso have no idea, how many people are really using desperate attacks in their games. So maybe some might still prefer to not show them as an attack option?

- Foundry VTT: 11.305
- Swade System: 3.0.5
- SWADE Tools: 1.13.4
- Browser: Google Chrome

**Comment by lipefl** [comment]
I think it's better to wait 3.1 to remove the option. So i'll keep the issue here as a reminder. I like the idea to merge wild and desperate, i'll think about it.
About the "other modifiers" there's already an option in the module:

![image](https://github.com/lipefl/swade-tools/assets/10639148/0a6972c7-cdad-4582-9b6a-459bf5baeaf0)

**Comment by lipefl** [comment]
Changed in v1.14.0
Only compatible with SWADE system 3.1.x (please update SWADE system as well)

Desperate attack is always shown and now merged with Wild Attack
