### ISSUE TITLE
GlobalMods not counting on rolls

### ISSUE THREAD

**Issue by itsmegrave** [lipefl/swade-tools#245]
SWADE tools not taking the `.globalMods` modifier on rolls

**Comment by lipefl** [comment]
What do you mean by `.globalMods` ?

**Comment by EternalRider** [comment]
globalMods是新版本添加的内容，包括全局的伤害加成和攻击加成等等。
此外，新版本还改变了动态效果对技能加值的应用，其不再修改技能加值，而是只在掷骰界面出现。
————————
globalMods are added in the new version, including global damage bonuses, attack bonuses, and more.
In addition, the new version changes the application of dynamic effects to skill bonuses, which no longer modify skill bonuses, but only appear on the roll screen.

**Comment by lipefl** [comment]
Which version? I tested in 3.0.6 (latest) and i can't find any of that. Can someone please provide screenshots?

**Comment by EternalRider** [comment]
3.0.6
![image](https://github.com/lipefl/swade-tools/assets/46736326/dec168d6-a578-45b1-b08c-2ab1e9c3cec5)
![image](https://github.com/lipefl/swade-tools/assets/46736326/341b905b-812c-4bfd-9ee8-0ce48af6f9fd)
![image](https://github.com/lipefl/swade-tools/assets/46736326/4185f580-e366-4d59-8def-2b6f5bb2f34d)

**Comment by lipefl** [comment]
Thanks!

**Comment by lipefl** [comment]
Fixed in v1.14.0
Only compatible with SWADE system 3.1.x (please update SWADE system as well)
