### ISSUE TITLE
[ENH] Improved Frenzy now adds a 3rd Fighting die

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#246]
The new errata 5.0 for Savage Worlds:
https://peg-swade.s3.us-west-2.amazonaws.com/SWADE_Updates_v10.pdf
changed the way, Improved Frenzy is handled:
"P42 IMPROVED FRENZY [5.0]: Replace the existing text with:
As Frenzy but the fighter adds a third Fighting die to his Fighting attack made with Frenzy this turn."

Even if there's no errata for Savage Pathfinder that changed Improved Frenzy accordingly, I would recommend switching in SWADE Tools to the new implementation.

- Foundry VTT: 11.307
- Swade System: 3.0.6
- SWADE Tools: 1.13.4
- Browser: Google Chrome

**Comment by lipefl** [comment]
Fixed in v1.14.0
Only compatible with SWADE system 3.1.x (please update SWADE system as well)
