### ISSUE TITLE
Allow player to add extra d6 damage to Power damage.

### ISSUE THREAD

**Issue by r2roberts** [lipefl/swade-tools#248]
Some Powers, such as Bolt, allow an extra d6 damage, causing the bolt to do 3d6 damage (4d6 on a raise). There should be a way to add this damage before the roll, so that wounds can be calculated correctly, and Aceing can happen.

**Comment by lipefl** [comment]
You can add dice modifier, just type "d6" in the Mod. field (or any dice formula)
Specifically for Bolt power, i suggest you create a damage type action in the item, since you will use it many times.

I'll close the issue. Feel free to reopen if you have any questions.

**Comment by r2roberts** [comment]
Adding the d6 to mod worked! Fantastic!! You should advertise that fact.
--
Randy M. Roberts
***@***.***

*“The law that entropy always increases, holds, I think, the supreme
position among the laws of Nature.*
*If someone points out to you that your pet theory of the universe is in
disagreement with Maxwell's equations — then so much the worse for
Maxwell's equations.*
*If it is found to be contradicted by observation — well, these
experimentalists do bungle things sometimes.*
*But if your theory is found to be against the second law of thermodynamics
I can give you no hope;*
*there is nothing for it but to collapse in deepest humiliation.” *
― Arthur Eddington, New Pathways in Science

**Comment by r2roberts** [comment]
It even Aces!!!!!!!!
--
Randy M. Roberts
***@***.***

*“The law that entropy always increases, holds, I think, the supreme
position among the laws of Nature.*
*If someone points out to you that your pet theory of the universe is in
disagreement with Maxwell's equations — then so much the worse for
Maxwell's equations.*
*If it is found to be contradicted by observation — well, these
experimentalists do bungle things sometimes.*
*But if your theory is found to be against the second law of thermodynamics
I can give you no hope;*
*there is nothing for it but to collapse in deepest humiliation.” *
― Arthur Eddington, New Pathways in Science
