### ISSUE TITLE
Vehicle's Handling

### ISSUE THREAD

**Issue by SpaceCal** [lipefl/swade-tools#250]
Hi.
I tested the vehicles and it seems that Handling is not taken into account in the Maneuvering jet.
It works correctly when SWADE Tools module isnt used.

**Comment by lipefl** [comment]
Thanks.
There's another bug when the driver doesnt have the skill... just to remind myself...

![image](https://github.com/lipefl/swade-tools/assets/10639148/b1bc40bc-2a56-42e1-b9b9-f6e3a98e3bb5)

**Comment by lipefl** [comment]
Fixed in v1.14.0
Only compatible with SWADE system 3.1.x (please update SWADE system as well)

**Comment by SpaceCal** [comment]
It works perfectly, thanks :)
