### ISSUE TITLE
AEs Modifiers not working in v11

### ISSUE THREAD

**Issue by Gorka-de-Ituroitz** [lipefl/swade-tools#251]
Hello,
As discussed in issue #231 , the Savage Worlds v3.1 system has been released, but the AEs modifiers doesn't work:
Modifiers like the -1 to notice and common knowlendge from clueless (and other AEs modifiers from different Edges) doesn't work despite the system now takes them in account.
Thank you.

**Comment by lipefl** [comment]
Yes, they changed a few things. I'll close it here since it's related to #245

**Comment by Gorka-de-Ituroitz** [comment]
Good to know everything is under control. Thank you.
