### ISSUE TITLE
Actions Broken in SWADE Tools as of SWADE 3.1.x

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#252]
Morning,

Thought everything was working fine last night in game until one of my players wanted to use an Action on his item to do Sneak Attack damage instead of normal damage. We found that neither Trait nor Damage variants of the Action on an item were working and suspect they don't work on Actors either. Did not try Resistance version. The Changelog mentions changing the name of some of these elements & this may be what is causing the issue.

First bullet mentions change of skill to trait. Second bullet point mentions changing terminology from weapon specific to more general terms like ROF to Dice. I added another bullet point at the bottom from the log in which they mention macros have been enabled in Actions as well.

![SWADE 3 1 Changes](https://github.com/lipefl/swade-tools/assets/116909768/0998ef61-273e-4d07-b0e5-8035ab995a87)

**Comment by lipefl** [comment]
Fixed in v1.14.0
