### ISSUE TITLE
[Bug] SWADE Tools applies cover to all Powers

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#253]
It might be this way for longer, but I realised it right now with 1.14.0 for the first time: SWADE Tools applies cover as a penalty against all spells against a character. But it should only make Bolt harder, but not all Powers.
![Cover](https://github.com/lipefl/swade-tools/assets/119852651/96471340-ff7a-410a-9807-72dc29a63edd)

I would recommend limiting cover to Bolt or, if that's not possible, to remove ther cover handling for powers at all.

- Foundry VTT: 11.308
- Swade System: 3.1.3
- SWADE Tools: 1.14.0
- Browser: Google Chrome

**Comment by lipefl** [comment]
Yes, the modifiers should affect only damage powers. I'll take a look into how to solve it. Thanks.

**Comment by Vogliadicone** [comment]
Cover effects only Bolt, not all damaging Powers. The rules for Bolt say explicitly:

_"There are no Range penalties, but the arcane skill roll is affected by Cover, Illumination, and all other usual penalties."_

While for Powers like Burst or Blast they refer to Area Effect Attacks and there it says:

_"To attack with a blast template, the player places the template on the tabletop [...] and rolls [...] If the roll is successful, any target even partially beneath the template is affected,regardless of any attack penalties to hit such as the Dodge Edge."_

So Cover, wether it's from a Shields or Dodge didn't help against Blast or Burst. But right now, they do.
If you want, a shield (but not Dodge) could maybe reduce the damage from these attacks, but I think, that's up to the DM:

_"Solid obstacles like trees or brick walls protect against area effect attacks if they’re between the origin of the blast and the GM reasonably thinks they’d apply. Reduce the damage by the amount listed on the Cover Bonus table under Cover & Obstacles, page 99."_

Therefore I think, cover should be limited to Bolt or, if that's not possible or to tricky, it should be removed from the Power handling at all.

**Comment by lipefl** [comment]
I get it. I'll look for a away to ignore these, maybe checking if the power has Templates and also not showing for non-damaging powers.
I don't agree about removing from Bolt, because it's very useful in these situations and work as intended. 
Normally, in my games, when dealing with template powers, I just roll the skill and ignore targeting info. I use targeting to roll damage in these cases. That's probably why i never noticed it.

**Comment by Vogliadicone** [comment]
I use a module to auto target all tokens under a template, so my players are used to target with blast & burst as well.

And sure, it would be great, if bolt still could handle cover automatically. I was just not sure, if it's possible to limit the cover handling to one power only.

**Comment by lipefl** [comment]
Btw, which module do you use for auto-target?

**Comment by Vogliadicone** [comment]
[Walled Templates](https://foundryvtt.com/packages/walledtemplates) has an option for auto target.

**Comment by lipefl** [comment]
Changed in v1.14.3
Non-damaging powers only apply Vulnerable for target
AoE powers don't apply situational modifiers (cover, range, etc)
Thanks!
