### ISSUE TITLE
[Bug] RoF isn't working

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#254]
After updating SWADE to 3.1 & SWADE Tools to 1.14, RoF isn't working anymore. When I click on the Attack with RoF2 nothing is happening (i.e. no chat card shows up):
![RoF2](https://github.com/lipefl/swade-tools/assets/119852651/5edbaa81-d990-4499-9fae-71fed74f9912)
I have set up the Attack like this:
![RoF1](https://github.com/lipefl/swade-tools/assets/119852651/a7ecadac-9af4-478a-9450-5c8bd54cbdc5)

I'm quite sure, it worked, the last time I tested it under SWADE 3.0 & an older version of SWADE Tools.

- Foundry VTT: 11.308
- Swade System: 3.1.3
- SWADE Tools: 1.14.0
- Browser: Google Chrome

**Comment by ratpooka** [comment]
Same issue here. 

![image](https://github.com/lipefl/swade-tools/assets/138188602/66be9a8c-69e7-4761-bbf9-b78ff00b85db)

**Comment by lipefl** [comment]
Fixed in v1.14..1
It was a problem with "skill" actions because of the renaming of things in SWADE system 3.1.
