### ISSUE TITLE
Skill Bonuses on Weapons/Items

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#256]
Hello,

I was running a game last night and I noticed that SWADE Tools was not picking up the skill bonuses on weapons in the chat roll - it does seem to display on the button. Fighting +1, etc. Tested by running all modules without SWADE Tools & I do see the modifiers picked up in the roll chat. Can you check on such?

Thanks,

Kenn

**Comment by lipefl** [comment]
Fixed in v1.14.2
Thanks!
