### ISSUE TITLE
SWADE Core Rules Module 3.1.3 seems to have broken the way SWADE Tools handles skills for gear

### ISSUE THREAD

**Issue by OrElDuderino** [lipefl/swade-tools#258]
Hi,
Since updating the latest SWADE Official Core Rules Module, I get this error message whenever I click on gear, even gear from the SWADE Core Rules compendium. When I choose a skill, the popup window appears again, I can't close it.

I saw someone say that it's because SWADE Official Core Rules renamed skills to traits, is that right?

Also thanks for the module, I just donated to your Ko-Fi, I really appreciate your work.

![Screenshot 2023-09-09 at 05 09 39](https://github.com/lipefl/swade-tools/assets/119539553/6778cb25-829c-4aec-8c31-9e1c1236310e)

**Comment by lipefl** [comment]
Yes, they renamed some things. It might be it. I'll take a look. Thanks!
And thanks for the donation too :)

**Comment by lipefl** [comment]
Hi, i wasn't able to reproduce the problem. Can you give me the exact steps, with screenshots if possible? 
Also, please check if you are using the same versions.
Foundry v11.308
SWADE System 3.1.4
SWADE Core 3.1.3
SWADE Tools 1.14.2

Thanks!

**Comment by OrElDuderino** [comment]
You are a genius and I am an idiot: I had everything up to date _except_ SWADE System itself! I updated it and the problem went away. Thank you so much, I really appreciate your help so much.
