### ISSUE TITLE
Ammo from inventory not working

### ISSUE THREAD

**Issue by Rooksgate** [lipefl/swade-tools#26]
Hey ho.
I've noticed with SWADE-Tools installed, reloading from inventory does not work.
Another user noticed the same issue and received: "Uncaught Error: Error: This is not a registered game setting" (last updated yesterday)

Thanks!

**Comment by Alis-72** [comment]
Works on SOME of my characters. 
-Works on old long time ago created characters
-Not working on long time ago cloned character
-Not working on brand new created character
-Works if I clone again old working character
-Not working if I clone non-working character.
-creating new weapons or copying old does not have any effect.

Comparing export from working and non-working character but didnt see anything special.

**Comment by lipefl** [comment]
Fixed on 1.2.4. @Alis-72 it should work on all chars now. I was using a deprecated tag to check if it's PC or not, so this is probably why you get it to work sometimes.
