### ISSUE TITLE
system.actions.dmgMod not be calculated!

### ISSUE THREAD

**Issue by EternalRider** [lipefl/swade-tools#261]
System.actions.traitMod bonuses are calculated correctly and displayed in button and die roll flavors. The bonus of system.actions.dmgMod is not calculated.
as the picture shows.
system.actions.traitMod的加值可以被正确的计算，按钮和掷骰的flavor中都会显示。而system.actions.dmgMod的加值没有被计算。
如图所示。

![image](https://github.com/lipefl/swade-tools/assets/46736326/8226e92c-d753-49ca-9e46-66d96bb2fe49)

**Comment by lipefl** [comment]
Fixed in v1.14.4
Thanks!
