### ISSUE TITLE
New Attributes - Wounds/Fatigue Ignored

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#262]
Hello,

I found over the weekend that new attribute keys added to ignore fatigue and/or wounds don't seem to be functioning in SWADE Tools. Took some time this afternoon and tested with & without only to figure this out. 

They keys that aren't working are: 
system.fatigue.ignored
system.woundsOrFatigue.ignored

The following is untested but may also be impacted: system.wounds.ignored.

Net result is that you should still be able to have unhealed/unresolved wounds/fatigue on the character but using the relief power will allow you to ignore the penalty [-1/-2] for up to an hour. Very similar to the Nerves of Steel Edge which has pre-existed so may not be impacted.

The attributes above can be directly applied with Effects, but there is also a field in the Tweaks section of the character sheet that these can be set as well. Just in case there is a need to look at both.

If you can look into, I'd appreciate it.

Thanks,

Kenn

**Comment by lipefl** [comment]
Added in v1.14.5
Thanks!
