### ISSUE TITLE
Click on a Power on the NPC sheet with the no Power Point parameter set on create an error

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#263]
Hi,

On a NPC Sheet when i click on a Power, nothin  happens, just an error:
![image](https://github.com/lipefl/swade-tools/assets/4520046/fc6c17a9-06e9-4f92-81b5-7115f705a538)

i use the no Power Point setting rules

if i use the macro the powers work well.

**Comment by lipefl** [comment]
I wasn't able to reproduce the problem. Can you give me the exact steps?

Thanks!

**Comment by Arnok13** [comment]
![image](https://github.com/lipefl/swade-tools/assets/4520046/2ba9cbb1-1237-4ddb-93ee-3effdde07518)

**Comment by Arnok13** [comment]
![image](https://github.com/lipefl/swade-tools/assets/4520046/43c82367-28b0-4094-a7a9-8778650484cf)

**Comment by Arnok13** [comment]
hope it helps.

**Comment by lipefl** [comment]
I still can't reproduce the error, but i made minor updates that might fix it. If not, please, check your versions: 
Foundry 11.313
SWADE system 3.2.0
SWADE Tools 1.14.6

**Comment by Arnok13** [comment]
may be it's due to a conversion issue (it's an old world) ?

**Comment by Arnok13** [comment]
it works now ! 
thanks a lot !
