### ISSUE TITLE
[ENH] SwadeActor.isEncumbered got deprecated with SWADE 3.2

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#264]
Encumbered actors get this decreption message when rolling:
![error](https://github.com/lipefl/swade-tools/assets/119852651/2d1afc2a-2a98-4202-b565-5f8b889a8386)
No big deal, since everything is working, but you should maybe switch to SwadeActor.system.encumbered before SWADE v4.0 is released (which is planned for FoundryVTT v12). See the [changelog of 3.2.0](https://gitlab.com/peginc/swade/-/blob/develop/CHANGELOG.md?ref_type=heads):
"SwadeActor.isEncumbered is deprecated in favor of SwadeActor.system.encumbered, and will be removed in Version 4.0"

- Foundry VTT: 11.313
- Swade System: 3.2.0
- SWADE Tools: 1.14.5
- Browser: Google Chrome

**Comment by lipefl** [comment]
Fixed in v1.14.6
Thanks!
