### ISSUE TITLE
globalMods

### ISSUE THREAD

**Issue by EternalRider** [lipefl/swade-tools#266]
add globalMods and damage attribute effect modifier.

ItemRoll.js - replace
```
    addSkillMod(){
        this.addModifier(this.item.system.trademark,gb.trans('TrademarkWeapon.Label','SWADE'))
        this.addModifier(this.item.system.actions.traitMod,gb.trans('ModItem'));
        if (this.actor?.system?.stats?.globalMods?.attack && this.actor?.system?.stats?.globalMods?.attack.length > 1) {
            this.actor?.system?.stats?.globalMods?.attack.forEach(el => {
                this.addModifier(el.value,el.label);
            });
        }
    }

    addDmgMod(){
        this.addModifier(this.data.dmgMod,gb.trans('ModItem'));
        if (this.actor?.system?.stats?.globalMods?.damage && this.actor?.system?.stats?.globalMods?.damage.length > 1) {
            this.actor?.system?.stats?.globalMods?.damage.forEach(el => {
                this.addModifier(el.value,el.label);
            });
        }
    }
```
CharRoll.js - rollAtt - add
```
        this.actor.system.stats.globalMods[attribute].map(e=>{
            this.addModifier(e.value,e.label);
        })
```
CharRoll.js - rollSkill - replace
```
        if (item===undefined){
            item = await game.packs.get(gb.systemSetting("coreSkillsCompendium")).getDocument(await game.packs.get(gb.systemSetting("coreSkillsCompendium")).index.find(el => el.name == skillName)._id);
            skillName=`${gb.trans('Unskilled')} (${skillName})`;
            dieType=4;
            this.addModifier(-2,gb.trans('Unskilled'));
            if (item.system?.attribute != "") {
                this.actor.system.stats.globalMods[item.system.attribute].map(e=>{
                    this.addModifier(e.value,e.label);
                })
            }

            if (wildCard){
                wildDie=6;
            } 

        } else {
            dieType=item.system.die.sides;

            if (wildCard){
                wildDie=item.system["wild-die"].sides;
            } 

            this.addModifier(gb.skillModifier(item),gb.trans('ModSkill'))
            if (item.system?.attribute != "") {
                this.actor.system.stats.globalMods[item.system.attribute].map(e=>{
                    this.addModifier(e.value,e.label);
                })
            }

            if (item.system.attribute=='agility'){
                this.agilityMods();
            }
        }
```
CharRoll.js - changeStr- add
```
                    if (this.actor.system.attributes[data.name].die.modifier){
                        this.addModifier(this.actor.system.attributes[data.name].die.modifier,gb.trans(`Attr${data.short.charAt(0).toUpperCase()}${data.short.slice(1)}`,'SWADE'));
                    }
                    this.actor.system.attributes[data.name].effects.map(e=>{
                        this.addModifier(e.value,e.label);
                    })
                    this.actor.system.stats.globalMods[data.name].map(e=>{
                        this.addModifier(e.value,e.label);
                    })
```

![image](https://github.com/lipefl/swade-tools/assets/46736326/604c206f-475f-496a-bef5-8408dcc44f8e)

**Comment by Neurochimp** [comment]
I came here to put in a ticket for this after my last session. I tried to use a global mod for Blindness & it didn't come through in SWADE Tools. Hope it's something that can be worked in. If the following picture helps, this is how they are implemented as effects in English.
![global](https://github.com/lipefl/swade-tools/assets/116909768/00eed35e-b066-408a-bf1f-72bdbd28f3e8)

**Comment by EternalRider** [comment]
> I came here to put in a ticket for this after my last session. I tried to use a global mod for Blindness & it didn't come through in SWADE Tools. Hope it's something that can be worked in. If the following picture helps, this is how they are implemented as effects in English. ![global](https://user-images.githubusercontent.com/116909768/284014156-00eed35e-b066-408a-bf1f-72bdbd28f3e8.png)

That's what I done at this issue.
You can edit these js file that I wrote in first level.

**Comment by lipefl** [comment]
Added in v1.14.7

**Comment by Neurochimp** [comment]
Thank you!

**Comment by Neurochimp** [comment]
I tried testing this over the weekend and unfortunately I'm not seeing the global damage mod show up in the chat with the damage roll. Going to test the others over the holiday. Was able to confirm though that global damage does show up when I don't have SWADE tools on - just had core running, nothing else.

**Comment by lipefl** [comment]
I'll reopen to investigate.

**Comment by Neurochimp** [comment]
Thank you!

**Comment by Neurochimp** [comment]
Been a long time & I haven't tried any custom Global Mods. I built one for one of my players this week & unfortunately it did not work in SWADE Tools. It does work in Core with the base game. Attaching some screen clippings of what I see.
First pic is the global mod as an effect - works in vanilla but not in tools.
![Global_Mod _Issue](https://github.com/user-attachments/assets/4ff19852-5f5d-45c6-a0bf-061d36491f1c)
Second two shots are of two PCs - the top most part off the clip is rolled in core where it includes the modifier in the roll - present in the popup dialogue as well; the lower pics show it present on the character sheet, but then the last part of the clip shows what happens in SWADETools.
![Coryn_Error_1](https://github.com/user-attachments/assets/798acee1-a8c1-40b3-8e70-2faa8554525e)
![Rums_Error_1](https://github.com/user-attachments/assets/213f3a96-4177-42aa-9ac9-2050885adb7d)
If you could look into this, I'd appreciate it. I was on v11 till today. Seeing the same behavior on v12 as v11 last night.
Thanks again.

**Comment by Neurochimp** [comment]
Sorry the pics are so big!

**Comment by lipefl** [comment]
After looking at the code, I think global trait was skipped. All the other are working, right?

**Comment by Neurochimp** [comment]
Yeah, I am on v12 now. Took the plunge after giving 2 weeks for Savage Worlds update to get quick fixes on any breaking bugs.

I tried - system.stats.globalMods.attack just now & that does work.

**Comment by lipefl** [comment]
Added in v1.16.1
Thank you!
