### ISSUE TITLE
Uncanny Reflexes

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#267]
Uncanny Reflexes gives attackers a -2 on their attack rolls against the person who has the ability. Is there any way to automate this with Swade Tools? Can the module detect when a player/NPC has "Uncanny Reflexes" on their character sheet and apply the -2 automatically to the attack?

There doesn't appear to be a working active effect for this in SWADE Rule system.

Thanks

**Comment by lipefl** [comment]
Where's this ability found? Can you show a print or location where i can find it? 
SWADE Tools already detect the Dodge Edge, that does something similar to Ranged Attacks, so... probably yes

**Comment by gravagehulk** [comment]
It's in the Rifts Module - Tomorrow Legion Player's Guide. Compendium - Abilities. Here's the exact name and text:

Uncanny Reflexes

An upgrade to Nimble with increased effects. The vehicle, creature, or individual is −2 to be hit by any attack it is aware of and gains +2 on Evasion rolls.

There is also this one:

Crazy Uncanny Reflexes

Same exact description. That one is for Crazy Iconic Frameworks.

This is Nimble:

NIMBLE
The vehicle, creature, or individual moves quickly and erratically, making it difficult to hit. It is −1 to be hit by any attack it is aware of and gains +1 on Evasion rolls.

If you can add all three, that would be great. Ideally, there would be active effect support for these abilities, but the SWADE system has been slow to add those.

**Comment by lipefl** [comment]
For Nimble, you can use Combat Acrobat as it have the same effect. There's no -2 yet, so i might add something that catches it. I'm just worried because there's a Uncanny Reflexes superpower, but i'll think of something, maybe adding (Rifts) as a warn.

**Comment by lipefl** [comment]
Added in v1.14.7 as "Rifts Uncanny Reflexes". You have to add an ability or edge with that name to work. But you can change any name in "Change Default Names" button under SWADE Tools options.
