### ISSUE TITLE
Size and Scale with Vehicles

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#268]
Sorry, I have another one for you with Savage Worlds Rifts:

Testing today, I noticed that Swade Tools does not factor the sizes of the vehicles when comparing scale (for the sake of modifiers). It instead uses the Pilot's scale (as the pilot is making the check with the vehicle weapon). I confirmed this by changing the size of the pilot for each vehicle, which allows the modifiers to apply as expected.

Just wondering if there's an easy way to fix it so the attack takes the scale of the vehicles into account, rather than the pilot. 

Thanks

**Comment by YellowAdder** [comment]
I noticed this as well, and am also receiving an error when hits (or hits with raises) are used to roll damage. Nothing happens, and this is reported in my console:

Char.js:39 
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'strength')
[Detected 1 package: swade-tools]
    at Char.getStrForMinStr (Char.js:39:50)
    at Module.getStrForMinStr (gb.js:477:17)
    at ItemRoll.rollDamage (CharRoll.js:742:68)
    at ItemRoll.rollBaseDamage (ItemRoll.js:175:20)
    at RollControl.targetFunction (RollControl.js:1195:32)
    at HTMLAnchorElement.<anonymous> (RollControl.js:600:30)
    at HTMLLIElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by gravagehulk** [comment]
> I noticed this as well, and am also receiving an error when hits (or hits with raises) are used to roll damage. Nothing happens, and this is reported in my console:
> 
> Char.js:39 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'strength') [Detected 1 package: swade-tools] at Char.getStrForMinStr (Char.js:39:50) at Module.getStrForMinStr (gb.js:477:17) at ItemRoll.rollDamage (CharRoll.js:742:68) at ItemRoll.rollBaseDamage (ItemRoll.js:175:20) at RollControl.targetFunction (RollControl.js:1195:32) at HTMLAnchorElement. (RollControl.js:600:30) at HTMLLIElement.dispatch (jquery.min.js:2:43184) at y.handle (jquery.min.js:2:41168)

Yeah, it has actually been that way for a while. Originally, Vehicle attacks on non-vehicles did absolutely nothing. Lipefl at least got that working for us. I generally just click the vehicle weapon for the attack and then click it again for the damage, but it would be nice if it worked all the way.

Without Swade Tools, you can't even make attacks from vehicle weapons. They just do nothing when you click them.

**Comment by lipefl** [comment]
Fixed (everyhing) in v1.14.7
