### ISSUE TITLE
Vehicle Ranged Combat in Melee doesn't use Parry as TN

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#269]
Sorry, it's me again.

Testing vehicle combat against a non vehicle, when firing ranged weapons in melee, it isn't using the target's parry as the TN. For example, if a Spider Skull Walker fires its railguns at a Greater Demon in melee combat, it will hit on a 4 or above, but the demon has a parry of 15.

Thanks.

**Comment by lipefl** [comment]
No worries. This makes the module better. Thanks! :)

**Comment by gravagehulk** [comment]
> No worries. This makes the module better. Thanks! :)

You have done such a great job with this module. It's the only thing that makes SWADE playable for me in Foundry. Thank you so much for all of your hard work. I own Savage Rifts for Fantasy Grounds as well and the automation is better there overall, but it just looks so much better in Foundry. Until the Foundry devs step up a little, Swade Tools is filling in a lot of the gaps for those of us who are running games. This module is the sole reason I'll be able to run my game from Foundry.

**Comment by lipefl** [comment]
I intentionally excluded vehicles from "melee" rules, i'm not sure why. But i couldn't find any documentation on why vehicles are included/excluded in this rule, gang up, etc., so you're probably right. If you have any confirmation on this, it'll be appreciated.
Anyway, fixed in v1.14.7
