### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by parvusdomus** [lipefl/swade-tools#27]
Just installed the newest 1.2.3 version that fixes the DSN issue, but now I'm getting this one:

Uncaught Error: TypeError: Cannot read property '0' of undefined
    at Dialog.submit (foundry.js:13153)
    at Dialog._onClickButton (foundry.js:13112)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

Whenever I do a skill roll from a weapon equipped in a NPC sheet. From PC sheets it works and the damage rolls from a weapon in the NPC sheet work too.

**Comment by parvusdomus** [comment]
Uhm actually it is in extra NPCs, it works for wildcards

**Comment by lipefl** [comment]
I found the problem. I'm working on it... i will update to v1.2.5 asap 
thanks!

**Comment by lipefl** [comment]
Fixed!
