### ISSUE TITLE
No Power Points & Blood & Gore Setting Rules

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#272]
Hello.

I'm looking to implement these two setting rules in future campaigns. Is there a way to enable them in SWADE Tools?

**No Power Points** looks like SWADE TOOLS may be doing a bit of the work already. I see in the initial roll window, there is a Power Mod that calculates the penalty on Bolt to be -1. Which is correct, it's supposed to -1 for every 2 points of PP it would've cost. But that penalty isn't carried over to the chat window and applied to the roll. I've attached a pic of what I see. Tested this in Core and it did carry over.

**Blood & Gore** - This is a Rifts rule that's a variant of the Gritty Damage rule that I think gives Heavy Damage the teeth it is missing in a standard game. The Gritty Damage rule forces a roll on the injury table every time a character takes a Wound except in cases of 2 Shakens converting to a Wound. Its a bit excessive for what I'm looking for. Blood & Gore changes this ever so slightly that if a Heavy [MDC in its lingo] Weapon inflicts a Wound on a target not protected by Heavy [MDC] Armor, it forces [auto] the Injury table roll. That seems more what I'm looking for in which someone like Superman fully letting loose will cause aggravated damage to anyone not protected in a similar [Heavy Armor] manner.  

Savage Rifts' Tomorrow Legions Player's Guide has this as an option in its configuration & it works in core. Better Rolls 2 also has an option in its configuration that probably came before the official implementation. It basically recognizes if a Heavy Weapon hits a target without Heavy Armor & once the Wound is accepted, it auto rolls the injury table to determine what came of the intense aggravated damage [broken arm; marred eyesight; etc] except of course in the case of 2 Shaken results causing the Wound.

Any way to handle either of these in SWADE Tools?

Thanks,

Kenn
![No_PP_3](https://github.com/lipefl/swade-tools/assets/116909768/84782116-2ad8-4626-a205-27c5c6b3d4e7)
![Blood_Gore](https://github.com/lipefl/swade-tools/assets/116909768/a1733580-a5da-47af-8380-07946ede40dd)

**Comment by lipefl** [comment]
The power mod (instead of PP Cost) is just informative. You still have to add the mod manually. But yes, an option to auto add will be a nice adition. 
About the Blood & Gore, fine too. I'll leave a reminder here to check about the 2 Shaken situation, I'm not sure Gritty Damage detects this exception.

Thanks!

**Comment by lipefl** [comment]
Added in v1.14.8
Thanks!

**Comment by Neurochimp** [comment]
Thank you! Been sick these last two weeks but I really appreciate the implementation!
