### ISSUE TITLE
[bug] Powerpoint total gets zeroed (=0) when spells cast

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#274]
When actor casts a spell current powerpoints get reduced correctly but total powerpoints changes to 0.
No errors show in console.

Tested:
Foundry v11 build 315
Savage Worlds system v3.2.4
SWADE Tools v1.14.7

[EDIT: perhaps this is core issue https://gitlab.com/peginc/swade/-/issues/997 and not SWADE Tools...]

**Comment by Alis-72** [comment]
related to this perhaps https://gitlab.com/peginc/swade/-/issues/997

**Comment by lipefl** [comment]
This is probably related do SWADE system. I tested with SWADE system 3.2.2 and it works fine. But when i update the system, it occurs. I'll keep the issue open to check if I have to do something on my side.

**Comment by Alis-72** [comment]
SWADE system updated to v3.2.5 (bugfixes) and now the issue is solved, so it was core.
This issue can be closed.
