### ISSUE TITLE
[ENH] Show Templates on Weapon Cards

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#277]
When using a Power with a template, the template is shown on the roll card. But when using a weapon with a template (f.e. Granades), the Template isn't shown on the roll card. Could you show it there as well like with Powers? That would be super helpful.
![MBT](https://github.com/lipefl/swade-tools/assets/119852651/170a6bcf-ae61-4a6f-9469-90556d7ab67c)
- Foundry VTT: 11.315
- Swade System: 3.2.5
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by Vogliadicone** [comment]
Because I recognised it right now, I would also harmonise the left column for powers and weapons: Damage, Range, Templates would be best left. And Shots and RoF (weapons) or PP and Duration (powers) right.

**Comment by lipefl** [comment]
Added in v1.15.0
Thanks!
