### ISSUE TITLE
[ENH] Show Range in Power cards in Inches

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#278]
At the moment the Range in power cards is shown as attribute x multiplier, f.e. Sm x 2 or Sp. Would it be possible to calculate the range automatically and show there the actual number of inches, f.e. 16? I think that would be helpful for the GM and players alike.

- Foundry VTT: 11.315
- Swade System: 3.2.5
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by lipefl** [comment]
I'm not sure it can be done easily because it's a text field, so it's prone to errors. The code would have to interpret the text. It would have to take language into account too. Tbh, I think it's too much trouble.

**Comment by Vogliadicone** [comment]
You're right, I forgot the other languages. So it's better done on system level. I created an issue for it in the system repo. Maybe they consider it for the Powers reborn milestone...

**Comment by Vogliadicone** [comment]
You're right, I forgot the other languages. So it's better done on system level. I created an issue for it in the system repo. Maybe they consider it for the Powers reborn milestone...
