### ISSUE TITLE
[ENH] Some minor Enhancements for the attack cards

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#279]
When playing Savage Pathfinder especially the players with rogues have sometimes problems with the attack cards, because of the sheer number of different attack and damage option. Their cards look like these:
![Attack](https://github.com/lipefl/swade-tools/assets/119852651/2bb5630d-8a52-48e1-a416-fcc14bc9119d)
![Attack2](https://github.com/lipefl/swade-tools/assets/119852651/86fb8522-7283-4007-81f2-91f618899645)
Therefore 3 minor enhancements:
1. It would be nice, if attacks and damage rolls would be sorted. Like first show all attacks and later all damage options. To have them mixed gets my players sometimes a bit confused.
2. My players found the different symbol for the attacks iiritating. The normal attack has a target plate, the extra attacks a black circle. They would prefer to have always the target plate for attacks. But maybe there's a good reason for the different symbols?
3. Is there a specific reason, why the trademark weapon leads to the "Shooting +1"? Because the +1 is also applied to the "Double-Shot"-attack (but isn't shown there). Since other bonusses aren't shown there as well, I would find it more consequent to also not show the "+1" for the trademark weapon here.

- Foundry VTT: 11.315
- Swade System: 3.2.5
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by lipefl** [comment]
1. It's something i already plan for future versions. 
2. Probably a bug, all the "attack actions" are supposed to have the same symbol. I'll investigate.
3. The "+1" is just informative, it's the base attack (the base action). The others are the name of the actions (so no +1 unless you name it that way).  It's good to know the +1 you have is being counted. I don't think removing it would do any good. Players would start to think "is the +1 applied?".

**Comment by lipefl** [comment]
Fixed in v1.15.0. Thanks!
For (1) I'll keep it for future versions, since it's not a big issue and unfortunately I'll have to change a lot of code to make this happen.
