### ISSUE TITLE
Auto-Apply Statuses

### ISSUE THREAD

**Issue by Razortide** [lipefl/swade-tools#28]
Hello Dev,
I was wondering if it is possible to auto apply statuses based on other statuses like:

If Stunned or Bound, also check Distracted and Vulnerable
If Entangled also check Distracted

Also uncheck actions:
Remove Distracted AND Vulnerable if Unbound
Remove Vulnerable if Unstunned.

If this would be possible using Active Effects, this would be awesome!

**Comment by lipefl** [comment]
This is actually how swade-tools works. You can try this by checking/unchecking Stunned and Entangled in the sheet.

**Comment by Razortide** [comment]
Uhm. Sorry :-)
