### ISSUE TITLE
[ENH] Optimize RoF-Attacks

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#280]
Most likely, RoF attacks can't really be simplified because any solution would be too complicated or not possible at all, but maybe something will work... Therefore:

I have multiple players in my group which use imp. frenzy / rapid shot and so are doing multiple attacks all the time. And a lot of the extras are going down with just one hit. Which is fine, but applying damage to the right target isn't always easy and gets sometimes messy, because you only see what target you are actually damaging, if you are hovering with the mouse over the token. So it happened sometimes, that one of my players applied damage to the wrong or even an already dead target.

Therefore I think it would be great, if you could highlight the token, that is going to get the damage, when hovering over the damage field (1). Or if that's not possible, if you could grey out / mark the damage fields for the already killed targets (2).
![RoF](https://github.com/lipefl/swade-tools/assets/119852651/51b7fccc-7316-4f9d-a10a-b54eb38246da)
Like I said, I have no idea if any of this is possible at all or not. So feel free to just close this enhancement if it's not possible. But maybe it's possible or maybe you have a better idea / solution...
- Foundry VTT: 11.315
- Swade System: 3.2.5
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by lipefl** [comment]
I don't think option 2 would solve it completely. I'll check about option 1, i think it can be done and it'll be a nice addition for normal attacks too.

**Comment by lipefl** [comment]
Added (1) in v1.15.0
Thanks!
