### ISSUE TITLE
[ENH] Show "click to roll damage" on attribute trait rolls

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#281]
I set up a Wand of Bolt for Savage Pathfinder as an Weapon with up to 25 "shots", range, damage and two trait rolls: one for smarts and one for spellcatsing (Savage Pathfinder allows you to choose Smarts or your Spellcasting skill). When attacking with Spellcasting everything works fine. But when attacking with smarts the "click to roll damage" is missing:
![Wand](https://github.com/lipefl/swade-tools/assets/119852651/84bba61d-f51d-454d-951d-9715e4dd58cd)
Could you add the "click to roll damage" option there as well? Or is there a specific reason why it's not shown here?
- Foundry VTT: 11.315
- Swade System: 3.2.5
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by lipefl** [comment]
Probably a bug. Can you send me the item file?

**Comment by Vogliadicone** [comment]
Sure, there you go:
[fvtt-Item-wand-of-bolt-o6Z8etJIsJrTbR7k.json](https://github.com/lipefl/swade-tools/files/13879087/fvtt-Item-wand-of-bolt-o6Z8etJIsJrTbR7k.json)

**Comment by lipefl** [comment]
Fixed in v1.15.0
Thanks!
