### ISSUE TITLE
Roller adding *10 to permanent effects using die formula (eg. 1d4) unless precision is used (eg 1d4.0)

### ISSUE THREAD

**Issue by holmanj** [lipefl/swade-tools#282]
![Screenshot from 2024-01-24 07-19-47](https://github.com/lipefl/swade-tools/assets/28579574/21880567-af97-450c-94d8-d650e35766cc)
![Screenshot from 2024-01-24 07-08-00](https://github.com/lipefl/swade-tools/assets/28579574/f40934f1-dd56-4644-84db-f1f9e2a79c87)
![Screenshot from 2024-01-24 07-07-29](https://github.com/lipefl/swade-tools/assets/28579574/db7a2371-2cc7-49fa-a439-6a9e52b9f5aa)
![Screenshot from 2024-01-24 07-05-23](https://github.com/lipefl/swade-tools/assets/28579574/481ae13c-eb6b-4603-aa21-10bf13bf5179)
![Screenshot from 2024-01-24 07-04-54](https://github.com/lipefl/swade-tools/assets/28579574/7ab5c593-39ca-4b77-835b-fb5dacfd91d0)

**Comment by lipefl** [comment]
I wasn't aware that effects allow dice modifiers. I'll add support, thanks.

**Comment by lipefl** [comment]
Fixed in v1.15.0
Thanks!
