### ISSUE TITLE
[ENH] Show roll dialog for shields

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#284]
Shields can be used with fighting for bash attacks (SWADE p71). In SWADE the shields are already preconfigured for it with fighting as a trait and and bash attack damage action (Str+d4).

But right now SWADE Tools didn't show any roll card for shields. When clicking on the item in the quick access area (1) nothing hapens. I have to open the SWADE core roll dialog (2), to attack with the shield. But when I use that one (2), I get also the standard roll dialog and not the one from SWADE Tools. It would be nice, if you could show the SWADE Tools roll dialog for shields as well.
![Shield_01](https://github.com/lipefl/swade-tools/assets/119852651/5b6386e3-f36b-4599-98b7-96f9d1918770)
![Shield_02](https://github.com/lipefl/swade-tools/assets/119852651/cf92339a-df67-4201-a635-2f53f90d2b0f)
- Foundry VTT: 11.315
- Swade System: 3.2.5
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by lipefl** [comment]
Added in v1.15.0
Thanks!
