### ISSUE TITLE
[ENH] return SwadeRoll  when calling game.swadetools.run

### ISSUE THREAD

**Issue by mrcomac** [lipefl/swade-tools#285]
Is it possible to maintain the same behavior as the core module by returning a ``SwadeRoll`` when calling ``game.swadetools.run(actor)``?

When calling ``actor.rollRunningDie()``, it returns the roll from which I can obtain the result.

**Comment by lipefl** [comment]
``game.swadetools`` functions are used for another module (Token Action HUD), if i change the way they behave, it wont work properly.
Couldn't you just call ``actor.rollRunningDie()`` instead? What are you trying to accomplish?
