### ISSUE TITLE
Hardy isn't working?

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#286]
I was quite shure, that SWADE Tools automically detected the hardy ability on an actor and prevented a second shaken to be added as a wound. But now it's no longer working for me. It's not working when I place the hardy ability on the actor and it's also not working when I add the Active Effect "flags.swade.hardy" add "true" to the actor.

When I deactivate SWADE Tools, the system is detecting hardy when I add the Active Effect  "flags.swade.hardy" add "true" to the actor (right now the hardy ability in the premium modules doesn't come with an AE, I added a ticket for that at Metamorphic/Sigil).

Do SWADE Tools support hardy? And do I need the Active Effect "flags.swade.hardy" on the actor or should the hardy ability be enough?

- Foundry VTT: 11.315
- Swade System: 3.3.1
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by lipefl** [comment]
SWADE Tools detects Hardy as Edge or Special Ability, you can check at "Change Default Names" option. I tested here and it's working fine. To test, you'll need to apply the second "Shaken" damage and a warn appears, nothing happens.
I wasn't aware there's an AE for that, i'll add to the module.

**Comment by Vogliadicone** [comment]
Yeah, I was thinking that SWADE Tools hjust checked the name, but like I said, it workrd for me in the past, but right now it's not working anymore. I don't know, when it broke. It is not working for me in 3.3.1 and I think it also wasn't working for me with 3.2.5.

Let me know, if you need more data.
![Hardy1](https://github.com/lipefl/swade-tools/assets/119852651/21b5240a-2948-4904-aa77-eccffaec724b)
![Hardy2](https://github.com/lipefl/swade-tools/assets/119852651/472b9444-f89b-46be-8fb1-1f6a03b43a0b)
![Hardy3](https://github.com/lipefl/swade-tools/assets/119852651/5d34bc3c-e6c7-4ba6-8a7b-5fe3b7976ae3)

**Comment by lipefl** [comment]
My SWADE system was 3.2.5 when i tested. I updated it and it's not working anymore. I'll check. Thanks!

**Comment by lipefl** [comment]
Fixed in v1.15.0
Thanks!
