### ISSUE TITLE
[ENH] Update Unstoppable

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#287]
SWADE Tools seem to have implemented an old version of unstoppable ([Unstoppable #177](https://github.com/lipefl/swade-tools/issues/177)). The rule in the actual version of the Fantasy Compendium, Horror Compendium, Savage Pathfinder, Holler & Rifts says:

"The creature has strong will, magical protections, or great mass. It takes a maximum of one Wound per attack no matter how many Wounds would normally be caused (_**after Soak rolls are made**_).
If an attacker's Action Card is a Joker, he may ignore this rule. Some magic items or a creature's Weaknesses also bypass its Unstoppable ability, as listed in the description."

But right now, when I'm doing 2 Wounds damage and I soak one of them, the actor gets no damage at all (according to the actual version of the rules it should be 1 Wound + Shaken):
![unstoppable](https://github.com/lipefl/swade-tools/assets/119852651/c4be8d6b-888f-46dc-9eae-a3b75421b96a)

- Foundry VTT: 11.315
- Swade System: 3.3.1
- SWADE Tools: 1.14.8
- Browser: Google Chrome

**Comment by lipefl** [comment]
Fixed in v1.15.0
Thanks!
