### ISSUE TITLE
Problem using with dice so nice module.

### ISSUE THREAD

**Issue by Lifthraser** [lipefl/swade-tools#29]
When using swade tools 1.2.5 with the module dice so nice 3.3.1 (latest version) i can't use the reroll with a bennie button or the soak damage button, when i click any of thoose the bennie is spent but nothing else happen.
The problem has been replicated by 3 users afaik.

**Comment by lipefl** [comment]
Fixed. Update to 1.2.6 please. Also different wild die is not showing on reroll, but i'll fix that later, since it's not a feature that will break the game. Thanks.
