### ISSUE TITLE
Show info when clicking on weapon/power/skill name setting does not apply to Quick Access items when unchecked

### ISSUE THREAD

**Issue by DrFeelgood21** [lipefl/swade-tools#291]
Occurs: When playing with this setting unchecked in SWADE Tools, clicking on an item in the Quick Access area of the character sheet will open both the SWADE Tools rolling dialog as well as the information panel with actions on the character sheet (default SWADE behavior)

Expected: With this setting unchecked, I was expecting _only_ the SWADE Tools dialog to appear when clicking on an item in Quick Access

**Comment by lipefl** [comment]
Fixed in v1.15.0
Thanks!

**Comment by Vogliadicone** [comment]
Maybe a side effect of fixing this: Now in 1.15.0 when the setting is checked, clicking on an item in the Quick Access area of the character sheet will open both the SWADE Tools roll dialog as well as the information panel with actions on the character sheet. Shall I open another ticket or is this enough?

**Comment by lipefl** [comment]
Yes, it is a side effect, at it's noted in the relase notes. I should have mentioned it here, sorry.
- Fixed dialog also opening description ("Show info when clicking..." option will now do both - open dialog and show description - due to the way SWADE system now handles the accordion animation)
