### ISSUE TITLE
Updated German Translation for SWADE Tools v1.14.8

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#292]
Since the German translation for SWADE Tools was 3 years old and based on v1.3.4, I updated the translation to v1.14.8.

I hope I did everything right, since that was my first time attempt with GitLocalize. I added the RAW translation file to this issue. Let me know, if you need the data in another file or if there's a better way (Weblate would be great).
[de.json](https://github.com/lipefl/swade-tools/files/14639271/de.json)

**Comment by lipefl** [comment]
Just the de.json file works fine. I'll add it in the next update.
I tried to contact foundry weblate, but no response from them. I'm not too familiar with it either, so im not sure how to implement, if i can implement it on my own. Any help would be appreciated.

**Comment by Vogliadicone** [comment]
Since there's a weblate for a bunch of other SWADE modules, I think, they might just have forgotten your request. So maybe ask gain or maybe ask on Discord (since the Foundry crew seems to be mostly active there)...

**Comment by lipefl** [comment]
Updated in v1.15.0
Thanks!
