### ISSUE TITLE
Criticcal Failure Anomaly - Multi-Dice

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#295]
In last session,  a player had a rapid shot action flagged as a critical failure when it should have been one failure & one success [barely as long as it was short range & it probably was for his bow]. The issue here arose with 2 of the 3 dice rolling a 1 but the wild die rolled a 2. The rule on page 118 in Pathfinder for Savage Worlds states that if half or more dice come up a 1 on a Frenzy/Rapid Fire type action it is a Critical Failure **but** the Wild Die must be one of those 1's. Honestly, it feels like a bit too much luck is thrown player's way but that is how it's written.

Can the logic be fixed to function that way? I've attached screen shots of his card and the blurb on page 118. 

Thanks
Kenn
![Screenshot 2024-04-25 at 12-40-51 SW_Pathfinder_Core_V1 9 pdf](https://github.com/lipefl/swade-tools/assets/116909768/abf2db19-345f-4bc3-9a1b-0c8a2cc52fad)
![cf](https://github.com/lipefl/swade-tools/assets/116909768/0ccbc91b-fd7c-4d34-b044-2e7454d7d7cb)

**Comment by lipefl** [comment]
Fixed in v1.16.0 (only compatible with Foundry v12 and SWADE system v4)
