### ISSUE TITLE
[ENH] Support flags.swade.wildAttackDamage

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#297]
Since SWADE 3.3 there's a flag for wild attacks to increase the damage to +4:
https://gitlab.com/peginc/swade/-/wikis/Attribute-Keys
_"flags.swade.wildAttackDamage: Replaces the bonus damage from Wild Attack; if you add 4 to this value, Wild Attacks will grant +4 damage instead of +2."_

The AE:
flags.swade.wildAttackDamage add 4
works in the basic system. But when I use SWADE Tools, SWADE Tools is still adding +2 to damage.

Can you add support for the flag in SWADE Tools?

Savage Pathfinder uses it for the Powerful Blow edge and the Fantasy compendium for the Savagery edge (I've written to MetaMorphic and asked them to add the AE to these edges in future releases).

- FVTT 11.315
- SWADE 3.3.11
- SWADE Tools 1.15.2

**Comment by lipefl** [comment]
Added support in v1.16.0 (only compatible with Foundry v12 and SWADE system v4)
