### ISSUE TITLE
Weapons with Reload Type = none does not work with Consumables

### ISSUE THREAD

**Issue by Alligateur** [lipefl/swade-tools#298]
This is basically the same issue as #218, except specifically for an ammo type that is set as a consumable. If there are any shots in the max shot counter (i.e. Shots = x/10), it spits out an "You don't have enough ammunition for this action!" message. The reload button also does not work. If all shots are set to zero (i.e. Shots = 0/0), it will perform actions, but not pull from the set consumable ammo type. Even if you manually fill in the shots counter to not be zero (i.e. Shots = 10/10), it will still give the same error message.

For example, I have a Weapon (gun) that uses "Ammo, Pistol" which is a consumable with 45 Charges. Any weapon with Reload = none does not work with any ammunition set as a consumable.

SWADE system documentation states that reload = none should work for both consumables and gear types of ammunition. If I use a gear item for ammunition, it works as intended. Additionally, when I disable the module, the gun/ammunition works as intended for consumables.

**Comment by lipefl** [comment]
Fixed in v1.16.0 (only compatible with Foundry v12 and SWADE system v4)
