### ISSUE TITLE
Hellfrost Land of Fire has Fast Regeneration Edge/Special Ability

### ISSUE THREAD

**Issue by TheGeolama** [lipefl/swade-tools#30]
in Hellfrost/Land of Fire, there is a Special Ability called Fast Regeneration that among other things adds +2 to remove Shaken that stacks with other Edges/Special Attributes that also add +2  to remove Shaken like Undead or Hardy. I have modified my local copy of the code to handle this for my Land of Fire world but don't know if it could/should be included in the basic SWADE Tools.

**Comment by lipefl** [comment]
For now, i intend to focus on swade core. It'll be hard to cover all settings. 
In the future, i plan to put a customizable area like the "Additional Traits" in swade system to handle this kind of thing.
With that said, if you want to send me your modification, i don't mind putting it in core for now if it would make it easier for you.
