### ISSUE TITLE
SWADE 4.0.2 - Macros in Actions don't work

### ISSUE THREAD

**Issue by richardrhyan** [lipefl/swade-tools#301]
If an Action for a power is clicked, there is no functionality.
I've confirmed it does work when SWADE Tools is not in use.

(I know you haven't worked on this for the new version, just recording this so it doesn't get missed.)

**Comment by lipefl** [comment]
There's no support for v12 or SWADE system 4.0 yet. I don't recommend the update if you want to use SWADE Tools, because some things are not working properly.
I'm already working on the compatibility and i'll check that too, but it might take some time.

**Comment by lipefl** [comment]
Fixed in v1.16.0 (only compatible with Foundry v12 and SWADE system v4)
