### ISSUE TITLE
Problem with gang up and ranged weapon in melee

### ISSUE THREAD

**Issue by Gordfang** [lipefl/swade-tools#302]
Hello! I'm having trouble with the gang up bonus not being present and also with any weapon considered a Ranged Weapon in Melee.

I'm rather new with FoundryVtt so it's totally possible that I simply made mistakes when it comes to configuration somewhere

If you need any other information, I will do my best to get them for you

![image](https://github.com/user-attachments/assets/32f28e3e-9492-490f-b268-a24c2c30dd0d)
In this Screenshot, both character with black border are PJ and friendly token, one of them strike the soldier with its rapier (Found in the SWADE Weapons list) and if I am not mistaken with the rule should get the "gang up" bonus, yet it does not appear and other modifiers appear "Ranged Weapon in Melee, Using Parry" even tho the Rapier should not be a Ranged Weapon

![image](https://github.com/user-attachments/assets/7bea8831-9eb6-4353-9ade-80525ce72606)

**Comment by lipefl** [comment]
I tested here and it's working.
It seems it's not detecting you Fighting skill as melee, so no GangUp.
Check if it's not mispelled (or another language) under SWADE Tools options: 

![image](https://github.com/user-attachments/assets/87b2e513-c605-4546-a94d-dc9c6abe968c)

**Comment by Gordfang** [comment]
Yeah, as I thought it was indeed a configuration problem, switching between languages seems to have fuck up the default name.

After resetting everything to English and it work perfectly! Thanks for the quick reply!
