### ISSUE TITLE
Wound/Fatigue counter not shown

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#304]
Foundry v12.328
SWADE Tools 1.16.0
New world, no other modules active

Wound and Fatigue counters dont show on token. 
Error in console

`Error: Token#toggleEffect is deprecated in favor of Actor#toggleStatusEffect
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at SwadeToken.toggleEffect (foundry.js:61760:19)
    at StatusIcon.js:94:37`

**Comment by lipefl** [comment]
Fixed in v1.16.1.
I had to create an active effect since v12 apparently doesn't accept just the icon anymore. But i think it'll have little to no impact in gameplay.
Thank you!
