### ISSUE TITLE
Error while Wild Attacking when in initiative

### ISSUE THREAD

**Issue by DT357** [lipefl/swade-tools#305]
Hello,

When I have a world with SWADE Tools as the only mod active, wild attacks work fine when an encounter is not active.  I can select it from the attack dropdown on any weapon, and everything works correctly.

However, when encounter mode is active, I receive the following error when trying to wild attack:

"User Cory lacks permission to update Combat [juSv6cs5FDMDYwO8]"

This applies to every user in my game, not just Cory's token.  Wild attacks work perfectly fine for me as a GM while in encounters.

**Comment by lipefl** [comment]
Fixed in v1.16.2
Thanks!
