### ISSUE TITLE
Couple of SWADE Tools macros no longer working

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#306]
Following macros dont work with latest Foundry v12:

Boost/Lower trait
Roll from selected
PC friendly / NPC hostile

Tested on 
Foundry v12 328
SWADE 4.0.3
SWADE Tools 1.16.1
(no additional modules)

All throw error
``You are accessing the SwadeActor "data" field of which was deprecated in v10 and replaced with "system". Continued usage of pre-v10 ".data" paths is no longer supported"

**Comment by lipefl** [comment]
Fixed in v1.16.3
Thanks!
