### ISSUE TITLE
Unable to place templates on the map from the character sheet

### ISSUE THREAD

**Issue by tmtabor** [lipefl/swade-tools#307]
Since updating to Foundry 12 and the latest version of SWADE Tools, I am unable to place templates (blast, cone, etc.) on the map using the buttons next to powers. I get the following error in the console:

```
Uncaught TypeError: canvas.grid.grid.options is undefined (gb.js, line 730)
```

For what it's worth, I am using:

* **Foundry:** 12, Build 328
* **SWADE System:** 4.0.5
* **SWADE Tools:** 1.16.3
* **Browser:** Firefox 128.0.3 (although my players have reported the issue in Chrome as well)

**Comment by lipefl** [comment]
Fixed in v1.16.4
Thanks!
