### ISSUE TITLE
Balistic Protection calculate

### ISSUE THREAD

**Issue by OscarMeFer** [lipefl/swade-tools#308]
Hello! I think the ballistic protection is not calculated automatically.
Toughness calculation
![1](https://github.com/user-attachments/assets/a9fe0c42-5be4-42e4-ad2a-492cf8ab1c30)

Balistic Protection
![2](https://github.com/user-attachments/assets/2c58b683-e072-4d8f-aab8-c14d6cd0f554)

Automatic damage (Not balistic protection calculation)
![3](https://github.com/user-attachments/assets/5d6f1174-1a2c-44cd-85e3-92a4ca26a9b1)

Manual damage penalty (As it should be)
![4](https://github.com/user-attachments/assets/7369dd5b-0f0b-40d5-809c-fac572ac21ed)

_I do not rule out that the one who is wrong with the regulations is me._

**Comment by lipefl** [comment]
As far as i know, there's no configuration to add "ballistic protection" or how to determine if the damage comes from a "bullet" in the system. So yes, it's not automatic and you have to add it mannualy. 
I'll close the issue.  Feel free to re-open if there's a way do determine this info in the system.
