### ISSUE TITLE
Armor Piercing on Actions Not Present in Card

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#309]
Hello,

Noticed this while building some weapons that have increased Armor Piercing in an Action. It rolls damage but I don't see any notation of Armor Piercing being factored in.

![AP_Issue](https://github.com/user-attachments/assets/88a0511a-a063-46cd-b341-66fdc34e48d8)

Hope it's not too hard of a fix. No one has noticed it as of yet, but the one guy using a weapon that increases AP hasn't used actions to do it; he has a couple variations of the same weapon with different stats.

Thanks!

**Comment by lipefl** [comment]
Fixed in v1.16.5
I noticed it was also not taking the new ap into account, fixed that too.
Thank you!
