### ISSUE TITLE
Some other modules incompatibility

### ISSUE THREAD

**Issue by smoothingplane** [lipefl/swade-tools#31]
Hi!
I found some incompatibility with these other modules:
1. Token Action HUD (use system rolls and no SWADE Tools roll , there is an option to choose which "roller" use, but SWADE don't appear)
2. Chat Portrait (SWADE Tools rolls don't have neither image or border like system rolls)
3. Maestro (Item Track don't work with SWADE Tools)
4. Chat BubbleRolls (simply don't work with SWADE Tools)

P.S.
i'm translating SWADE Tools in italian, when i finish, can i send to you the json file for implemented into your project?  and how can I send it to you?

**Comment by lipefl** [comment]
Hi! Thanks, I'll take a look at the modules and see if i can do something to make them compatible, but i can't guarantee (i dont know any of these).
About the translation, sure, no problem. I'll be happy to add :)
You can send it here as a link, merge request or through discord (@lipefl)

**Comment by lipefl** [comment]
Just to let you know, all the modules you listed are now compatible.

**Comment by smoothingplane** [comment]
Thank you!
