### ISSUE TITLE
Categoria de item GEAR puxando a rolagem default

### ISSUE THREAD

**Issue by Diogoarakis** [lipefl/swade-tools#310]
Quando vc aciona a rolagem de alguma GEAR, ele puxa a rolagem default do SWADE

![Imagem do WhatsApp de 2024-08-12 à(s) 15 18 11_bbd769d0](https://github.com/user-attachments/assets/3d273235-06bb-4c1f-9cff-77a27b012990)

**Comment by lipefl** [comment]
Feito!
