### ISSUE TITLE
Distracted and Vulnerable statuses no longer auto-removed after turn

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#311]
Distracted and Vulnerable statuses are no longer auto-removed in combat. Tested multiple rounds and with PC and NPC sheet.
No errors in concole.

Tested in
new world, new actors
Foundry v12 Build 330
SWADE Tools 1.16.4
(no other modules)

Shaken & Stunned are removed correctly.

**Comment by lipefl** [comment]
Fixed in v1.16.5
Thank you!
