### ISSUE TITLE
Damage Through Actions on Macro Bar Not Calculating

### ISSUE THREAD

**Issue by MondoManMike** [lipefl/swade-tools#313]
Getting an error when calculating damage through an Action when clicked on in the macro bar.

![image](https://github.com/user-attachments/assets/ab529822-52a9-43c3-9f62-530d280c508a)

**Comment by lipefl** [comment]
I can't reproduce the problem. Here's a few things to check
- Check if everything is updated to the last version (Foundry, System, Swade Tools)
- Tell me the steps that you do so i can replicate it here
- Check if it happens with all the weapons. If it's only with an specific weapon, please, import it here.

**Comment by MondoManMike** [comment]
I got you:

1. Place two Wildcards down in your scene. I'm using Deadlands assets for this example.
![image](https://github.com/user-attachments/assets/d1b3474c-ffe7-4ca2-809b-913ffd51bc43)
2. Go to the item tab and make a new Action.
![image](https://github.com/user-attachments/assets/6ccc6730-b314-4cc1-b1ad-4ade961800ae)
3. Double click your new action and go to properties. Type in "Fighting" for the trait.
![image](https://github.com/user-attachments/assets/33102e98-d90b-4848-80b7-4026a3c44852)
4. Open the Explorer's character sheet and click on the 'Actions' tab. Then drag and drop the Action in the actions box.
![image](https://github.com/user-attachments/assets/96cb1340-ce3a-4f80-933d-6d8822222d86)
5. Now drag and drop the Action from the character sheet onto your macro bar and close the character sheet.
![image](https://github.com/user-attachments/assets/299c0b90-3171-4e8a-8073-a23fb313c3b6)
6. Select the Huckster as target, click on the macro, and make a fighting roll until you receive a hit or raise. When you click on 'Roll for Damage', that is when it produces the error.
![image](https://github.com/user-attachments/assets/ccba6afb-7650-4f02-9a0e-15fa50c28e86)
![image](https://github.com/user-attachments/assets/58f4fda4-3df6-4b3b-9823-96b7543790da)

Hope this helps.

**Comment by MondoManMike** [comment]
Actually, I may have just figured it out - the reason why there is an error is because an Action does not have anywhere to list a damage value like a weapon does. It does have an initial trait roll though, which is why the first part of the roll works...

**Comment by lipefl** [comment]
There's no support for Actions in Swade Tools yet. The fact that it works as Macro is probably a bug.
But, I'll keep the issue open as a reminder to add support for Actions.

**Comment by lipefl** [comment]
Added support to actions in v1.16.6.
Thanks!
