### ISSUE TITLE
Weapon Actions with additional Trait Modifiers do not work

### ISSUE THREAD

**Issue by Alligateur** [lipefl/swade-tools#314]
When using a weapon with an Rate of Fire 2+ attack, it should have a -2 modifier to the shooting roll. This does not show up or apply to the roll when. Other modifiers such as minimum Strength req or Unskilled attempts calculate correctly. Modified ammo consumption appears to be working correctly as well.

I have double checked that these modifiers are present in the weapon's actions.

Tested on new world with only SWADE Core Rules and SWADE Tools modules active.
![image](https://github.com/user-attachments/assets/a3dc5a23-6ea9-4e66-aa9a-e6e778ffa253)
![image](https://github.com/user-attachments/assets/189f4993-4d60-42a9-8740-9ab7480264d4)

**Comment by lipefl** [comment]
Fixed in v1.16.6. Thanks!
