### ISSUE TITLE
Object Promise

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#316]
Hello,

Getting the following message [object Promise] in the chat card from weapon attacks and powers, but not items sent to the chat w/o a die roll. I saw someone reported it in discord but doesn't look like they followed up. If I turn off SWADE Tools the attack's/power's text from the item appears as it should.

Can you take a look into it?

Thanks!
![image](https://github.com/user-attachments/assets/0e2e9434-e34e-4226-a9bb-262cddcfa0e3)

**Comment by lipefl** [comment]
Sure. Fixed in v1.16.7

**Comment by Neurochimp** [comment]
Thank you!
