### ISSUE TITLE
Ammo not being used when making a roll using Swade Tools

### ISSUE THREAD

**Issue by Fiddoodle** [lipefl/swade-tools#317]
When using the swade tools dialogue box the ammo loaded in the weapon does not tick down. I have confirmed that it does tick down when clicking the button found on the character sheet. Screenshot included for clarity.

![image](https://github.com/user-attachments/assets/89a562ef-c417-4df7-b114-71a955a28627)

**Comment by lipefl** [comment]
Fixed in v1.16.8
Thanks!
