### ISSUE TITLE
Token NPC not linked don't work with "Ammunition Management"

### ISSUE THREAD

**Issue by smoothingplane** [lipefl/swade-tools#32]
The NPC tokens not connected to the sheet, when they try to reload their weapon, receive the message "The weapon is already fully loaded" (probably because the NPC sheet is already loaded) and do not make the roll, when I use SWADE Tools (otherwise works as expected).
Did I do something wrong or is it a bug?

**Comment by lipefl** [comment]
It seems a bug with the "Reload" button in  the chat. I'll check. The reload button at weapon dialog seems fine, you can use that one until the fix.

**Comment by lipefl** [comment]
Fixed in v1.2.9, please update. Thanks!
