### ISSUE TITLE
Chat text

### ISSUE THREAD

**Issue by smoothingplane** [lipefl/swade-tools#34]
Sorry bothering you, it's me again,
but the text of the chat cards, has no paragraphs, and ends up sticking together as in the image, but after a chat refresh (restart of foundry or a change of setting) the formatting of the text is corrected.
![image](https://user-images.githubusercontent.com/43862671/109016509-899faa80-76b6-11eb-8164-ca3dc9b2e801.png)

**Comment by smoothingplane** [comment]
ok is a problem that appears only when bubblerolls is also activated

**Comment by lipefl** [comment]
Yes, i noticed that too... It's something Bubblerolls do. They remove spaces, divs and commas. I can't fix it without making it problematic for other players (or changing the swade system, since the skill roll comes directly from swade function). You should check with them.
