### ISSUE TITLE
Feature request: support for Gritty Damage settings rule

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#37]
Would it be possible to add option to automaticly roll from Injury table (user created, rolltable picker) when Wound is applied to actor, and append (or just create new chat message) the result to chat?
This ofc should be toggleable from module settings.

**Comment by lipefl** [comment]
Yes, and it's a nice idea. Thanks!

**Comment by lipefl** [comment]
There's now an option in settings rules to add Gritty Damage rolltable
