### ISSUE TITLE
Roll initiative on Joker the next round doesn't roll.

### ISSUE THREAD

**Issue by grendel111111** [lipefl/swade-tools#40]
When SWADE tools rolls initiative, if it gets a joker it kicks in jokers wild. But at the start of the next turn it doesn't roll initiative automatically. It also stops doing the checking and removing of conditions. Once the round has completed it goes back to checking, rolling for and removing conditions. I tried it on 2 worlds with the same results.

**Comment by lipefl** [comment]
Are you using with swade system v0.17 ?

**Comment by grendel111111** [comment]
I am using 17.2. It happens even if Jokers wild is turned off and the SWADE jokers wild is running it instead. (Also don't remove jokers wild yet. The one on SWADE is only giving Bennies for the PC's not for when the GM should get it for NPC's get a joker.)

**Comment by grendel111111** [comment]
Round 11 the elemental gets a joker.
![image](https://user-images.githubusercontent.com/80164119/110233277-f68c2d80-7f5d-11eb-9354-2fda79f6c32f.png)
The next round (12):
It does not draw:
![image](https://user-images.githubusercontent.com/80164119/110233298-1a4f7380-7f5e-11eb-93d0-2cd70b422927.png)
when it gets to the wolfs turn it does not roll to unstun. (Still round 12)
![image](https://user-images.githubusercontent.com/80164119/110233324-36531500-7f5e-11eb-9cbe-f7129ad9951e.png)
On round 13 it gives cards again and rolls to unstun the wolf.
![image](https://user-images.githubusercontent.com/80164119/110233420-e294fb80-7f5e-11eb-8399-64cb1b719b0b.png)

**Comment by lipefl** [comment]
Thanks for the screenshots. I ran some tests and it seems like the problem occurs when the deck resets. If you keep pressing next when there's no initiative, it'll be back to normal when it reaches the next round.
I am aware of the joker not fully working in swade system, but i am not sure if i can keep the funcionality in Swade Tools, since i'll have to change a lot of code. I'll try anyway.

**Comment by grendel111111** [comment]
You can  turn off jokers wild in the core too. So I have the core jokers wild and tools JW running instead. You can just use the jump to next round, but it means you can't use timed effects based on rounds passed.

**Comment by lipefl** [comment]
Fixed in v1.3.0
For now, Joker's Wild is still an option in Swade Tools (auto-disabling system setting, as suggested).
