### ISSUE TITLE
damage on vehicles

### ISSUE THREAD

**Issue by Diogoarakis** [lipefl/swade-tools#42]
when attacking a vehicle, when I roll the damage, it does not calculate its resistance / armor

![dano tanque](https://user-images.githubusercontent.com/13071505/110542016-4c500980-8107-11eb-91fc-f43f8a584332.jpg)

**Comment by lipefl** [comment]
Pode escrever em português da próxima :)

**Comment by Diogoarakis** [comment]
a gente segue o fluxo!

**Comment by lipefl** [comment]
Corrigido. E tbm checa Fora de Controle, e rola automático na tabela em caso de falha (se estiver configurado)
