### ISSUE TITLE
Error on Rolls from Inventory

### ISSUE THREAD

**Issue by Stray-Sojourner** [lipefl/swade-tools#43]
![unknown](https://user-images.githubusercontent.com/80721191/111224106-629d1000-85b4-11eb-9817-dc5ceb56f959.png)

**Comment by Stray-Sojourner** [comment]
None of the offered buttons work, all ending in displayed error message.

**Comment by lipefl** [comment]
I suspect you're using an incompatible version. Can you check Swade system and Swade Tools versions?

**Comment by Stray-Sojourner** [comment]
Tools is 1.3.1 and Swade system is 0.14.1

**Comment by Stray-Sojourner** [comment]
I updated the SWADE sys, seems to be working fine, sorry for the hassle
