### ISSUE TITLE
Weapon dialog gives "Error: This is not a registered game setting"

### ISSUE THREAD

**Issue by steveculshaw** [lipefl/swade-tools#46]
On the character sheet, I can select a token, and click on the "Fighting" skill in the "Summary" tab, get a dialog "Fighting Skill Test", and click "Roll", and it works

Similarly on the "Inventory" tab, I can click on a weapons "Damage", get the weapons "Damage" dialog, and click on either "Roll" or "Roll Raise", and they work

But if I click on the weapons name, get the weapon dialog, when I click on either the "Fighting" or "Damage" buttons, I get an error alert ... **"Error: This is not a registered game setting"**

![image](https://user-images.githubusercontent.com/64320/113471815-e2e9bf00-9456-11eb-9272-43d319e8ec95.png)

**Comment by lipefl** [comment]
I suspect you're using an incompatible version. Can you check if your system or module is updated?

**Comment by steveculshaw** [comment]
Thanks for the response

Checked on my PC ...

I've got Foundry v0.7.9, with various modules; specifically I had Savage Worlds Adventure Edition Core Rules v1.0.4, and SWADE Tools **v1.2.11**

Now updated SWADE Tools to **v1.3.2**

Re-checked the various options on the character sheet, and still getting the error :-(

Are there other modules that can cause the problem ?

**Comment by lipefl** [comment]
Have you checked your system? Check if swade is v0.17.2

**Comment by steveculshaw** [comment]
Argh ... sorry, still getting to grips with Foundry and where things are !

Yeap, my game system "Savage Worlds Adventure Edition" was only v0.15.3 :-(   ...it's now v0.17.2 !

That's better :-)

Now on the "Traits / Skills" tab ...
![image](https://user-images.githubusercontent.com/64320/113484323-a098a000-949f-11eb-9d91-33ea49f35d52.png)

I get a dialog for rolling the "Fighting Skill Test" ...
![image](https://user-images.githubusercontent.com/64320/113484686-8790ee80-94a1-11eb-8446-f762a258a889.png)

Then on the "Gear" tab (no longer Inventory!) ...
![image](https://user-images.githubusercontent.com/64320/113485420-44387f00-94a5-11eb-8e62-8ad7eb186eeb.png)

I get a "Weapon" dialog ...
![image](https://user-images.githubusercontent.com/64320/113485474-94174600-94a5-11eb-863b-59f34f9ff57a.png)

And a "Weapons Damage" dialog ...
![image](https://user-images.githubusercontent.com/64320/113485533-e5273a00-94a5-11eb-823d-45372f214f22.png)

So if I've selected my token, and targeted a monster, I get e.g. a Raise, and lots of damage, which calculates the Shake & Wounds
![image](https://user-images.githubusercontent.com/64320/113485556-0425cc00-94a6-11eb-8916-72a9b9d50a3d.png)

Final point ... WOW, this makes my GM life so much easier, and combats should flow a lot better 

**Many, many thanks for the development !!!!**
