### ISSUE TITLE
Thrown weapons use ammo in close combat.

### ISSUE THREAD

**Issue by grendel111111** [lipefl/swade-tools#47]
When using a thrown weapon in close combat I set up an action for use Strength, 0 shots, but when I roll to attack it still removes 1 shot. If I roll it through the core system it doesn't remove a shot for close combat.
![image](https://user-images.githubusercontent.com/80164119/113472576-dedd9180-9496-11eb-9316-ceca23c1c810.png)

**Comment by lipefl** [comment]
Fixed in 1.3.3. Thanks!
