### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Dorifer** [lipefl/swade-tools#49]
I would like to help out with a German translation for SWADE tools (there already is a German version of the SWADE rules which I own).

**Comment by lipefl** [comment]
Hi @Dorifer , you need to get one of the files inside "lang" folder, let's say "en.json" and translate the terms. Then send me back with the code for your language. You can attach your file in the comments here. If you need any help, you can ask me here or use the foundry discord.

**Comment by Dorifer** [comment]
Here you go!

[de.json.txt](https://github.com/lipefl/swade-tools/files/6298453/de.json.txt)

**Comment by lipefl** [comment]
Added in v1.3.4.
Thanks!
