### ISSUE TITLE
Descrição do item/poder na rolagem

### ISSUE THREAD

**Issue by Diogoarakis** [lipefl/swade-tools#50]
Gostaria de saber se é possível fazer, assim como na rolagem default do sistema, que apareça a descrição cl do item/poder na rolagem.
default
![default](https://user-images.githubusercontent.com/13071505/114324542-0b318780-9b01-11eb-8103-391b9a2c141b.jpg)
![default](https://user-images.githubusercontent.com/13071505/114324615-78451d00-9b01-11eb-8328-09640fb45f9a.jpg)

SWADE Tools
![sistema](https://user-images.githubusercontent.com/13071505/114324549-17b5e000-9b01-11eb-97a7-92ea8a55eea8.jpg)

**Comment by lipefl** [comment]
Acredito que é possível sim. Está na lista para ser feito :)

**Comment by lipefl** [comment]
Feito, já deixei como padrão (v1.3.4)

**Comment by Diogoarakis** [comment]
@lipefl so to postando aqui pq é uma dúvida. O mod "The Furnace" tem uma opção em que ele puxa macros se um comando aparecer no chat - {{macro "nome da macro"}}. 
Quanto testei, vi que sem o SWADE tools funcionava, e eu achei q era pq tinha essa opção de jogar a descrição do item/poder no chat.
Mas agora que temos essa função, o "The Furnace" ainda não executa a macro, mesmo com o comando aparecendo no chat. O que vc acha que pode ser?

**Comment by lipefl** [comment]
@Diogoarakis não sei te ajudar. Seria melhor verificar com o autor do Furnace.

**Comment by lipefl** [comment]
Se no swade padrão funciona, eu posso ate tentar verificar o q pode ser. Mas não tenho como garantir. Quem vai saber responder com certeza é o autor do módulo.

**Comment by Diogoarakis** [comment]
sim, se vc não achar nada muito obvio, eu falo com o pessoal do Furnace, desculpa o incomodo!

**Comment by lipefl** [comment]
@Diogoarakis q isso, não é incomodo. Não consegui nem testar o q vc falou. Tenho o Furnace instalado, mas comigo não funciona nem sem o Swade Tools. Talvez esteja fazendo algo errado. Se puder me dar um exemplo mais elaborado...

**Comment by Diogoarakis** [comment]
Vou tentar.
O Furnace permite executar uma macro qualquer quando o comando {{macro "nome da macro"}} (tem que ter espaço) aparece no chat.
Isso permite algumas paradas interessantes, como rodar animações quando se usa um ataque ou magia, ou mesmo algum efeito visual, etc.
Quando eu digito no chat o tal comando, roda a macro. Quando eu uso o item sem o SWADE Tools, funciona o comando. Com o SWADE ativo, o Furnace não reconhece o comando. Vou ver se gravo um video.

**Comment by lipefl** [comment]
![image](https://user-images.githubusercontent.com/10639148/115121791-f9c9fe80-9f8a-11eb-99b6-41496c1ce63d.png)

Tentei e fica assim sem o Swade Tools (o The Furnace está ativado)

**Comment by Diogoarakis** [comment]
https://youtu.be/fVxvPAd9hn4

Da uma olhada, pfv

**Comment by lipefl** [comment]
@Diogoarakis vendo vídeo consegui entender e testar.  A única diferença q eu consigo ver é que sem o Swade Tools, o que vai pro chat é uma mensagem comum (como se vc tivesse digitado "bla bla bla" no chat). E com o Swade Tools já é direto a rolagem (como se vc tivesse digitado /r d10 no chat). O que eu fiz, foi colocar os dados da arma no "flavor" da rolagem. Não sei se é isso, mas pode ser que o Furnace ignore quando é rolagem, mas não há nada que eu possa fazer do meu lado pra resolver. Se você verificar no Furnace e eu puder fazer algo, só falar, mas de cara assim, não vejo como resolver, pq não tenho ideia de como esse gatilho funciona.

**Comment by Diogoarakis** [comment]
vou no git do Furnace. Se houver uma resposta, te atualizo só por curiosidade. Obrigado pela atenção!
