### ISSUE TITLE
Blast applied same damage to all targets

### ISSUE THREAD

**Issue by steveculshaw** [lipefl/swade-tools#52]
### Environment Details

- Foundry VTT Version: 0.7.9
- Operating System: Windows
- How Are You Using Foundry: both Native Application (Electron) and Edge
- Modules Enabled?: yes
   SWADE Core Rules v1.0.4
   SWADE Tools v1.3.5
   Easy Target v2.10

### Issue Description

Using the Blast Damage button with two targets selected. Clicking Damage roll one set of dice (in this case 2d6) and applies the same damage to ALL targets. 

### Relevant logs and/or screenshots

<img width="214" alt="fvtt-blast-damage" src="https://user-images.githubusercontent.com/64320/117880431-072f8b80-b2a0-11eb-9191-662aac7a49da.png">

### Possible Solution and/or Root Cause

N/A

**Comment by lipefl** [comment]
Sorry. I don't get what the issue is. That's how it's supposed to work.

**Comment by steveculshaw** [comment]
Hmm ... 

On page 97, it says ... _"If the effect causes damage, roll for each victim separately"_

I questioned the single damage roll on the PEG forum, because I was running a combat, and the roll result was very high, so we were looking at a TPK  :-(

![image](https://user-images.githubusercontent.com/64320/117993917-0d714680-b338-11eb-82a9-180052eed7d2.png)

**Comment by lipefl** [comment]
I see. In these cases, you can mark the targets and choose "Spellcasting" first, it'll show all the targets, then you can roll damage separately for each of them, clicking on them. Like this:

![image](https://user-images.githubusercontent.com/10639148/118014467-a5b3ff00-b329-11eb-9cab-93d5033841ca.png)

**Comment by steveculshaw** [comment]
Ah ha ... ta

Key thing I was missing ... I didn't know you had to set the Trait in the powers Actions & Effects
Once I set it to Faith, the button changed from Unskilled to Faith
