### ISSUE TITLE
Strength modifier not included in damage rolls

### ISSUE THREAD

**Issue by Chris-Sturgess** [lipefl/swade-tools#53]
### Environment Details
Foundry VTT Version: 0.7.9
Operating System: OSX
How Are You Using Foundry: Chrome
Modules Enabled?: yes
SWADE Tools v1.3.5

### Issue Description
When rolling a damage formula for a weapon that uses "@str", the strength modifier is ignored.

### Relevant logs and/or screenshots
![Screen Shot 2021-05-12 at 1 48 06 PM](https://user-images.githubusercontent.com/1301316/118021005-c62f8980-b328-11eb-963f-fa82620374ab.png)
The first entry is a roll from the character sheet using only the SWADE system (no modules).
The second entry is a roll from the character sheet using the card generated by SWADE tools.
In both cases, the same weapon is used with a damage value of "@str+d4"

### Possible Solution and/or Root Cause
It looks like the damage formula is just taking the strength die value, and not the strength modifier.
Likely caused right [here](https://github.com/lipefl/swade-tools/blob/74065ca67026009b9300b894539590a753042c0c/scripts/class/CharRoll.js#L417) where it replaces strength with a die, but not the additional modifier.

**Comment by lipefl** [comment]
Fixed in 1.3.6. Thanks for the directions :)
