### ISSUE TITLE
Feature Request: automatic range penalties

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#54]
Would be really cool to have option for autocalculating range penalties (and switching TN4 to Parry for targets in range  <1 inch) for ranged attacks.
(Better Rolls2 does this since v2.26)

**Comment by Alis-72** [comment]
I misunderstood how BR2 does this. So discard this request.

**Comment by lipefl** [comment]
Hi @Alis-72 sorry for the delay. This is something I intend to add to swade tools in the future. Out of curiosity, how does br2 do this?

**Comment by Alis-72** [comment]
I actually don't have a clue how it is done. Might be done by comparing token location coordinates, though there is also Rangefinder module that shows distance from token to mousepointer so it might also have some ideas how it's done (or maybe Javier would share his secrets?)
(Sorry for being little use, I cannot code and only barely read basic code)

**Comment by Alis-72** [comment]
reopened this (closed a bit too fast ^^ )

**Comment by lipefl** [comment]
Thanks anyway. I already have some directions on how to do this.

**Comment by lipefl** [comment]
Available now in v1.5
