### ISSUE TITLE
Ações extras

### ISSUE THREAD

**Issue by Diogoarakis** [lipefl/swade-tools#55]
Boa noite,

Teria a possibilidade de "puxar" as ações extras dos itens e poderes direto do chat? vou postar as imagens para ver se me faço entender
![Captura de tela 2021-05-19 233408](https://user-images.githubusercontent.com/13071505/118910477-e51ab680-b8fa-11eb-97df-e420eee28f38.jpg)
![Captura de tela 2021-05-19 233438](https://user-images.githubusercontent.com/13071505/118910479-e5b34d00-b8fa-11eb-901e-84f962f23349.jpg)

**Comment by lipefl** [comment]
Entendi. Mas preciso pensar melhor em como implementar de forma simples Se tiver alguma sugestão...

**Comment by Diogoarakis** [comment]
eu pensei e tenho medo de virar um "better rolls 2.1" muito poluido

acho eu, mas ai seria uma mudança pro sistema, que a "ação extra" deveria ser uma rolagem completa, verificação de pericia e rolagem de dano. Pq ai não teria esse problema, vc declara a ação, rola o acerto, rola o dano.

Isso seria um possível para o SWADE tools? se não, sera que um "botão", num sistema similar a descrição do item que vc implementou, com mais opções de rolagem , nao funcionaria sem poluir muito? se não me fiz claro, posso gravar um video ou podemos trocar uma ideia no discord, sei la

**Comment by lipefl** [comment]
Entendo o que diz. Mas modificação do sistema precisa vir do desenvolvedor do swade. Vou pensar numa solução.

**Comment by Diogoarakis** [comment]
Outra ideia que tive seria ter uma opção extra abaixo da aplicação de dano. Fiz uma montagem rudimentar
![001](https://user-images.githubusercontent.com/13071505/119414856-c6d00480-bcc6-11eb-8877-ba597a12fa5e.png)

Ai vc tem essas 2 opções, aplicar o dano ou puxar mais opções de dano
Na rolagem defaut é discriminado o que é "trait" e o que é "damage", se possivel, a opção de "Ações Extras" puxaria aquela janela de ações da arma, mas apenas com as opções de Dano, similar a imagem
![002](https://user-images.githubusercontent.com/13071505/119415103-507fd200-bcc7-11eb-988e-45157d5523ab.jpg)

Caso não de para discriminar, puxaria a janela toda
![002](https://user-images.githubusercontent.com/13071505/119415168-72795480-bcc7-11eb-8579-bc19e296d794.jpg)

**Comment by lipefl** [comment]
Minha ideia é algo proximo do seu ultimo print.

**Comment by lipefl** [comment]
Adicionei um campo pra mudar o dano antes de rolar (vc consegue testar em itens quando tem mais de um dano, só aparece pra esses)
