### ISSUE TITLE
Armas Veículares (Macro)

### ISSUE THREAD

**Issue by Diogoarakis** [lipefl/swade-tools#56]
Foundry 0.8.6
Savage Worlds 0.19.4

Não consigo rolar as armas veiculares, toda vez aparece a seguinte mensagem
![erro](https://user-images.githubusercontent.com/13071505/121827169-67e02880-cc91-11eb-8fb2-052a05b2dd74.jpg)

**Comment by lipefl** [comment]
Corrigido na v1.4.0 (possível ter q atualizar pra Foundry v0.8.7, não testei na 0.8.6)

**Comment by JusticeTheAwesome** [comment]
Olá. Tenho o mesmo problema agora e estou usando a versão 0.8.9 do Foundry e a versão 0.21.4 do SWADE.

As armas veiculares não parecem funcionar quando seleciono um alvo. E a mesma mensagem aparece "Cannot read property 'value' of undefined"

**Comment by JusticeTheAwesome** [comment]
Eu atualizo. Não parece funcionar com a ação de tiro, mas quando faço a rolagem de dano funciona.

Não parece reconhecer a jogada de ataque.

Desculpe meu português ruim. Não é meu idioma principal

**Comment by lipefl** [comment]
Testei e está funcionando normalmente. Se puder passar um print do console ou mais detalhes, talvez seja alguma configuração. 
Se preferir, podemos falar em inglês.

**Comment by JusticeTheAwesome** [comment]
![image](https://user-images.githubusercontent.com/91155212/144104966-71117074-440d-4d27-81dd-c9bb95e8a9f7.png)

**Comment by lipefl** [comment]
Provavelmente algo com a Macro. Tente rolar clicando diretamente na arma, dentro da ficha do veículo. Irei verificar e corrigir a macro.

**Comment by JusticeTheAwesome** [comment]
Acabei de tentar usar a arma de comando dentro da folha do veículo. Aparentemente, ele não reconhece o sistema de apontamento necessário para ativar a macro.

Parece que estamos prestes a descobrir

**Comment by JusticeTheAwesome** [comment]
Talvez isso ajude:

![image](https://user-images.githubusercontent.com/91155212/144134486-2f57399f-5125-47c8-8553-0928a3043f23.png)
![image](https://user-images.githubusercontent.com/91155212/144134521-7cc41ed2-c7b0-4d67-9511-b641fd23cd9e.png)
![image](https://user-images.githubusercontent.com/91155212/144134553-afb6d39f-cee6-40e2-8eac-1eaebbe7c8cc.png)

**Comment by lipefl** [comment]
Obrigado! Descobri o problema. O que está acontecendo é que para medir a distância o módulo está tentando encontrar o operador do veículo e não o token do veículo em si. Provavelmente o token do operador não está no mapa e dá esse erro. 
O que eu aconselho, até eu conseguir resolver, é colocar também o token do operador junto do veículo, no mapa, assim não ocorrem erros e a distância medida é a correta.

**Comment by JusticeTheAwesome** [comment]
Obrigado pela sua dedicação. Infelizmente eu tentei e não parece funcionar assim também. :(

**Comment by lipefl** [comment]
Eu farei uma correção nos próximos dias e aviso aqui. Caso continue acontecendo após essa atualização, tentamos ver o que pode ser.

**Comment by lipefl** [comment]
Atualização para v1.6 disponível
Verifique se resolveu o problema, caso contrário reabra aqui com os detalhes.
