### ISSUE TITLE
Atirar à queima roupa

### ISSUE THREAD

**Issue by Diogoarakis** [lipefl/swade-tools#57]
Seria muito bom se pudéssemos ter a opção de atirar contra o aparar do adversário para emularmos a condição de atirar à queima roupa

**Comment by lipefl** [comment]
Acredito que isso virá junto quando inserir cálculo de distância, agrupar e tal. No momento, eu não to conseguindo fazer atualizações no módulo. Mas vou deixar aqui pra quando puder.

**Comment by lipefl** [comment]
Feito na v1.5
