### ISSUE TITLE
'Disable Joker's Wild' does the opposite

### ISSUE THREAD

**Issue by TheBiggerBadderWolf** [lipefl/swade-tools#59]
The 'Disable Joker's Wild' in SWADE Tools seems to do the opposite of how it reads. That is:
_Jokers Wild_ **On** in System Settings and _Disable Jokers Wild_ **Off** in Module Settings -> _Jokers Wild_ turns off.
_Jokers Wild_ **On** in System Settings and _Disable Jokers Wild_ **On** in Module Settings -> _Jokers Wild_ stays on.

To reproduce:
1. **Tick** _Jokers Wild_ in _System Settings -> Settings Configuration_ 
2. **Untick** _Disable Jokers Wild_ in _Module Settings -> SWADE Tools_ 
3. Reboot foundryvtt

**Observed Behaviour**: Go to _System Settings -> Settings Configuration_  and see that _Joker's Wild_ is now unticked.
**Expected Behaviour:** Joker's Wild remains ticked when Disable Jokers Wild is unticked.

This is running on Forge with the latest version of Foundry (0.8.8) and SWADE (0.20.4).

e: I've just seen this in the last release notes: _Auto Disabling Jokers Wild setting on swade system for now, can be enabled if you Disable Jokers Wild in Swade Tools (it'll probably be removed from Swade Tools once the swade system is fully working with NPCs)_ , it still feels like the behaviour is the opposite of what I'd expect though!

**Comment by lipefl** [comment]
This is intended. These are two different Jokers Wild configurations, swade system and swade tools. If you want to use Jokers Wild in swade tools (disable jokers wild unticked), it'll disable swade system jokers wild to prevent both running at the same time (you'll see a blue warning for this, there's also an info in the option description).
Anyway, the intention is to remove jokers wild in swade tools, i'll check if swade system is fully working (it wasn't working for npcs, so i let it as an option).

**Comment by TheBiggerBadderWolf** [comment]
Understood, thanks for the clarification! I'll close this issue :)
