### ISSUE TITLE
Hit message with failed powers

### ISSUE THREAD

**Issue by parvusdomus** [lipefl/swade-tools#6]
When you roll, and fail, a power, you get the 1PP spent message (that's ok) but you are also getting a green "HIT" button to roll damage.

**Comment by lipefl** [comment]
i tried and i dont see this happening. It still shows "miss" for me. Can you send me a screenshot or elaborate more?

**Comment by parvusdomus** [comment]
Sure, here you are:
![failed_power](https://user-images.githubusercontent.com/71666845/103582095-7bff4d00-4edd-11eb-96fe-717f296a114d.png)

I think I understand what happens. The objective has the vulnerable condition. So it at the same time fails with a 3 and hits, because of the vulnerable condition. Showing both messages (fails spending only 1 pp, and gives the option to apply damage).
If the objective doesn't have the condition on, it works properly.

**Comment by lipefl** [comment]
I see... I will find a way to solve this. Thanks.
