### ISSUE TITLE
Enhancement Request: Automatically Include Scale Modifier 

### ISSUE THREAD

**Issue by TheBiggerBadderWolf** [lipefl/swade-tools#62]
Hello again!

Would it be possible to have the Scale Modifier automatically calculated into attack rolls?

That is: if a creature with Scale Modifier -2 is being attacked by a creature  with Scale Modifier 0 (size -1 to 3), a -2 is automatically applied to the attack roll. Likewise, a +2 is added if the attack goes the other way.

No problem at all if not, very much appreciate all the work you do.

**Comment by lipefl** [comment]
Yes. Nice idea :)

**Comment by lipefl** [comment]
Available in v1.6.0
