### ISSUE TITLE
Request: Range penalty to dieroll total

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#63]
New automatic range penalty calculation is a bit confusing as the penalty is not calculated on roll but only on total,
 i.e. if shooting something in medium range and dieroll comes up as 5 it shows green 5 on chatcard but says 'miss' and only by  clicking questionmark one sees what penalty was from range.

In comparison Distracted mod is shown above dierolls and calculated to total roll.

Having both/all penalties listed on top and calculated straight to total would be more intuitive.
![Näyttökuva 2021-09-12 001522](https://user-images.githubusercontent.com/75221971/132961790-c75ebb96-f8cf-4466-a4ad-62c7bdc1be0b.png)

**Comment by lipefl** [comment]
The thing is your request will not work for all cases. Like using CdT, Frenzy or if you have accidentaly selected more than 1 target.
Distracted is not target dependant, and will apply to every target, that's why it's on top.

**Comment by Alis-72** [comment]
You are correct. I didn't thin it through :)
I'll close this ticket now.

**Comment by TheBiggerBadderWolf** [comment]
Coming back to this issue, one slight change that I think would help: have the '?' that you need to click on to be automatically expanded. This means you'll see penalties for range (and size maybe if added in the future) straightaway:

![range](https://user-images.githubusercontent.com/76487459/134812472-0035eaea-be49-40ec-a189-045c632ea282.png)

**Comment by lipefl** [comment]
No problem, it could be an option.

**Comment by lipefl** [comment]
Option added in v1.5.3
