### ISSUE TITLE
Token Status icons linking not working if Active Effects on sheet

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#64]
Token statuses do not show on token if actor has Active Effects on sheet.
Does not matter if Active Effects do anything nor if they are ON or OFF.
Deleting effect from sheet restores functionality.
(Just noticed when playing with Pathfinder Premium Content, which has races and classes done as active effects)

**Comment by lipefl** [comment]
Fixed in v1.5.1
Thanks!
