### ISSUE TITLE
Active Effects are Breaking Wound's Appearing on Token

### ISSUE THREAD

**Issue by Cosmic-Lattee** [lipefl/swade-tools#65]
So when there is a active effect on a token it prevents the wound numbers from appearing on the token.

**Comment by Cosmic-Lattee** [comment]
Here is a gif to show what is happening.
![Example](https://user-images.githubusercontent.com/24766235/134004826-23e18780-c924-4723-b7b5-d6e6cb63e95e.gif)

I am getting two console errors one seems to be directly related to the problem:
![image](https://user-images.githubusercontent.com/24766235/134005319-baf95dc8-6c0c-4dea-91e0-b3235795ce4f.png)

The other happens when Active Effects are deleted on the token so it might indicate there is something going on with the SWADE itself. This is that error:

![image](https://user-images.githubusercontent.com/24766235/134005430-a2a548a1-5d3c-4b5c-b97b-e35159e0d097.png)

Happens on both character and npc sheets. Tested in a clean game with only Swade Tools going. Making the active effect do something rather than just being blank doesn't change anything.

Versions
Foundry: 0.8.9
SWADE: 0.20.4
Tools: 1.5.1

**Comment by lipefl** [comment]
fixed in v1.5.2
Thanks for the info
