### ISSUE TITLE
Shaken condition not being removed with successful Spirit roll

### ISSUE THREAD

**Issue by architech99** [lipefl/swade-tools#66]
The automatic roll to un-shake is successful but the Shaken condition is not removed/unchecked from the actor.
The automatic roll to un-shake is unsuccessful but the Shaken condition is not removed/unchecked from the actor when choosing the "Remove Shaken with a Benny" option on the Chat card.

SWADE: 0.20.4
SWADE Tools: 1.5.1

**Comment by Cosmic-Lattee** [comment]
I can confirm this is happening as well. There are no errors in the console when this happens.

**Comment by lipefl** [comment]
fixed in v1.5.2
