### ISSUE TITLE
Enhancement Request: Allow changing the word 'recharged'

### ISSUE THREAD

**Issue by TheBiggerBadderWolf** [lipefl/swade-tools#68]
The most minor of minor requests :)

Could you please make it possible to change the word 'recharged' when a character performs a reload action? I'd like it to say 'reloaded' (for my Deadlands campaign).

![recharged](https://user-images.githubusercontent.com/76487459/134769183-3718e7f1-095d-44ff-b945-49836419bc8b.png)

If this isn't possible, or is more work than it's worth, please don't hesitate to close the ticket. Thanks again!

**Comment by lipefl** [comment]
I think "reloaded" is better anyway more in line with the system, the button, etc. I'll just fix the translation. It'll be available in the next update.
