### ISSUE TITLE
One bullet reloading

### ISSUE THREAD

**Issue by Ksen01** [lipefl/swade-tools#69]
Hello,
Can you make an option to reload one round for weapons like revolvers and rifles from Deadlands?
Otherwise it make bullets automatization worthless for this setting.
Your module is awesome but this problem bugging me and I really don't want to remove it from the list. I would be very grateful if we can find some solution.

**Comment by TheBiggerBadderWolf** [comment]
Aye a 'reload all' or 'reload 1' would be great.

Int he meantime, I know it's not perfect, but you can edit the weapon and manually change the number of rounds of ammunition in it.

**Comment by lipefl** [comment]
It's already in plan. The idea of 2 buttons is even better. It'll be an option, since it's not for every setting.

**Comment by Ksen01** [comment]
Thank you for fast responce, I will eagerly await the introduction of the feature.

**Comment by lipefl** [comment]
Available in v1.6.0
