### ISSUE TITLE
REQUEST: Disable automatic Unshaken and Unstunned rolls

### ISSUE THREAD

**Issue by SalmonRain** [lipefl/swade-tools#70]
My party and I are allergic to automatic rolling, which I think is only on unshaking and unstunning.

A toggle for this feature would be nice. Alternatively no automation but instead a button in chat to attempt to unshake/unstun and then proceed as usual would be even better.

Thank you for your time and the amazing tool.

**Comment by lipefl** [comment]
I can put a toggle to combat automation, but it'll disable all the start turn/end turn events (like removing distracted, for example). The "semi-automation" can be tricky to implement.

**Comment by lipefl** [comment]
Available in v1.6.0
