### ISSUE TITLE
ISSUE: Range penalty calculation wrong on maps with scale

### ISSUE THREAD

**Issue by SalmonRain** [lipefl/swade-tools#71]
On a gridless map with a non-1 scale the range penalties weren't coming out right. Looking at RollControl.js I don't see the scale (scene.dimensions.distance) being used anywhere. This changed fixed it locally for me. Line 572:

            if (item.data.data.range.includes('/')){
                let distances=item.data.data.range.split('/')
                let distancemod=0;
                let toofar=false;
                let extreme='';
                let i=1;
		let scale = canvas.dimensions.distance //fetching distance scale
              //console.log(targetRange);
              distances.forEach(dist=>{
                  dist=gb.realInt(dist);
                  if (dist>0 && targetRange*scale>Math.abs(dist)){    //applying distance scale to targetRange so it matches the range measured

**Comment by lipefl** [comment]
Thanks for the code. I'll look into it.

**Comment by lipefl** [comment]
Fixed in 1.5.3
