### ISSUE TITLE
Gang Up Bonus Weirdness

### ISSUE THREAD

**Issue by Cosmic-Lattee** [lipefl/swade-tools#72]
So we are having some strange things happen with gang up bonus:

![image](https://user-images.githubusercontent.com/24766235/136587711-062b662a-e220-4eb5-82fc-f25515e3f25f.png)

Green are Friendly PC's sheet
Blue are Friendly NPCs sheet
Red are Enemy NPCs sheet

Unless I am mistaken the selected green guy should have a +3 gang up bonus. What is interesting is that a logged in player can see the gang up bonus correctly, here is a screen shot from their screen:

![image](https://user-images.githubusercontent.com/24766235/136587985-aa06f04b-ff62-421e-8cc5-52dc9d9d9da9.png)

This was tested with a fresh game with the following modules/systems:

![image](https://user-images.githubusercontent.com/24766235/136589467-8a971df2-d306-4dfb-9d89-50b9b221e1de.png)

There is also some strangness where if I do a copy and paste of the players token it gives the +1 gang up as seen here:
![image](https://user-images.githubusercontent.com/24766235/136589062-3b0f3df0-1535-4e5a-9c15-37a79fe5b8a9.png)

but if I use four different player sheets the +3 gang up bonus is showing correctly

![image](https://user-images.githubusercontent.com/24766235/136589145-2ce5f2ca-d80e-4d9c-aaff-6df550acb005.png)

**Comment by lipefl** [comment]
Fixed in v1.5.3
This bug was happening because of using the same pc as "copies", they're now ignored.
