### ISSUE TITLE
Damage Icon Graphic Bug

### ISSUE THREAD

**Issue by Cosmic-Lattee** [lipefl/swade-tools#73]
So something else I have noticed is if a target isn't shaken and you apply damage that damage doesn't show up on the icon. 

Without being Shaken
![Example 1](https://user-images.githubusercontent.com/24766235/136592590-4e77700f-2f71-4c89-803d-1bbe45679300.gif)

Being Shaken
![Example 2](https://user-images.githubusercontent.com/24766235/136592634-16fe0f40-8aff-4d79-a466-acde96a1fba5.gif)
 
However this doesn't happen if the token is linked to their sheet. Instead it displays normally: 

![Example 3](https://user-images.githubusercontent.com/24766235/136592860-8960b9a2-dc5c-457d-a162-0cd1250ccfb6.gif)

Foundry/System/Module versions:
![image](https://user-images.githubusercontent.com/24766235/136592325-8efb05ff-5c89-47cd-ab89-d4039921d605.png)

**Comment by lipefl** [comment]
Fixed in v1.5.3
