### ISSUE TITLE
Automatic Unshaken sometimes rolls before the actor's turn

### ISSUE THREAD

**Issue by TheBiggerBadderWolf** [lipefl/swade-tools#74]
When an actor is shaken, the Unshaken roll sometimes happens before initiative finishes drawing, and thus happens out of order.  This seems to happen when the first character that draws initiative is Shaken - the Unshaken roll happens before the full initiative order is confirmed.

In this screenshot you can see that the Unshaken roll happened for Leon as initiative was being drawn, and he drew first, but before the other action cards drawn had even finished displaying in chat. Leon actually ended up going last in this round, not first. 

![initroll](https://user-images.githubusercontent.com/76487459/136650566-6ffc9d13-058f-4e89-bc25-f6c6d66a4bf6.png)

**Comment by lipefl** [comment]
Fixed in v1.5.3
