### ISSUE TITLE
Weapon Active Effects do not combine properly

### ISSUE THREAD

**Issue by bloy** [lipefl/swade-tools#76]
Active Effects for weapon damage modifier do not combine properly on the same weapon, apparently acting like an override for swade tools, not a string add.

Steps to reproduce:

1. Create a character (PC or NPC)
2. Create or drag a "Sword, Long" weapon to that character
3. Create an active effect "Foo" on the character, with effect "@Weapon{Sword, Long}[data.actions.dmgMod]", "Add", "+4"
4. Create an active effect "Bar" on the character, with effect "@Weapon{Sword, Long}[data.actions.dmgMod]", "Add", "+2"
5. Enable both effects 
6. Roll damage using SWADE Tools dialog

(the weapon damage modifier is a string to be able to handle "+2d6" and the like, so the sign is needed)

![image](https://user-images.githubusercontent.com/1473405/137219521-c0582bf0-22cd-4911-bc66-e6e4584149c2.png)

Expected Result:

The weapon modifiers combine, and appear in the chat card as "+2 +4".

Actual Result:

The weapon modifier uses the first applied, or the first encountered by the code, resulting in "+4"

![image](https://user-images.githubusercontent.com/1473405/137219616-c0b71837-6f6d-4bd8-a1f8-c2ab7e3884b2.png)

Additional Troubleshooting:

* The SWADE System, with SWADE Tools turned off, correctly adds both modifiers individually
  ![image](https://user-images.githubusercontent.com/1473405/137219790-ad860f0d-42b4-4edd-8e89-edb70b28da79.png)
* Work around: make one of the modifiers a different damage action on the weapon

Foundry version: 0.8.9
SWADE System Version: 0.21.2
SWADE Tools Version: 1.5.2
Other Modules Enabled: Savage Pathfinder 1.0.2, Compendium Folders 2.3.53, libWrapper 1.10.8.0

**Comment by lipefl** [comment]
Fixed in v1.5.3
