### ISSUE TITLE
Gritty damage setting doesn't appear to do anything.

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#78]
Gritty Damage setting is on, with relevant table imported and linked, but when a wildcard is injured, it never rolls on the table. Am I missing something?
<img width="1272" alt="Screen Shot 2021-10-25 at 8 45 23 AM" src="https://user-images.githubusercontent.com/69117052/138707300-ed9dfbec-4bcf-4f42-9b02-0c7e21dfd9ed.png">

**Comment by lipefl** [comment]
Fixed in v1.5.3
