### ISSUE TITLE
REQUEST: Compatibility between SWADE Tools and SWADE Sfx & Vfx Enchantments

### ISSUE THREAD

**Issue by CoherentThought** [lipefl/swade-tools#79]
SWADE Tools chat trait rolls and popup trait rolls for weapons and powers fail to trigger sound effects from the SWADE Sfx & Vfx Enchantments module. If compatibility is possible and within the modules scope, having both modules working together would greatly enhance games.

**Comment by TheBiggerBadderWolf** [comment]
I found it periodically worked then stops working. In the end i just switched to Maestro and set Item Tracks manually, though I realise that's only the sound part of what SFX & VFX Enhancements does.

**Comment by lipefl** [comment]
Fixed in v1.6.0
