### ISSUE TITLE
Allow expanding items in quick-actions

### ISSUE THREAD

**Issue by eXaminator** [lipefl/swade-tools#8]
Right now this module seems to override the click on quick action names. In the base system that click would expand the entry to show additional information. I think it would be nice to still be able to do that.

Maybe just override click interactions for places that toggle a roll in the base system?

Maybe also keep an eye on this issue I posted a few days ago for the SWADE system, it might be interesting in this regard too: https://gitlab.com/peginc/swade/-/issues/167

**Comment by lipefl** [comment]
This was intentional. Probably due to the problem you reported. With the module, almost everywhere you click will show the stats and buttons to roll. But sure it can be streamlined when out of beta. I'll mark here for review.

**Comment by eXaminator** [comment]
I just would like to point out that right now, this prevents the usage of a (for me) crucial feature of the NPC sheet: The ability to expand items to see some additional information. I often use Items (more specifically Gear, which don't allow a roll anyway), to represent special abilities that I want to have on the sheet but can't really represent using any other option. In that case I need access to the text description that is visible by expanding the entry.

**Comment by lipefl** [comment]
Can you show me a print? I tried here, but the edit button that shows the description is still functional with the module enabled.

**Comment by eXaminator** [comment]
Sure.

One the NPC sheet, Items can be expanded when clicking on the name of the item:
![image](https://user-images.githubusercontent.com/2758908/104021392-f7534e00-51be-11eb-8f95-943f1a8a7ff3.png)

But if this module is activated, a click on a weapons name will open the roll dialog while a click on a gear entry does nothing.

**Comment by lipefl** [comment]
I see. Apparently this behaviour is only for item (gear). I think i can make the dialog shows only for powers/weapons and leave the rest as it is. Thanks for pointing it out.

**Comment by eXaminator** [comment]
Well, the first item above in my screenshot is a weapon. In that case it might also be nice to easily access the info about remaining shots etc. without having to open (and subsequently close) a dialog.

Imho it would be best if modules like this (or better rolls for that matter) integrated in a way that only overrides features they are actually trying to replace / enhance (in this case rolling for an item) and leaving other features intact, because you never know who draws value from those features.

What do you think?

**Comment by lipefl** [comment]
I understand your point. That's why i'll keep as an option in settings. In my personal opinion, everywhere i click should roll, it speeds up game for everyone (that's why i made it this way). I've had problems with this before (players asking where should they click). But well, it's my personal opinion afterall. If i can please both sides (and i can) all the better :D
Since i'm making this change for 0.0.5, i'll put the setting option right away.

**Comment by eXaminator** [comment]
Awesome! I really hope they'll finde a nice way to streamline the experience in the core system (as mentioned in the linked issue above), that should remove such questions and hopefully makes it easier for modules like this to easily extend the functionality!
