### ISSUE TITLE
Request: Compability with Automated Animations

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#80]
Automated Animations works with plain swade system and br2 but unfortunately it stops making animations if SWADE Tools is enabled.
No errors in console.
Foundry 0.87
Swade 0.21.2
SWADE Tools 1.5.2 
Automated Animations 0.6.56

**Comment by spencerh117** [comment]
Encountering this as well.
Foundry 0.8.9
SWADE 0.21.4
SWADE tools 1.5.4
Automated Animations 0.6.63
No errors in console. Tested in a fresh world in multiple combinations. With just Automated Animations, no issues. With Swade tools, 2 Warnings show up in console:
![image](https://user-images.githubusercontent.com/11981994/144561702-bbfc787e-73b0-4d50-84f2-be020698db48.png)
If both Swade tools and Automated Animations are enabled, it has the same warnings as if Swade Tools only version.

**Comment by lipefl** [comment]
Fixed in v1.6.0
