### ISSUE TITLE
Ammunition Tracker not Working

### ISSUE THREAD

**Issue by RedVanGhoul** [lipefl/swade-tools#81]
I have tested with several guns, as well as from the GM perspective and logging in as a player.  None of the weapons decrease their ammo count after shooting, and can also be used when ammo is at 0 (manually set it to 0).  Power points tracking works normally.
I noticed that the configuration panel only has an option for power point tracking (enable or disable) and not one for ammo.

Picture included is activating the shooting macro immediately after using it once.  As you can see, ammo is still 8/8 despite having fired one shot.

Foundry Ver 0.8.9
SWADE Ver 0.21.3
SWADETools Ver 1.5.2
![issue](https://user-images.githubusercontent.com/67716629/141861763-3f8e22b8-bb38-4f33-b4f5-026511a6cbd3.png)

**Comment by lipefl** [comment]
Ammunition is tracked based on system configuration. Can you check if you enabled it in the system?
Power Points will be also tracked by system. This option in the module will be removed.

This is to avoid having to check in both configurations.

**Comment by RedVanGhoul** [comment]
Ah, I assumed it would be in Module Config.  It was not checked in System, but I have checked it now and it works as intended, thank you very much.
