### ISSUE TITLE
Benny icon not shown every time after SWADE 0.21.3

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#82]
After recent Savage Worlds Adventure Edition system update (v 0.21.3) benny icon in chatcard shows only 50% of times.

In this console snip 1st & 3rd roll showed benny icon correctly, while middle one missed the icon from chatcard.
![image](https://user-images.githubusercontent.com/75221971/141927022-c1537e0e-e9af-4553-9b78-6cc771ef8b18.png)

Right click>Reroll with Benny works in all chatcards normally so thats workaround for now.

System:
Foundry 0.8.9
SWADE system 0.21.3  
SWADE Tools 1.5.2
no other modules
(standalone install, havent tested on Forge)

**Comment by lipefl** [comment]
Fixed in v1.5.3
