### ISSUE TITLE
SWADE Tools breaks compendium links in chat output

### ISSUE THREAD

**Issue by Phenomen** [lipefl/swade-tools#85]
Here is how Power descriptions look in default SWADE roll:
![image](https://user-images.githubusercontent.com/138311/143627072-1923cb1a-c20a-4ed2-a4d5-b6e63607d68b.png)

Here is how Power descriptions look in SWADE Tools roll:
![image](https://user-images.githubusercontent.com/138311/143627036-c506af3c-cdf1-459d-a474-81c1a423f21c.png)

**Comment by lipefl** [comment]
Fixed in v1.6.0
