### ISSUE TITLE
Customization Request

### ISSUE THREAD

**Issue by deanopalooza** [lipefl/swade-tools#86]
(As a Forge user....)
Would it be at all possible to allow users to upload/choose their own customized status effect icons?  

Alternatively, since Combat Utility Belt (CUB) module already provides this functionality, provide an option that would allow Swade Tools to ignore its own status icons so they don't result in duplicates on the token icon?

**Comment by lipefl** [comment]
Yes. Upload own status icons could be a lot of work, but the second option could be done.

**Comment by lipefl** [comment]
Available in v1.6.0
