### ISSUE TITLE
NPC attacks don't auto calculate against parry

### ISSUE THREAD

**Issue by gravagehulk** [lipefl/swade-tools#87]
Since updating to 1.6.0, NPC attacks no longer resolve against the parry of the PCs. The PCs attacks DO resolve against the NPC Parry. This was working as expected before.

**Comment by lipefl** [comment]
I tested here and everything's working as expected. Can you elaborate more and/or send screenshots? 
The use or not of Parry is based in the "Fighting Skill" Configuration.

**Comment by gravagehulk** [comment]
Sure. As seen here, Orc attacks PC and it gives a result, but not "hit/miss". This is a melee attack with a Falchion and the Orc is from Pathfinder Savage Worlds compendium:

![image](https://user-images.githubusercontent.com/69117052/144859656-30815a9a-b189-4892-91c8-2a6161002ab8.png)

But if I do a ranged attack, it resolves as normal:

![image](https://user-images.githubusercontent.com/69117052/144859932-c0c13d67-fba7-4b9c-b885-344b1a2efd4f.png)

**Comment by gravagehulk** [comment]
Console error I'm getting:

![image](https://user-images.githubusercontent.com/69117052/144860242-ab68d4b7-f4d9-4908-a2d3-9bd4d02fe66e.png)

**Comment by lipefl** [comment]
I still cant reproduce the error. Just to clarify, the error is in the pc token (the target), when it tries to find if it's stunned.
Can you test with another pc? a new one?
Also, i think it'll work if you disable GangUp. I know it's not ideal, but until we can find the problem.

**Comment by gravagehulk** [comment]
I had tested it with several PCs and NPCs and was getting the same results (sorry I wasn't clear about that). You appear to be right about GangUp. After disabling it, it is resolving the attacks normally. Also, note that I tested Better Rolls for Savage Worlds 2 and everything was working normally at the time I was getting these errors. And it is calculating GangUp correctly as well.

![image](https://user-images.githubusercontent.com/69117052/144865256-bccd5292-8d33-4ef5-8ab5-38812a394f20.png)

**Comment by lipefl** [comment]
I just made a minor update in the gangup. Update to v1.6.1 and see if it works for you now.

**Comment by gravagehulk** [comment]
I'm still getting this error in console, but it does appear to be working with GangUp enabled now:

![image](https://user-images.githubusercontent.com/69117052/144867870-10c1f01e-8389-4ffc-9c9b-7bad240ef83e.png)

**Comment by gravagehulk** [comment]
Thank you, sir. Appreciate the quick fix. I'm really looking forward to the Adventure Card enhancements that are coming.
