### ISSUE TITLE
Not calculating hits/misses when targeting vehicles

### ISSUE THREAD

**Issue by RedVanGhoul** [lipefl/swade-tools#89]
Foundry Version - 0.8.9
SWADE Version - 0.21.4
SWADE Tools Version - 1.6.3

SWADE Tools does not seem to be automatically determining success or failure for attacks when vehicles are targeted.  When anyone, including a vehicle, targets a creature then there is the normal option in the chat window to calculate damage (if hit, given example is a miss, but it tells me I missed so it's working correctly.  Pic 1).

However, when targeting a vehicle (pictures 2 and 3) it simply displays the result of the roll but does not tell me whether I hit or miss and does not give me the button to calculate damage.

Clicking "Damage" in the weapon's dialog box will still calculate against a vehicle's toughness (pictures 4 and 5), but I have to reopen the weapon's dialog box in order to do that.  Obviously I can just have my players roll the shooting test separate and then roll damage after (which I end up doing anyways because vehicles can only have one
![issue1](https://user-images.githubusercontent.com/67716629/146683328-87723968-56b0-457f-a6d2-e4b807da8ab3.png)
![issue2](https://user-images.githubusercontent.com/67716629/146683329-cc36b1fa-abc3-4c73-ac8f-b6ff67236f09.png)
![issue3](https://user-images.githubusercontent.com/67716629/146683330-095867b5-42f3-4262-84ed-3bc50ea7befa.png)
![issue4](https://user-images.githubusercontent.com/67716629/146683331-290a5b31-0118-4ce4-b874-6cef1656f20c.png)
![issue5](https://user-images.githubusercontent.com/67716629/146683332-4a5c194d-467d-4528-a4f3-ae0be278851a.png)
 operator currently), but that defeats the purpose of the automation.

**Comment by lipefl** [comment]
Fixed in v1.6.4
