### ISSUE TITLE
Wait for Dice So Nice rolls to be finished

### ISSUE THREAD

**Issue by eXaminator** [lipefl/swade-tools#9]
I noticed at least one roll (the automatic roll to remove shaken) which does not wait for the dice so nice roll to be finished before posting / applying the result. Attack and damage rolls seem to behave as expected.

**Comment by lipefl** [comment]
I wasn't using dice so nice for testing, there's no code for it in the module. It's probably something automatic, but i intend to deal and test it for v1.0.0
