### ISSUE TITLE
Request: Compatibility to Foundry v9

### ISSUE THREAD

**Issue by Alis-72** [lipefl/swade-tools#90]
Weapon rolls (skill & damage) only produce error message
Skillrolls work ok.

When rolling for weapon, in console, there is error:

Uncaught Error: TypeError: Cannot read properties of undefined (reading '0')
    at Dialog.submit (foundry.js:43721)
    at Dialog._onClickButton (foundry.js:43680)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
submit @ foundry.js:43721
_onClickButton @ foundry.js:43680
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by lipefl** [comment]
Fixed in v1.7.0
I haven't fully tested with Foundry 9, if you find any other bugs, please let me know. Thanks
