### ISSUE TITLE
Damage not rolled properly with traits different from strength.

### ISSUE THREAD

**Issue by parvusdomus** [lipefl/swade-tools#93]
FVTT v9 comp 238
swade 0.22.4
swade-tools 1.7.2

If you have a weapon that rolls its damage using agility or any other trait different from strength, the trait dice is never rolled.

For example we have a character that uses a scimitar with damage @str+1d8 and that character takes an advantage that allows him to calculate its melee damage with agility instead of strength: @agi+1d8

In the first case: @str+1d8 when rolling damage for that machine both the strength dice and the d8 are rolled. But in the second one: @agi+1d8, when rolling damage only the d8 is rolled. Same happens for all the other traits that are not @str. 

If I deactivate swade tools and roll damage with vanilla swade both dice are rolled properly always regardless of the trait used.

**Comment by lipefl** [comment]
I didn't know this was possible. Solved in v1.7.3
