### ISSUE TITLE
All wildcards receive +2 bonus when joker is drawn in combat

### ISSUE THREAD

**Issue by LoreUK** [lipefl/swade-tools#95]
Whenever a joker is drawn during initiative in combat, all wild card characters (friendly & hostile) are receiving a +2 joker bonus to their rolls.

This seems to occur even if the "Joker's Wild" setting rule is disabled in the swade system settings. I have tested this with "minimal modules" installed (Compendium Folders, libWrapper, Savage Worlds Adventure Edition Core Rules & SWADE Tools) and confirmed the issue still occurs.

**Comment by lipefl** [comment]
Can you update Swade Tools and check again? This was solved in the last update.
If you're still having problems, feel free to re-open the issue.

**Comment by LoreUK** [comment]
Thank you for the help. I just updated swade tools and tested and it
appears to be working as expected.
