### ISSUE TITLE
Status won't disappear after player's turn

### ISSUE THREAD

**Issue by JusticeTheAwesome** [lipefl/swade-tools#96]
Simple as the title. Maybe is an incompatibility problem?. My players keep the Vulnerable status even after their turn. In addition for some reason whenever they are shaken, when they turn begins it won't unshake automatically.

**Comment by lipefl** [comment]
I tested here and everything is working. Can you tell me the version of Foundry, Swade System and Swade Tools? Also, try to look at console (F12) when a new turn starts/ends to see if anything appears. Another thing you could try is disabling all modules, except swade tools, and see if it works.
