### ISSUE TITLE
Mistakes in the french translation

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#97]
Hi, i havec noticed somme mistake in the french translation.
the most important is "Raise" translated as "Augmenter" or the offical translation is "Prouesse".

Can help on this issues.

Best regards,

Arnok

**Comment by lipefl** [comment]
I can fix this in the next upgrade. But i have no knowledge about french translation. If you find any other mistakes just download the translation file, update and send me here (or as a pull request)

**Comment by lipefl** [comment]
By the way, i'd rather wait for you to send me the revised file, i just noticed Augmenter appears in a lot of places and i am afraid i'll  just make more mistakes since i don't know a lot about french.

**Comment by Arnok13** [comment]
i will do that ;)
