### ISSUE TITLE
token (linked) statuses not displayed on new scene

### ISSUE THREAD

**Issue by Arnok13** [lipefl/swade-tools#98]
Hi,

i'm not sure if it is a Swade Tools or Core issue, bur when a token is on a scene and the statuses are updated in another scene, the statuses are not updated.

for example, if on a second scene, the character associated to a linked token get a wound, the token for the same character won't display the wound number (but the character sheet is fine - linked)

Best regards.

**Comment by lipefl** [comment]
I'm not sure if that's how supposed to work, but I found another bug while testing this: when creating a new token, it's not displaying status icons.
I'll investigate both cases. Thanks

**Comment by lipefl** [comment]
The problem with creating a new token is fixed now in 1.7.5. 
Now, you can delete the token in the "new" active scene and create again, it'll show all status.

About the tokens between scenes:
Foundry api only gives me the tokens in the active scene, i'd have to find a way to bypass this, also it could cause perfomance issues (in a case where there are too many scenes). So i'll leave it that way for now. I heard swade system is about to implement status icons as well, maybe they'll solve this problem.
